// =============================================================================
// STOCK HOMBRE — Generado automáticamente con scripts/importar-stock.py
// Fuente: Google Sheets (hoja INVENTARIO, columna T = HOMBRE/MUJER)
// Edita el sheet y vuelve a ejecutar el script para actualizar.
// =============================================================================
const productosHombre = [
    {
        id: 2,
        nombre: "ARRIVAL REGULAR FIT",
        categoria: "Hombre",
        precio: 550.00,
        stock: 1,
        imagen1: "hombre/2.webp",
        imagen2: "hombre/2.1.webp",
        talla: "S",
        tallaBase: "S",
        tipo: "T-Shirt",
        color: "Verde",
        marca: "Gym Shark",
        precioMayoreo: 485.71,
        mayoreo: false,
        posicionCarrusel: 0,
        coleccion: "",
        coleccionCatalogo: ""
    },
    {
        id: 3,
        nombre: "COLLEGIATE 9 SHORT",
        categoria: "Hombre",
        precio: 600.00,
        stock: 3,
        imagen1: "hombre/3.webp",
        imagen2: "hombre/3.1.webp",
        talla: "M",
        tallaBase: "M",
        tipo: "Short",
        color: "Verde",
        marca: "Gym Shark",
        precioMayoreo: 480.00,
        mayoreo: true,
        posicionCarrusel: 0,
        coleccion: "",
        coleccionCatalogo: ""
    },
    {
        id: 4,
        nombre: "COLLEGIATE 9 SHORT",
        categoria: "Hombre",
        precio: 600.00,
        stock: 1,
        imagen1: "hombre/4.webp",
        imagen2: "hombre/4.1.webp",
        talla: "S",
        tallaBase: "S",
        tipo: "Short",
        color: "Gris",
        marca: "Gym Shark",
        precioMayoreo: 480.00,
        mayoreo: true,
        posicionCarrusel: 0,
        coleccion: "",
        coleccionCatalogo: ""
    },
    {
        id: 5,
        nombre: "COLLEGIATE 9 SHORT",
        categoria: "Hombre",
        precio: 600.00,
        stock: 1,
        imagen1: "hombre/5.webp",
        imagen2: "hombre/5.1.webp",
        talla: "L",
        tallaBase: "L",
        tipo: "Short",
        color: "Gris",
        marca: "Gym Shark",
        precioMayoreo: 480.00,
        mayoreo: true,
        posicionCarrusel: 0,
        coleccion: "",
        coleccionCatalogo: ""
    },
    {
        id: 6,
        nombre: "COLLEGIATE 9 SHORT",
        categoria: "Hombre",
        precio: 600.00,
        stock: 2,
        imagen1: "hombre/6.webp",
        imagen2: "hombre/6.1.webp",
        talla: "S",
        tallaBase: "S",
        tipo: "Short",
        color: "Verde",
        marca: "Gym Shark",
        precioMayoreo: 480.00,
        mayoreo: true,
        posicionCarrusel: 0,
        coleccion: "",
        coleccionCatalogo: ""
    },
    {
        id: 7,
        nombre: "COLLEGIATE 9 SHORT",
        categoria: "Hombre",
        precio: 600.00,
        stock: 2,
        imagen1: "hombre/7.webp",
        imagen2: "hombre/7.1.webp",
        talla: "M",
        tallaBase: "M",
        tipo: "Short",
        color: "Negro",
        marca: "Gym Shark",
        precioMayoreo: 480.00,
        mayoreo: true,
        posicionCarrusel: 0,
        coleccion: "",
        coleccionCatalogo: ""
    },
    {
        id: 8,
        nombre: "COLLEGIATE 9 SHORT",
        categoria: "Hombre",
        precio: 600.00,
        stock: 1,
        imagen1: "hombre/8.webp",
        imagen2: "hombre/8.1.webp",
        talla: "S",
        tallaBase: "S",
        tipo: "Short",
        color: "Negro",
        marca: "Gym Shark",
        precioMayoreo: 480.00,
        mayoreo: true,
        posicionCarrusel: 0,
        coleccion: "",
        coleccionCatalogo: ""
    },
    {
        id: 9,
        nombre: "ELEMENT BASELAYER",
        categoria: "Hombre",
        precio: 1000.00,
        stock: 1,
        imagen1: "hombre/9.webp",
        imagen2: "hombre/9.1.webp",
        talla: "S",
        tallaBase: "S",
        tipo: "T-Shirt",
        color: "Blanco",
        marca: "Gym Shark",
        precioMayoreo: 800.00,
        mayoreo: true,
        posicionCarrusel: 0,
        coleccion: "",
        coleccionCatalogo: ""
    },
    {
        id: 10,
        nombre: "ELEMENT BASELAYER",
        categoria: "Hombre",
        precio: 1000.00,
        stock: 1,
        imagen1: "hombre/10.webp",
        imagen2: "hombre/10.1.webp",
        talla: "M",
        tallaBase: "M",
        tipo: "T-Shirt",
        color: "Blanco",
        marca: "Gym Shark",
        precioMayoreo: 800.00,
        mayoreo: true,
        posicionCarrusel: 0,
        coleccion: "",
        coleccionCatalogo: ""
    },
    {
        id: 12,
        nombre: "FIT ELITE 5",
        categoria: "Hombre",
        precio: 600.00,
        stock: 1,
        imagen1: "hombre/12.webp",
        imagen2: "hombre/12.1.webp",
        talla: "S",
        tallaBase: "S",
        tipo: "Short",
        color: "Verde",
        marca: "Gym Shark",
        precioMayoreo: 480.00,
        mayoreo: true,
        posicionCarrusel: 0,
        coleccion: "",
        coleccionCatalogo: ""
    },
    {
        id: 13,
        nombre: "LIFTING MESH 5",
        categoria: "Hombre",
        precio: 550.00,
        stock: 1,
        imagen1: "hombre/13.webp",
        imagen2: "hombre/13.1.webp",
        talla: "S",
        tallaBase: "S",
        tipo: "Short",
        color: "Gris",
        marca: "Gym Shark",
        precioMayoreo: 440.00,
        mayoreo: true,
        posicionCarrusel: 0,
        coleccion: "",
        coleccionCatalogo: ""
    },
    {
        id: 15,
        nombre: "LIFTING MESH 5",
        categoria: "Hombre",
        precio: 550.00,
        stock: 3,
        imagen1: "hombre/15.webp",
        imagen2: "hombre/15.1.webp",
        talla: "S",
        tallaBase: "S",
        tipo: "Short",
        color: "Negro",
        marca: "Gym Shark",
        precioMayoreo: 440.00,
        mayoreo: true,
        posicionCarrusel: 0,
        coleccion: "",
        coleccionCatalogo: ""
    },
    {
        id: 17,
        nombre: "LIFTING MESH 5",
        categoria: "Hombre",
        precio: 500.00,
        stock: 2,
        imagen1: "hombre/17.webp",
        imagen2: "hombre/17.1.webp",
        talla: "M",
        tallaBase: "M",
        tipo: "Short",
        color: "Negro",
        marca: "Gym Shark",
        precioMayoreo: 400.00,
        mayoreo: true,
        posicionCarrusel: 0,
        coleccion: "",
        coleccionCatalogo: ""
    },
    {
        id: 18,
        nombre: "LIFTING MESH 5",
        categoria: "Hombre",
        precio: 550.00,
        stock: 3,
        imagen1: "hombre/18.webp",
        imagen2: "hombre/18.1.webp",
        talla: "S",
        tallaBase: "S",
        tipo: "Short",
        color: "Verde",
        marca: "Gym Shark",
        precioMayoreo: 440.00,
        mayoreo: true,
        posicionCarrusel: 0,
        coleccion: "",
        coleccionCatalogo: ""
    },
    {
        id: 19,
        nombre: "SPORT PANEL 7",
        categoria: "Hombre",
        precio: 500.00,
        stock: 1,
        imagen1: "hombre/19.webp",
        imagen2: "hombre/19.1.webp",
        talla: "S",
        tallaBase: "S",
        tipo: "Short",
        color: "Marrón",
        marca: "Gym Shark",
        precioMayoreo: 0.00,
        mayoreo: false,
        posicionCarrusel: 0,
        coleccion: "",
        coleccionCatalogo: ""
    },
    {
        id: 20,
        nombre: "SPORT PANEL 7",
        categoria: "Hombre",
        precio: 500.00,
        stock: 2,
        imagen1: "hombre/20.webp",
        imagen2: "hombre/20.1.webp",
        talla: "S",
        tallaBase: "S",
        tipo: "Short",
        color: "Azul",
        marca: "Gym Shark",
        precioMayoreo: 0.00,
        mayoreo: false,
        posicionCarrusel: 0,
        coleccion: "",
        coleccionCatalogo: ""
    },
    {
        id: 21,
        nombre: "VARSITY MESH",
        categoria: "Hombre",
        precio: 500.00,
        stock: 1,
        imagen1: "hombre/21.webp",
        imagen2: "hombre/21.1.webp",
        talla: "S",
        tallaBase: "S",
        tipo: "Short",
        color: "Rojo",
        marca: "Gym Shark",
        precioMayoreo: 400.00,
        mayoreo: true,
        posicionCarrusel: 0,
        coleccion: "",
        coleccionCatalogo: ""
    },
    {
        id: 22,
        nombre: "WAFFLE SHORT",
        categoria: "Hombre",
        precio: 700.00,
        stock: 2,
        imagen1: "hombre/22.webp",
        imagen2: "hombre/22.1.jpg",
        talla: "M",
        tallaBase: "M",
        tipo: "Short",
        color: "Negro",
        marca: "Gym Shark",
        precioMayoreo: 560.00,
        mayoreo: false,
        posicionCarrusel: 0,
        coleccion: "",
        coleccionCatalogo: ""
    },
    {
        id: 23,
        nombre: "WAFFLE SHORT",
        categoria: "Hombre",
        precio: 700.00,
        stock: 1,
        imagen1: "hombre/23.webp",
        imagen2: "hombre/23.1.webp",
        talla: "M",
        tallaBase: "M",
        tipo: "Short",
        color: "Gris",
        marca: "Gym Shark",
        precioMayoreo: 560.00,
        mayoreo: false,
        posicionCarrusel: 0,
        coleccion: "",
        coleccionCatalogo: ""
    },
    {
        id: 25,
        nombre: "STRENGHT OF TOMORROW ZIP UP HOODIE",
        categoria: "Hombre",
        precio: 990.00,
        stock: 2,
        imagen1: "hombre/25.webp",
        imagen2: "hombre/25.1.webp",
        talla: "L",
        tallaBase: "L",
        tipo: "Hoodie",
        color: "Negro",
        marca: "Gym Shark",
        precioMayoreo: 920.00,
        mayoreo: false,
        posicionCarrusel: 0,
        coleccion: "",
        coleccionCatalogo: ""
    },
    {
        id: 26,
        nombre: "CREST T-SHIRT",
        categoria: "Hombre",
        precio: 550.00,
        stock: 2,
        imagen1: "hombre/26.webp",
        imagen2: "hombre/26.1.webp",
        talla: "S",
        tallaBase: "S",
        tipo: "T-Shirt",
        color: "Azul",
        marca: "Gym Shark",
        precioMayoreo: 450.00,
        mayoreo: false,
        posicionCarrusel: 0,
        coleccion: "",
        coleccionCatalogo: ""
    },
    {
        id: 27,
        nombre: "CREST T-SHIRT",
        categoria: "Hombre",
        precio: 550.00,
        stock: 2,
        imagen1: "hombre/27.webp",
        imagen2: "hombre/27.1.jpg",
        talla: "M",
        tallaBase: "M",
        tipo: "T-Shirt",
        color: "Azul",
        marca: "Gym Shark",
        precioMayoreo: 450.00,
        mayoreo: false,
        posicionCarrusel: 0,
        coleccion: "",
        coleccionCatalogo: ""
    },
    {
        id: 28,
        nombre: "CREST T-SHIRT",
        categoria: "Hombre",
        precio: 550.00,
        stock: 2,
        imagen1: "hombre/28.webp",
        imagen2: "hombre/28.1.webp",
        talla: "L",
        tallaBase: "L",
        tipo: "T-Shirt",
        color: "Azul",
        marca: "Gym Shark",
        precioMayoreo: 450.00,
        mayoreo: false,
        posicionCarrusel: 0,
        coleccion: "",
        coleccionCatalogo: ""
    },
    {
        id: 29,
        nombre: "CREST T-SHIRT",
        categoria: "Hombre",
        precio: 550.00,
        stock: 1,
        imagen1: "hombre/29.webp",
        imagen2: "hombre/29.1.webp",
        talla: "S",
        tallaBase: "S",
        tipo: "T-Shirt",
        color: "Marrón",
        marca: "Gym Shark",
        precioMayoreo: 450.00,
        mayoreo: false,
        posicionCarrusel: 0,
        coleccion: "",
        coleccionCatalogo: ""
    },
    {
        id: 30,
        nombre: "CREST T-SHIRT",
        categoria: "Hombre",
        precio: 550.00,
        stock: 2,
        imagen1: "hombre/30.webp",
        imagen2: "hombre/30.1.jpg",
        talla: "M",
        tallaBase: "M",
        tipo: "T-Shirt",
        color: "Marrón",
        marca: "Gym Shark",
        precioMayoreo: 450.00,
        mayoreo: false,
        posicionCarrusel: 0,
        coleccion: "",
        coleccionCatalogo: ""
    },
    {
        id: 31,
        nombre: "CREST T-SHIRT",
        categoria: "Hombre",
        precio: 550.00,
        stock: 2,
        imagen1: "hombre/31.webp",
        imagen2: "hombre/31.1.webp",
        talla: "L",
        tallaBase: "L",
        tipo: "T-Shirt",
        color: "Marrón",
        marca: "Gym Shark",
        precioMayoreo: 450.00,
        mayoreo: false,
        posicionCarrusel: 0,
        coleccion: "",
        coleccionCatalogo: ""
    },
    {
        id: 33,
        nombre: "RUNNING LONG SLEEVE T-SHIRT",
        categoria: "Hombre",
        precio: 600.00,
        stock: 2,
        imagen1: "hombre/33.webp",
        imagen2: "hombre/33.1.webp",
        talla: "S",
        tallaBase: "S",
        tipo: "Long Sleeve",
        color: "Verde",
        marca: "Gym Shark",
        precioMayoreo: 480.00,
        mayoreo: false,
        posicionCarrusel: 0,
        coleccion: "",
        coleccionCatalogo: ""
    },
    {
        id: 34,
        nombre: "RUNNING LONG SLEEVE T-SHIRT",
        categoria: "Hombre",
        precio: 600.00,
        stock: 2,
        imagen1: "hombre/34.webp",
        imagen2: "hombre/34.1.webp",
        talla: "M",
        tallaBase: "M",
        tipo: "Long Sleeve",
        color: "Verde",
        marca: "Gym Shark",
        precioMayoreo: 480.00,
        mayoreo: false,
        posicionCarrusel: 0,
        coleccion: "",
        coleccionCatalogo: ""
    },
    {
        id: 35,
        nombre: "COLLEGIATE CONTRAST 5",
        categoria: "Hombre",
        precio: 550.00,
        stock: 3,
        imagen1: "hombre/35.webp",
        imagen2: "hombre/35.1.webp",
        talla: "S",
        tallaBase: "S",
        tipo: "Short",
        color: "Azul",
        marca: "Gym Shark",
        precioMayoreo: 440.00,
        mayoreo: true,
        posicionCarrusel: 0,
        coleccion: "",
        coleccionCatalogo: ""
    },
    {
        id: 36,
        nombre: "FIND YOUR SPEED JACKET",
        categoria: "Hombre",
        precio: 990.00,
        stock: 2,
        imagen1: "hombre/36.webp",
        imagen2: "hombre/36.1.webp",
        talla: "S",
        tallaBase: "S",
        tipo: "Hoodie",
        color: "Gris",
        marca: "Gym Shark",
        precioMayoreo: 950.00,
        mayoreo: false,
        posicionCarrusel: 0,
        coleccion: "",
        coleccionCatalogo: ""
    },
    {
        id: 37,
        nombre: "KNITTED SCARF/BEANIE GIFT SET",
        categoria: "Hombre",
        precio: 380.00,
        stock: 1,
        imagen1: "hombre/37.webp",
        imagen2: "hombre/37.1.webp",
        talla: "ONE SIZE",
        tallaBase: "ONE SIZE",
        tipo: "Accesorios",
        color: "Blanco",
        marca: "Gym Shark",
        precioMayoreo: 57.14,
        mayoreo: false,
        posicionCarrusel: 0,
        coleccion: "",
        coleccionCatalogo: ""
    },
    {
        id: 38,
        nombre: "ESSENTIAL OVERSIZED JOGGERS",
        categoria: "Hombre",
        precio: 750.00,
        stock: 3,
        imagen1: "hombre/38.webp",
        imagen2: "hombre/38.1.webp",
        talla: "S",
        tallaBase: "S",
        tipo: "Joggers",
        color: "Azul",
        marca: "Gym Shark",
        precioMayoreo: 500.00,
        mayoreo: false,
        posicionCarrusel: 0,
        coleccion: "",
        coleccionCatalogo: ""
    },
    {
        id: 39,
        nombre: "ESSENTIAL OVERSIZED JOGGERS",
        categoria: "Hombre",
        precio: 750.00,
        stock: 3,
        imagen1: "hombre/39.webp",
        imagen2: "hombre/39.1.webp",
        talla: "S",
        tallaBase: "S",
        tipo: "Joggers",
        color: "Gris",
        marca: "Gym Shark",
        precioMayoreo: 500.00,
        mayoreo: false,
        posicionCarrusel: 0,
        coleccion: "",
        coleccionCatalogo: ""
    },
    {
        id: 41,
        nombre: "2012 STRENGTH JOGGERS",
        categoria: "Hombre",
        precio: 850.00,
        stock: 1,
        imagen1: "hombre/41.webp",
        imagen2: "hombre/41.1.webp",
        talla: "L",
        tallaBase: "L",
        tipo: "Joggers",
        color: "Gris",
        marca: "Gym Shark",
        precioMayoreo: 0.00,
        mayoreo: false,
        posicionCarrusel: 0,
        coleccion: "",
        coleccionCatalogo: ""
    },
    {
        id: 42,
        nombre: "CREST SWEATSHIRT",
        categoria: "Hombre",
        precio: 750.00,
        stock: 3,
        imagen1: "hombre/42.webp",
        imagen2: "hombre/42.1.webp",
        talla: "S",
        tallaBase: "S",
        tipo: "Hoodie",
        color: "Negro",
        marca: "Gym Shark",
        precioMayoreo: 576.00,
        mayoreo: true,
        posicionCarrusel: 0,
        coleccion: "",
        coleccionCatalogo: ""
    },
    {
        id: 43,
        nombre: "RETAKE ANORAK",
        categoria: "Hombre",
        precio: 1000.00,
        stock: 2,
        imagen1: "hombre/43.webp",
        imagen2: "hombre/43.1.webp",
        talla: "L",
        tallaBase: "L",
        tipo: "Jacket",
        color: "Negro",
        marca: "Gym Shark",
        precioMayoreo: 800.00,
        mayoreo: true,
        posicionCarrusel: 0,
        coleccion: "",
        coleccionCatalogo: ""
    },
    {
        id: 44,
        nombre: "FIT REPEAT 6",
        categoria: "Hombre",
        precio: 550.00,
        stock: 1,
        imagen1: "hombre/44.webp",
        imagen2: "hombre/44.1.webp",
        talla: "S",
        tallaBase: "S",
        tipo: "Short",
        color: "Azul",
        marca: "Gym Shark",
        precioMayoreo: 420.00,
        mayoreo: false,
        posicionCarrusel: 0,
        coleccion: "",
        coleccionCatalogo: ""
    },
    {
        id: 45,
        nombre: "TACTICAL 6 SHORT",
        categoria: "Hombre",
        precio: 550.00,
        stock: 2,
        imagen1: "hombre/45.webp",
        imagen2: "hombre/45.1.webp",
        talla: "S",
        tallaBase: "S",
        tipo: "Short",
        color: "Verde",
        marca: "Gym Shark",
        precioMayoreo: 520.00,
        mayoreo: false,
        posicionCarrusel: 0,
        coleccion: "",
        coleccionCatalogo: ""
    },
    {
        id: 46,
        nombre: "TACTICAL 6 SHORT",
        categoria: "Hombre",
        precio: 720.00,
        stock: 1,
        imagen1: "hombre/46.webp",
        imagen2: "hombre/46.1.webp",
        talla: "S",
        tallaBase: "S",
        tipo: "Short",
        color: "Negro",
        marca: "Gym Shark",
        precioMayoreo: 576.00,
        mayoreo: true,
        posicionCarrusel: 0,
        coleccion: "",
        coleccionCatalogo: ""
    },
    {
        id: 47,
        nombre: "ARRIVAL SHORT",
        categoria: "Hombre",
        precio: 550.00,
        stock: 1,
        imagen1: "hombre/47.webp",
        imagen2: "hombre/47.1.webp",
        talla: "L",
        tallaBase: "L",
        tipo: "Short",
        color: "Blanco",
        marca: "Gym Shark",
        precioMayoreo: 440.00,
        mayoreo: true,
        posicionCarrusel: 0,
        coleccion: "",
        coleccionCatalogo: ""
    },
    {
        id: 48,
        nombre: "ARRIVAL SHORT",
        categoria: "Hombre",
        precio: 550.00,
        stock: 1,
        imagen1: "hombre/48.webp",
        imagen2: "hombre/48.1.webp",
        talla: "M",
        tallaBase: "M",
        tipo: "Short",
        color: "Blanco",
        marca: "Gym Shark",
        precioMayoreo: 0.00,
        mayoreo: false,
        posicionCarrusel: 0,
        coleccion: "",
        coleccionCatalogo: ""
    },
    {
        id: 49,
        nombre: "2012 STRENGHT JOGGERS",
        categoria: "Hombre",
        precio: 700.00,
        stock: 1,
        imagen1: "hombre/49.webp",
        imagen2: "hombre/49.1.webp",
        talla: "M",
        tallaBase: "M",
        tipo: "Joggers",
        color: "Gris",
        marca: "Gym Shark",
        precioMayoreo: 680.00,
        mayoreo: false,
        posicionCarrusel: 0,
        coleccion: "",
        coleccionCatalogo: ""
    },
    {
        id: 50,
        nombre: "2012 STRENGHT JOGGERS",
        categoria: "Hombre",
        precio: 700.00,
        stock: 1,
        imagen1: "hombre/50.webp",
        imagen2: "hombre/50.1.webp",
        talla: "S",
        tallaBase: "S",
        tipo: "Joggers",
        color: "Gris",
        marca: "Gym Shark",
        precioMayoreo: 680.00,
        mayoreo: false,
        posicionCarrusel: 0,
        coleccion: "",
        coleccionCatalogo: ""
    },
    {
        id: 51,
        nombre: "CREST JOGGERS",
        categoria: "Hombre",
        precio: 750.00,
        stock: 1,
        imagen1: "hombre/51.webp",
        imagen2: "hombre/51.1.webp",
        talla: "M",
        tallaBase: "M",
        tipo: "Joggers",
        color: "Negro",
        marca: "Gym Shark",
        precioMayoreo: 600.00,
        mayoreo: true,
        posicionCarrusel: 0,
        coleccion: "",
        coleccionCatalogo: ""
    },
    {
        id: 52,
        nombre: "CREST JOGGERS",
        categoria: "Hombre",
        precio: 750.00,
        stock: 1,
        imagen1: "hombre/52.webp",
        imagen2: "hombre/52.1.webp",
        talla: "M",
        tallaBase: "M",
        tipo: "Joggers",
        color: "Gris",
        marca: "Gym Shark",
        precioMayoreo: 600.00,
        mayoreo: true,
        posicionCarrusel: 0,
        coleccion: "",
        coleccionCatalogo: ""
    },
    {
        id: 53,
        nombre: "CREST JOGGERS",
        categoria: "Hombre",
        precio: 750.00,
        stock: 2,
        imagen1: "hombre/53.webp",
        imagen2: "hombre/53.1.webp",
        talla: "L",
        tallaBase: "L",
        tipo: "Joggers",
        color: "Gris",
        marca: "Gym Shark",
        precioMayoreo: 600.00,
        mayoreo: true,
        posicionCarrusel: 0,
        coleccion: "",
        coleccionCatalogo: ""
    },
    {
        id: 54,
        nombre: "HERITAGE 5 SHORTS",
        categoria: "Hombre",
        precio: 550.00,
        stock: 1,
        imagen1: "hombre/54.webp",
        imagen2: "hombre/54.1.webp",
        talla: "S",
        tallaBase: "S",
        tipo: "Short",
        color: "Gris",
        marca: "Gym Shark",
        precioMayoreo: 440.00,
        mayoreo: true,
        posicionCarrusel: 0,
        coleccion: "",
        coleccionCatalogo: ""
    },
    {
        id: 55,
        nombre: "HERITAGE 5 SHORTS",
        categoria: "Hombre",
        precio: 550.00,
        stock: 1,
        imagen1: "hombre/55.webp",
        imagen2: "hombre/55.1.webp",
        talla: "S",
        tallaBase: "S",
        tipo: "Short",
        color: "Gris",
        marca: "Gym Shark",
        precioMayoreo: 440.00,
        mayoreo: true,
        posicionCarrusel: 0,
        coleccion: "",
        coleccionCatalogo: ""
    },
    {
        id: 58,
        nombre: "VENOM JERSEYS",
        categoria: "Hombre",
        precio: 750.00,
        stock: 1,
        imagen1: "hombre/58.webp",
        imagen2: "",
        talla: "S",
        tallaBase: "S",
        tipo: "Jersey",
        color: "Negro",
        marca: "YoungLA",
        precioMayoreo: 680.00,
        mayoreo: false,
        posicionCarrusel: 0,
        coleccion: "",
        coleccionCatalogo: ""
    },
    {
        id: 59,
        nombre: "OLY LIFTING STRAPS",
        categoria: "Hombre",
        precio: 350.00,
        stock: 4,
        imagen1: "hombre/59.webp",
        imagen2: "hombre/59.1.webp",
        talla: "ONE SIZE",
        tallaBase: "ONE SIZE",
        tipo: "Accesorios",
        color: "Azul",
        marca: "Gym Shark",
        precioMayoreo: 280.00,
        mayoreo: true,
        posicionCarrusel: 0,
        coleccion: "",
        coleccionCatalogo: ""
    },
    {
        id: 61,
        nombre: "COLLEGIATE CREW SOCKS 3PK",
        categoria: "Hombre",
        precio: 520.00,
        stock: 1,
        imagen1: "hombre/61.webp",
        imagen2: "hombre/61.1.webp",
        talla: "M",
        tallaBase: "M",
        tipo: "Accesorios",
        color: "Rosa",
        marca: "Gym Shark",
        precioMayoreo: 416.00,
        mayoreo: true,
        posicionCarrusel: 0,
        coleccion: "",
        coleccionCatalogo: ""
    },
    {
        id: 62,
        nombre: "COLLEGIATE CREW SOCKS 3PK",
        categoria: "Hombre",
        precio: 520.00,
        stock: 1,
        imagen1: "hombre/62.webp",
        imagen2: "hombre/62.1.webp",
        talla: "M",
        tallaBase: "M",
        tipo: "Accesorios",
        color: "Azul",
        marca: "Gym Shark",
        precioMayoreo: 416.00,
        mayoreo: true,
        posicionCarrusel: 0,
        coleccion: "",
        coleccionCatalogo: ""
    },
    {
        id: 63,
        nombre: "CREW SOCKS 5 PK",
        categoria: "Hombre",
        precio: 450.00,
        stock: 5,
        imagen1: "hombre/63.webp",
        imagen2: "hombre/63.1.webp",
        talla: "S",
        tallaBase: "S",
        tipo: "Accesorios",
        color: "Negro",
        marca: "Gym Shark",
        precioMayoreo: 360.00,
        mayoreo: true,
        posicionCarrusel: 0,
        coleccion: "",
        coleccionCatalogo: ""
    },
    {
        id: 64,
        nombre: "COLLEGIATE CAP",
        categoria: "Hombre",
        precio: 500.00,
        stock: 2,
        imagen1: "hombre/64.webp",
        imagen2: "hombre/64.1.webp",
        talla: "ONE SIZE",
        tallaBase: "ONE SIZE",
        tipo: "Accesorios",
        color: "Azul",
        marca: "Gym Shark",
        precioMayoreo: 400.00,
        mayoreo: true,
        posicionCarrusel: 0,
        coleccion: "",
        coleccionCatalogo: ""
    },
    {
        id: 65,
        nombre: "DEEP KNIT BEANIE",
        categoria: "Hombre",
        precio: 350.00,
        stock: 3,
        imagen1: "hombre/65.webp",
        imagen2: "hombre/65.1.webp",
        talla: "ONE SIZE",
        tallaBase: "ONE SIZE",
        tipo: "Accesorios",
        color: "Rosa",
        marca: "Gym Shark",
        precioMayoreo: 57.14,
        mayoreo: false,
        posicionCarrusel: 0,
        coleccion: "",
        coleccionCatalogo: ""
    },
    {
        id: 67,
        nombre: "2.2L WATER BOTTLE",
        categoria: "Hombre",
        precio: 510.00,
        stock: 2,
        imagen1: "hombre/67.webp",
        imagen2: "hombre/67.1.webp",
        talla: "ONE SIZE",
        tallaBase: "ONE SIZE",
        tipo: "Accesorios",
        color: "Negro",
        marca: "Gym Shark",
        precioMayoreo: 408.00,
        mayoreo: true,
        posicionCarrusel: 0,
        coleccion: "",
        coleccionCatalogo: ""
    },
    {
        id: 68,
        nombre: "500ML BOTTLE",
        categoria: "Hombre",
        precio: 500.00,
        stock: 2,
        imagen1: "hombre/68.webp",
        imagen2: "hombre/68.1.webp",
        talla: "ONE SIZE",
        tallaBase: "ONE SIZE",
        tipo: "Accesorios",
        color: "Gris",
        marca: "Gym Shark",
        precioMayoreo: 600.00,
        mayoreo: false,
        posicionCarrusel: 0,
        coleccion: "",
        coleccionCatalogo: ""
    },
    {
        id: 69,
        nombre: "SUPERMAN COMPRESSION 4117",
        categoria: "Hombre",
        precio: 1300.00,
        stock: 1,
        imagen1: "hombre/69.webp",
        imagen2: "",
        talla: "M",
        tallaBase: "M",
        tipo: "Compression Shirt",
        color: "Negro",
        marca: "YoungLA",
        precioMayoreo: 1150.00,
        mayoreo: false,
        posicionCarrusel: 0,
        coleccion: "",
        coleccionCatalogo: ""
    },
    {
        id: 70,
        nombre: "ARRIVAL CONTRAST T-SHIRT",
        categoria: "Hombre",
        precio: 550.00,
        stock: 1,
        imagen1: "hombre/70.webp",
        imagen2: "hombre/70.1.webp",
        talla: "L",
        tallaBase: "L",
        tipo: "T-Shirt",
        color: "Gris",
        marca: "Gym Shark",
        precioMayoreo: 440.00,
        mayoreo: true,
        posicionCarrusel: 0,
        coleccion: "",
        coleccionCatalogo: ""
    },
    {
        id: 71,
        nombre: "ARRIVAL CONTRAST T-SHIRT",
        categoria: "Hombre",
        precio: 550.00,
        stock: 1,
        imagen1: "hombre/71.webp",
        imagen2: "hombre/71.1.webp",
        talla: "L",
        tallaBase: "L",
        tipo: "T-Shirt",
        color: "Azul",
        marca: "Gym Shark",
        precioMayoreo: 440.00,
        mayoreo: true,
        posicionCarrusel: 0,
        coleccion: "",
        coleccionCatalogo: ""
    },
    {
        id: 72,
        nombre: "ARRIVAL CONTRAST T-SHIRT",
        categoria: "Hombre",
        precio: 550.00,
        stock: 1,
        imagen1: "hombre/72.webp",
        imagen2: "hombre/72.1.webp",
        talla: "L",
        tallaBase: "L",
        tipo: "T-Shirt",
        color: "Verde",
        marca: "Gym Shark",
        precioMayoreo: 440.00,
        mayoreo: true,
        posicionCarrusel: 0,
        coleccion: "",
        coleccionCatalogo: ""
    },
    {
        id: 74,
        nombre: "ARRIVAL CONTRAST T-SHIRT",
        categoria: "Hombre",
        precio: 550.00,
        stock: 1,
        imagen1: "hombre/74.webp",
        imagen2: "hombre/74.1.webp",
        talla: "S",
        tallaBase: "S",
        tipo: "T-Shirt",
        color: "Azul",
        marca: "Gym Shark",
        precioMayoreo: 440.00,
        mayoreo: true,
        posicionCarrusel: 0,
        coleccion: "",
        coleccionCatalogo: ""
    },
    {
        id: 75,
        nombre: "ARRIVAL CONTRAST T-SHIRT",
        categoria: "Hombre",
        precio: 550.00,
        stock: 1,
        imagen1: "hombre/75.webp",
        imagen2: "hombre/75.1.webp",
        talla: "S",
        tallaBase: "S",
        tipo: "T-Shirt",
        color: "Verde",
        marca: "Gym Shark",
        precioMayoreo: 440.00,
        mayoreo: true,
        posicionCarrusel: 0,
        coleccion: "",
        coleccionCatalogo: ""
    },
    {
        id: 76,
        nombre: "ARRIVAL CONTRAST T-SHIRT",
        categoria: "Hombre",
        precio: 550.00,
        stock: 1,
        imagen1: "hombre/76.webp",
        imagen2: "hombre/76.1.jpg",
        talla: "L",
        tallaBase: "L",
        tipo: "T-Shirt",
        color: "Gris",
        marca: "Gym Shark",
        precioMayoreo: 440.00,
        mayoreo: true,
        posicionCarrusel: 0,
        coleccion: "",
        coleccionCatalogo: ""
    },
    {
        id: 77,
        nombre: "ARRIVAL CONTRAST T-SHIRT",
        categoria: "Hombre",
        precio: 550.00,
        stock: 1,
        imagen1: "hombre/77.webp",
        imagen2: "hombre/77.1.webp",
        talla: "M",
        tallaBase: "M",
        tipo: "T-Shirt",
        color: "Azul",
        marca: "Gym Shark",
        precioMayoreo: 440.00,
        mayoreo: true,
        posicionCarrusel: 0,
        coleccion: "",
        coleccionCatalogo: ""
    },
    {
        id: 78,
        nombre: "ARRIVAL CONTRAST T-SHIRT",
        categoria: "Hombre",
        precio: 550.00,
        stock: 1,
        imagen1: "hombre/78.webp",
        imagen2: "hombre/78.1.jpg",
        talla: "S",
        tallaBase: "S",
        tipo: "T-Shirt",
        color: "Gris",
        marca: "Gym Shark",
        precioMayoreo: 440.00,
        mayoreo: true,
        posicionCarrusel: 0,
        coleccion: "",
        coleccionCatalogo: ""
    },
    {
        id: 80,
        nombre: "ARRIVAL TANK",
        categoria: "Hombre",
        precio: 500.00,
        stock: 1,
        imagen1: "hombre/80.webp",
        imagen2: "hombre/80.1.webp",
        talla: "L",
        tallaBase: "L",
        tipo: "Tank Top",
        color: "Verde",
        marca: "Gym Shark",
        precioMayoreo: 400.00,
        mayoreo: true,
        posicionCarrusel: 0,
        coleccion: "",
        coleccionCatalogo: ""
    },
    {
        id: 82,
        nombre: "BUILT FOR MORE T-SHIRT",
        categoria: "Hombre",
        precio: 550.00,
        stock: 1,
        imagen1: "hombre/82.webp",
        imagen2: "hombre/82.1.webp",
        talla: "L",
        tallaBase: "L",
        tipo: "T-Shirt",
        color: "Negro",
        marca: "Gym Shark",
        precioMayoreo: 440.00,
        mayoreo: true,
        posicionCarrusel: 0,
        coleccion: "",
        coleccionCatalogo: ""
    },
    {
        id: 83,
        nombre: "BUILT FOR MORE T-SHIRT",
        categoria: "Hombre",
        precio: 550.00,
        stock: 1,
        imagen1: "hombre/83.webp",
        imagen2: "hombre/83.1.webp",
        talla: "S",
        tallaBase: "S",
        tipo: "T-Shirt",
        color: "Blanco",
        marca: "Gym Shark",
        precioMayoreo: 440.00,
        mayoreo: true,
        posicionCarrusel: 0,
        coleccion: "",
        coleccionCatalogo: ""
    },
    {
        id: 84,
        nombre: "BUILT FOR MORE T-SHIRT",
        categoria: "Hombre",
        precio: 550.00,
        stock: 1,
        imagen1: "hombre/84.webp",
        imagen2: "hombre/84.1.webp",
        talla: "L",
        tallaBase: "L",
        tipo: "T-Shirt",
        color: "Blanco",
        marca: "Gym Shark",
        precioMayoreo: 440.00,
        mayoreo: true,
        posicionCarrusel: 0,
        coleccion: "",
        coleccionCatalogo: ""
    },
    {
        id: 85,
        nombre: "BUILT FOR MORE T-SHIRT",
        categoria: "Hombre",
        precio: 550.00,
        stock: 1,
        imagen1: "hombre/85.webp",
        imagen2: "hombre/85.1.webp",
        talla: "L",
        tallaBase: "L",
        tipo: "T-Shirt",
        color: "Gris",
        marca: "Gym Shark",
        precioMayoreo: 440.00,
        mayoreo: true,
        posicionCarrusel: 0,
        coleccion: "",
        coleccionCatalogo: ""
    },
    {
        id: 86,
        nombre: "BUILT FOR MORE T-SHIRT",
        categoria: "Hombre",
        precio: 550.00,
        stock: 1,
        imagen1: "hombre/86.webp",
        imagen2: "hombre/86.1.webp",
        talla: "M",
        tallaBase: "M",
        tipo: "T-Shirt",
        color: "Marrón",
        marca: "Gym Shark",
        precioMayoreo: 440.00,
        mayoreo: true,
        posicionCarrusel: 0,
        coleccion: "",
        coleccionCatalogo: ""
    },
    {
        id: 87,
        nombre: "BUILT FOR MORE T-SHIRT",
        categoria: "Hombre",
        precio: 550.00,
        stock: 1,
        imagen1: "hombre/87.webp",
        imagen2: "hombre/87.1.jpg",
        talla: "L",
        tallaBase: "L",
        tipo: "T-Shirt",
        color: "Marrón",
        marca: "Gym Shark",
        precioMayoreo: 440.00,
        mayoreo: true,
        posicionCarrusel: 0,
        coleccion: "",
        coleccionCatalogo: ""
    },
    {
        id: 88,
        nombre: "BUILT FOR MORE T-SHIRT",
        categoria: "Hombre",
        precio: 550.00,
        stock: 1,
        imagen1: "hombre/88.webp",
        imagen2: "hombre/88.1.webp",
        talla: "M",
        tallaBase: "M",
        tipo: "T-Shirt",
        color: "Blanco",
        marca: "Gym Shark",
        precioMayoreo: 440.00,
        mayoreo: true,
        posicionCarrusel: 0,
        coleccion: "",
        coleccionCatalogo: ""
    },
    {
        id: 89,
        nombre: "BUILT FOR MORE T-SHIRT",
        categoria: "Hombre",
        precio: 550.00,
        stock: 1,
        imagen1: "hombre/89.webp",
        imagen2: "hombre/89.1.webp",
        talla: "M",
        tallaBase: "M",
        tipo: "T-Shirt",
        color: "Gris",
        marca: "Gym Shark",
        precioMayoreo: 440.00,
        mayoreo: true,
        posicionCarrusel: 0,
        coleccion: "",
        coleccionCatalogo: ""
    },
    {
        id: 90,
        nombre: "BUILT FOR MORE T-SHIRT",
        categoria: "Hombre",
        precio: 550.00,
        stock: 1,
        imagen1: "hombre/90.webp",
        imagen2: "hombre/90.1.webp",
        talla: "S",
        tallaBase: "S",
        tipo: "T-Shirt",
        color: "Negro",
        marca: "Gym Shark",
        precioMayoreo: 440.00,
        mayoreo: true,
        posicionCarrusel: 0,
        coleccion: "",
        coleccionCatalogo: ""
    },
    {
        id: 91,
        nombre: "BUILT FOR MORE T-SHIRT",
        categoria: "Hombre",
        precio: 550.00,
        stock: 1,
        imagen1: "hombre/91.webp",
        imagen2: "hombre/91.1.webp",
        talla: "S",
        tallaBase: "S",
        tipo: "T-Shirt",
        color: "Marrón",
        marca: "Gym Shark",
        precioMayoreo: 440.00,
        mayoreo: true,
        posicionCarrusel: 0,
        coleccion: "",
        coleccionCatalogo: ""
    },
    {
        id: 92,
        nombre: "BUILT FOR MORE T-SHIRT",
        categoria: "Hombre",
        precio: 550.00,
        stock: 1,
        imagen1: "hombre/92.webp",
        imagen2: "hombre/92.1.webp",
        talla: "S",
        tallaBase: "S",
        tipo: "T-Shirt",
        color: "Gris",
        marca: "Gym Shark",
        precioMayoreo: 440.00,
        mayoreo: true,
        posicionCarrusel: 0,
        coleccion: "",
        coleccionCatalogo: ""
    },
    {
        id: 93,
        nombre: "CHAOS TEES",
        categoria: "Hombre",
        precio: 1050.00,
        stock: 1,
        imagen1: "hombre/93.webp",
        imagen2: "hombre/93.1.webp",
        talla: "L",
        tallaBase: "L",
        tipo: "T-Shirt",
        color: "Negro",
        marca: "YoungLA",
        precioMayoreo: 1020.00,
        mayoreo: false,
        posicionCarrusel: 0,
        coleccion: "",
        coleccionCatalogo: ""
    },
    {
        id: 95,
        nombre: "CREST OVERSIZED JOGGERS",
        categoria: "Hombre",
        precio: 750.00,
        stock: 1,
        imagen1: "hombre/95.webp",
        imagen2: "hombre/95.1.webp",
        talla: "M",
        tallaBase: "M",
        tipo: "Pants",
        color: "Marrón",
        marca: "Gym Shark",
        precioMayoreo: 600.00,
        mayoreo: true,
        posicionCarrusel: 0,
        coleccion: "",
        coleccionCatalogo: ""
    },
    {
        id: 97,
        nombre: "CREST OVERSIZED T-SHIRT",
        categoria: "Hombre",
        precio: 550.00,
        stock: 1,
        imagen1: "hombre/97.webp",
        imagen2: "hombre/97.1.webp",
        talla: "S",
        tallaBase: "S",
        tipo: "T-Shirt",
        color: "Azul",
        marca: "Gym Shark",
        precioMayoreo: 440.00,
        mayoreo: true,
        posicionCarrusel: 0,
        coleccion: "",
        coleccionCatalogo: ""
    },
    {
        id: 99,
        nombre: "CREST OVERSIZED T-SHIRT",
        categoria: "Hombre",
        precio: 550.00,
        stock: 1,
        imagen1: "hombre/99.webp",
        imagen2: "hombre/99.1.webp",
        talla: "L",
        tallaBase: "L",
        tipo: "T-Shirt",
        color: "Azul",
        marca: "Gym Shark",
        precioMayoreo: 440.00,
        mayoreo: true,
        posicionCarrusel: 0,
        coleccion: "",
        coleccionCatalogo: ""
    },
    {
        id: 102,
        nombre: "CREW SOCKS",
        categoria: "Hombre",
        precio: 500.00,
        stock: 1,
        imagen1: "hombre/102.webp",
        imagen2: "hombre/102.1.webp",
        talla: "S",
        tallaBase: "S",
        tipo: "Accesorios",
        color: "Negro",
        marca: "Gym Shark",
        precioMayoreo: 400.00,
        mayoreo: true,
        posicionCarrusel: 0,
        coleccion: "",
        coleccionCatalogo: ""
    },
    {
        id: 105,
        nombre: "DARK WAVE JOGGERS",
        categoria: "Hombre",
        precio: 1500.00,
        stock: 1,
        imagen1: "hombre/105.webp",
        imagen2: "hombre/105.1.webp",
        talla: "L",
        tallaBase: "L",
        tipo: "Pants",
        color: "Negro",
        marca: "YoungLA",
        precioMayoreo: 1490.00,
        mayoreo: false,
        posicionCarrusel: 0,
        coleccion: "",
        coleccionCatalogo: ""
    },
    {
        id: 106,
        nombre: "DARK WAVE WIFE LOVERS",
        categoria: "Hombre",
        precio: 750.00,
        stock: 1,
        imagen1: "hombre/106.webp",
        imagen2: "hombre/106.1.webp",
        talla: "XL",
        tallaBase: "XL",
        tipo: "Tank Top",
        color: "Negro",
        marca: "YoungLA",
        precioMayoreo: 600.00,
        mayoreo: true,
        posicionCarrusel: 0,
        coleccion: "",
        coleccionCatalogo: ""
    },
    {
        id: 107,
        nombre: "DISTRESSED SCRIPT TEES",
        categoria: "Hombre",
        precio: 1050.00,
        stock: 1,
        imagen1: "hombre/107.webp",
        imagen2: "hombre/107.1.webp",
        talla: "L",
        tallaBase: "L",
        tipo: "T-Shirt",
        color: "Negro",
        marca: "YoungLA",
        precioMayoreo: 1020.00,
        mayoreo: false,
        posicionCarrusel: 0,
        coleccion: "",
        coleccionCatalogo: ""
    },
    {
        id: 108,
        nombre: "DISTRESSED SCRIPT TEES",
        categoria: "Hombre",
        precio: 1050.00,
        stock: 1,
        imagen1: "hombre/108.webp",
        imagen2: "hombre/108.1.webp",
        talla: "L",
        tallaBase: "L",
        tipo: "T-Shirt",
        color: "Blanco",
        marca: "YoungLA",
        precioMayoreo: 1020.00,
        mayoreo: false,
        posicionCarrusel: 0,
        coleccion: "",
        coleccionCatalogo: ""
    },
    {
        id: 109,
        nombre: "DIVINE SWEATS",
        categoria: "Hombre",
        precio: 1600.00,
        stock: 1,
        imagen1: "hombre/109.webp",
        imagen2: "hombre/109.1.webp",
        talla: "L",
        tallaBase: "L",
        tipo: "Pants",
        color: "Negro",
        marca: "YoungLA",
        precioMayoreo: 1530.00,
        mayoreo: false,
        posicionCarrusel: 0,
        coleccion: "",
        coleccionCatalogo: ""
    },
    {
        id: 110,
        nombre: "DYNASTY SWEATS",
        categoria: "Hombre",
        precio: 1500.00,
        stock: 1,
        imagen1: "hombre/110.webp",
        imagen2: "hombre/110.1.jpg",
        talla: "L",
        tallaBase: "L",
        tipo: "Pants",
        color: "Negro",
        marca: "YoungLA",
        precioMayoreo: 1380.00,
        mayoreo: false,
        posicionCarrusel: 0,
        coleccion: "",
        coleccionCatalogo: ""
    },
    {
        id: 111,
        nombre: "ELEMENT BASELAYER T-SHIRT",
        categoria: "Hombre",
        precio: 800.00,
        stock: 1,
        imagen1: "hombre/111.webp",
        imagen2: "hombre/111.1.webp",
        talla: "M",
        tallaBase: "M",
        tipo: "T-Shirt",
        color: "Rojo",
        marca: "Gym Shark",
        precioMayoreo: 640.00,
        mayoreo: true,
        posicionCarrusel: 0,
        coleccion: "",
        coleccionCatalogo: ""
    },
    {
        id: 112,
        nombre: "FAITH SWEATS",
        categoria: "Hombre",
        precio: 1500.00,
        stock: 1,
        imagen1: "hombre/112.webp",
        imagen2: "hombre/112.1.webp",
        talla: "L",
        tallaBase: "L",
        tipo: "Pants",
        color: "Negro",
        marca: "YoungLA",
        precioMayoreo: 1380.00,
        mayoreo: false,
        posicionCarrusel: 0,
        coleccion: "",
        coleccionCatalogo: ""
    },
    {
        id: 116,
        nombre: "GYMSHARK X CBUM CAP",
        categoria: "Hombre",
        precio: 900.00,
        stock: 1,
        imagen1: "hombre/116.webp",
        imagen2: "hombre/116.1.webp",
        talla: "ONE SIZE",
        tallaBase: "ONE SIZE",
        tipo: "Accesorios",
        color: "Negro",
        marca: "Gym Shark",
        precioMayoreo: 900.00,
        mayoreo: false,
        posicionCarrusel: 0,
        coleccion: "CBUM",
        coleccionCatalogo: "CBUM"
    },
    {
        id: 121,
        nombre: "GYMSHARK X CBUM T-SHIRT",
        categoria: "Hombre",
        precio: 1200.00,
        stock: 1,
        imagen1: "hombre/121.webp",
        imagen2: "hombre/121.1.webp",
        talla: "L",
        tallaBase: "L",
        tipo: "T-Shirt",
        color: "Blanco",
        marca: "Gym Shark",
        precioMayoreo: 1190.00,
        mayoreo: false,
        posicionCarrusel: 0,
        coleccion: "CBUM",
        coleccionCatalogo: "CBUM"
    },
    {
        id: 123,
        nombre: "GYMSHARK X CBUM T-SHIRT",
        categoria: "Hombre",
        precio: 1200.00,
        stock: 1,
        imagen1: "hombre/123.webp",
        imagen2: "hombre/123.1.webp",
        talla: "M",
        tallaBase: "M",
        tipo: "T-Shirt",
        color: "Blanco",
        marca: "Gym Shark",
        precioMayoreo: 1190.00,
        mayoreo: false,
        posicionCarrusel: 0,
        coleccion: "CBUM",
        coleccionCatalogo: "CBUM"
    },
    {
        id: 124,
        nombre: "GYMSHARK X CBUM T-SHIRT",
        categoria: "Hombre",
        precio: 1200.00,
        stock: 1,
        imagen1: "hombre/124.webp",
        imagen2: "hombre/124.1.webp",
        talla: "S",
        tallaBase: "S",
        tipo: "T-Shirt",
        color: "Negro",
        marca: "Gym Shark",
        precioMayoreo: 1190.00,
        mayoreo: false,
        posicionCarrusel: 0,
        coleccion: "CBUM",
        coleccionCatalogo: "CBUM"
    },
    {
        id: 125,
        nombre: "GYMSHARK X CBUM WASHED HOODIE",
        categoria: "Hombre",
        precio: 2000.00,
        stock: 1,
        imagen1: "hombre/125.webp",
        imagen2: "hombre/125.1.webp",
        talla: "L",
        tallaBase: "L",
        tipo: "Hoodie",
        color: "Negro",
        marca: "Gym Shark",
        precioMayoreo: 1990.00,
        mayoreo: false,
        posicionCarrusel: 0,
        coleccion: "CBUM",
        coleccionCatalogo: "CBUM"
    },
    {
        id: 126,
        nombre: "GYMSHARK X CBUM WASHED HOODIE",
        categoria: "Hombre",
        precio: 2000.00,
        stock: 1,
        imagen1: "hombre/126.webp",
        imagen2: "hombre/126.1.webp",
        talla: "M",
        tallaBase: "M",
        tipo: "Hoodie",
        color: "Gris",
        marca: "Gym Shark",
        precioMayoreo: 1990.00,
        mayoreo: false,
        posicionCarrusel: 0,
        coleccion: "CBUM",
        coleccionCatalogo: "CBUM"
    },
    {
        id: 127,
        nombre: "GYMSHARK X CBUM WASHED HOODIE",
        categoria: "Hombre",
        precio: 2000.00,
        stock: 1,
        imagen1: "hombre/127.webp",
        imagen2: "hombre/127.1.webp",
        talla: "M",
        tallaBase: "M",
        tipo: "Hoodie",
        color: "Morado",
        marca: "Gym Shark",
        precioMayoreo: 1990.00,
        mayoreo: false,
        posicionCarrusel: 0,
        coleccion: "CBUM",
        coleccionCatalogo: "CBUM"
    },
    {
        id: 128,
        nombre: "LEGACY DROP ARM TANK",
        categoria: "Hombre",
        precio: 500.00,
        stock: 1,
        imagen1: "hombre/128.webp",
        imagen2: "hombre/128.1.webp",
        talla: "M",
        tallaBase: "M",
        tipo: "Tank Top",
        color: "Blanco",
        marca: "Gym Shark",
        precioMayoreo: 400.00,
        mayoreo: false,
        posicionCarrusel: 0,
        coleccion: "",
        coleccionCatalogo: ""
    },
    {
        id: 130,
        nombre: "NUMERALS HOODIE",
        categoria: "Hombre",
        precio: 900.00,
        stock: 1,
        imagen1: "hombre/130.webp",
        imagen2: "hombre/130.1.webp",
        talla: "M",
        tallaBase: "M",
        tipo: "Hoodie",
        color: "Negro",
        marca: "Gym Shark",
        precioMayoreo: 760.00,
        mayoreo: false,
        posicionCarrusel: 0,
        coleccion: "",
        coleccionCatalogo: ""
    },
    {
        id: 131,
        nombre: "NUMERALS HOODIE",
        categoria: "Hombre",
        precio: 800.00,
        stock: 1,
        imagen1: "hombre/131.webp",
        imagen2: "hombre/131.1.jpg",
        talla: "S",
        tallaBase: "S",
        tipo: "Hoodie",
        color: "Negro",
        marca: "Gym Shark",
        precioMayoreo: 760.00,
        mayoreo: false,
        posicionCarrusel: 0,
        coleccion: "",
        coleccionCatalogo: ""
    },
    {
        id: 132,
        nombre: "PANTS ELITE TALL 30",
        categoria: "Hombre",
        precio: 800.00,
        stock: 1,
        imagen1: "hombre/132.webp",
        imagen2: "hombre/132.1.webp",
        talla: "S",
        tallaBase: "S",
        tipo: "Pants",
        color: "Azul",
        marca: "Gym Shark",
        precioMayoreo: 760.00,
        mayoreo: false,
        posicionCarrusel: 0,
        coleccion: "",
        coleccionCatalogo: ""
    },
    {
        id: 133,
        nombre: "PANTS ELITE TALL 30",
        categoria: "Hombre",
        precio: 800.00,
        stock: 1,
        imagen1: "hombre/133.webp",
        imagen2: "hombre/133.1.webp",
        talla: "S",
        tallaBase: "S",
        tipo: "Pants",
        color: "Negro",
        marca: "Gym Shark",
        precioMayoreo: 760.00,
        mayoreo: false,
        posicionCarrusel: 0,
        coleccion: "",
        coleccionCatalogo: ""
    },
    {
        id: 134,
        nombre: "PANTS ELITE TALL 32",
        categoria: "Hombre",
        precio: 800.00,
        stock: 1,
        imagen1: "hombre/134.webp",
        imagen2: "hombre/134.1.webp",
        talla: "M",
        tallaBase: "M",
        tipo: "Pants",
        color: "Azul",
        marca: "Gym Shark",
        precioMayoreo: 760.00,
        mayoreo: false,
        posicionCarrusel: 0,
        coleccion: "",
        coleccionCatalogo: ""
    },
    {
        id: 135,
        nombre: "PANTS ELITE TALL 32",
        categoria: "Hombre",
        precio: 800.00,
        stock: 1,
        imagen1: "hombre/135.webp",
        imagen2: "hombre/135.1.webp",
        talla: "M",
        tallaBase: "M",
        tipo: "Pants",
        color: "Negro",
        marca: "Gym Shark",
        precioMayoreo: 760.00,
        mayoreo: false,
        posicionCarrusel: 0,
        coleccion: "",
        coleccionCatalogo: ""
    },
    {
        id: 136,
        nombre: "REVENGE CROP CUT-OFFS",
        categoria: "Hombre",
        precio: 900.00,
        stock: 1,
        imagen1: "hombre/136.webp",
        imagen2: "hombre/136.1.webp",
        talla: "L",
        tallaBase: "L",
        tipo: "Tank Top",
        color: "Gris",
        marca: "YoungLA",
        precioMayoreo: 890.00,
        mayoreo: false,
        posicionCarrusel: 0,
        coleccion: "",
        coleccionCatalogo: ""
    },
    {
        id: 137,
        nombre: "REVENGE TEES SPRING",
        categoria: "Hombre",
        precio: 1050.00,
        stock: 1,
        imagen1: "hombre/137.webp",
        imagen2: "",
        talla: "M",
        tallaBase: "M",
        tipo: "T-Shirt",
        color: "Gris",
        marca: "YoungLA",
        precioMayoreo: 1020.00,
        mayoreo: false,
        posicionCarrusel: 0,
        coleccion: "",
        coleccionCatalogo: ""
    },
    {
        id: 138,
        nombre: "RUNNING 4 2 IN 1 SHORTS",
        categoria: "Hombre",
        precio: 600.00,
        stock: 1,
        imagen1: "hombre/138.webp",
        imagen2: "hombre/138.1.webp",
        talla: "S",
        tallaBase: "S",
        tipo: "Short",
        color: "Marrón",
        marca: "Gym Shark",
        precioMayoreo: 660.00,
        mayoreo: false,
        posicionCarrusel: 0,
        coleccion: "",
        coleccionCatalogo: ""
    },
    {
        id: 139,
        nombre: "RUNNING 4 2 IN 1 SHORTS",
        categoria: "Hombre",
        precio: 700.00,
        stock: 1,
        imagen1: "hombre/139.webp",
        imagen2: "hombre/139.1.webp",
        talla: "M",
        tallaBase: "M",
        tipo: "Short",
        color: "Verde",
        marca: "Gym Shark",
        precioMayoreo: 660.00,
        mayoreo: false,
        posicionCarrusel: 0,
        coleccion: "",
        coleccionCatalogo: ""
    },
    {
        id: 142,
        nombre: "SPORT 7 2 IN 1 SHORTS",
        categoria: "Hombre",
        precio: 600.00,
        stock: 1,
        imagen1: "hombre/142.webp",
        imagen2: "hombre/142.1.webp",
        talla: "S",
        tallaBase: "S",
        tipo: "Short",
        color: "Azul",
        marca: "Gym Shark",
        precioMayoreo: 480.00,
        mayoreo: true,
        posicionCarrusel: 0,
        coleccion: "",
        coleccionCatalogo: ""
    },
    {
        id: 143,
        nombre: "STRAIGHT LEG PUMPER PANTS",
        categoria: "Hombre",
        precio: 1850.00,
        stock: 1,
        imagen1: "hombre/143.webp",
        imagen2: "hombre/143.1.webp",
        talla: "L",
        tallaBase: "L",
        tipo: "Pants",
        color: "Gris",
        marca: "Gym Shark",
        precioMayoreo: 1690.00,
        mayoreo: false,
        posicionCarrusel: 0,
        coleccion: "",
        coleccionCatalogo: ""
    },
    {
        id: 145,
        nombre: "ARRIVAL CONTRAST PANTS",
        categoria: "Hombre",
        precio: 750.00,
        stock: 1,
        imagen1: "hombre/145.webp",
        imagen2: "hombre/145.1.webp",
        talla: "L",
        tallaBase: "L",
        tipo: "Pants",
        color: "Negro",
        marca: "Gym Shark",
        precioMayoreo: 720.00,
        mayoreo: false,
        posicionCarrusel: 0,
        coleccion: "",
        coleccionCatalogo: ""
    },
    {
        id: 146,
        nombre: "ARRIVAL CONTRAST PANTS",
        categoria: "Hombre",
        precio: 750.00,
        stock: 1,
        imagen1: "hombre/146.webp",
        imagen2: "hombre/146.1.webp",
        talla: "S",
        tallaBase: "S",
        tipo: "Pants",
        color: "Negro",
        marca: "Gym Shark",
        precioMayoreo: 720.00,
        mayoreo: false,
        posicionCarrusel: 0,
        coleccion: "",
        coleccionCatalogo: ""
    },
    {
        id: 149,
        nombre: "ARRIVAL JOGGERS",
        categoria: "Hombre",
        precio: 750.00,
        stock: 1,
        imagen1: "hombre/149.webp",
        imagen2: "hombre/149.1.webp",
        talla: "S",
        tallaBase: "S",
        tipo: "Joggers",
        color: "Gris",
        marca: "Gym Shark",
        precioMayoreo: 600.00,
        mayoreo: true,
        posicionCarrusel: 0,
        coleccion: "",
        coleccionCatalogo: ""
    },
    {
        id: 150,
        nombre: "ARRIVAL JOGGERS",
        categoria: "Hombre",
        precio: 750.00,
        stock: 1,
        imagen1: "hombre/150.webp",
        imagen2: "hombre/150.1.webp",
        talla: "M",
        tallaBase: "M",
        tipo: "Joggers",
        color: "Gris",
        marca: "Gym Shark",
        precioMayoreo: 600.00,
        mayoreo: true,
        posicionCarrusel: 0,
        coleccion: "",
        coleccionCatalogo: ""
    },
    {
        id: 151,
        nombre: "ARRIVAL JOGGERS",
        categoria: "Hombre",
        precio: 750.00,
        stock: 1,
        imagen1: "hombre/151.jpg",
        imagen2: "hombre/151.1.webp",
        talla: "L",
        tallaBase: "L",
        tipo: "Joggers",
        color: "Gris",
        marca: "Gym Shark",
        precioMayoreo: 600.00,
        mayoreo: true,
        posicionCarrusel: 0,
        coleccion: "",
        coleccionCatalogo: ""
    },
    {
        id: 152,
        nombre: "COLLEGIATE TECH HOODIE",
        categoria: "Hombre",
        precio: 750.00,
        stock: 1,
        imagen1: "hombre/152.webp",
        imagen2: "hombre/152.1.webp",
        talla: "S",
        tallaBase: "S",
        tipo: "Hoodie",
        color: "Rojo",
        marca: "Gym Shark",
        precioMayoreo: 690.00,
        mayoreo: false,
        posicionCarrusel: 8,
        coleccion: "",
        coleccionCatalogo: ""
    },
    {
        id: 153,
        nombre: "COLLEGIATE TECH HOODIE",
        categoria: "Hombre",
        precio: 750.00,
        stock: 1,
        imagen1: "hombre/153.webp",
        imagen2: "hombre/153.1.webp",
        talla: "M",
        tallaBase: "M",
        tipo: "Hoodie",
        color: "Rojo",
        marca: "Gym Shark",
        precioMayoreo: 690.00,
        mayoreo: false,
        posicionCarrusel: 0,
        coleccion: "",
        coleccionCatalogo: ""
    },
    {
        id: 154,
        nombre: "COLLEGIATE TECH HOODIE",
        categoria: "Hombre",
        precio: 750.00,
        stock: 1,
        imagen1: "hombre/154.webp",
        imagen2: "hombre/154.1.webp",
        talla: "L",
        tallaBase: "L",
        tipo: "Hoodie",
        color: "Rojo",
        marca: "Gym Shark",
        precioMayoreo: 690.00,
        mayoreo: false,
        posicionCarrusel: 0,
        coleccion: "",
        coleccionCatalogo: ""
    },
    {
        id: 157,
        nombre: "WEEKEND ZIP THROUGH SHELL JACKET",
        categoria: "Hombre",
        precio: 750.00,
        stock: 1,
        imagen1: "hombre/157.webp",
        imagen2: "hombre/157.1.webp",
        talla: "L",
        tallaBase: "L",
        tipo: "Jacket",
        color: "Gris",
        marca: "Gym Shark",
        precioMayoreo: 580.00,
        mayoreo: false,
        posicionCarrusel: 0,
        coleccion: "",
        coleccionCatalogo: ""
    },
    {
        id: 160,
        nombre: "ACTIVE BACKPACK",
        categoria: "Hombre",
        precio: 600.00,
        stock: 1,
        imagen1: "hombre/160.webp",
        imagen2: "hombre/160.1.webp",
        talla: "ONE SIZE",
        tallaBase: "ONE SIZE",
        tipo: "Accesorios",
        color: "Verde",
        marca: "Gym Shark",
        precioMayoreo: 480.00,
        mayoreo: true,
        posicionCarrusel: 0,
        coleccion: "",
        coleccionCatalogo: ""
    },
    {
        id: 162,
        nombre: "ARRIVAL T-SHIRT",
        categoria: "Hombre",
        precio: 550.00,
        stock: 1,
        imagen1: "hombre/162.webp",
        imagen2: "hombre/162.1.webp",
        talla: "L",
        tallaBase: "L",
        tipo: "T-Shirt",
        color: "Rosa",
        marca: "Gym Shark",
        precioMayoreo: 450.00,
        mayoreo: false,
        posicionCarrusel: 0,
        coleccion: "",
        coleccionCatalogo: ""
    },
    {
        id: 165,
        nombre: "ARRIVAL T-SHIRT",
        categoria: "Hombre",
        precio: 550.00,
        stock: 1,
        imagen1: "hombre/165.webp",
        imagen2: "hombre/165.1.webp",
        talla: "M",
        tallaBase: "M",
        tipo: "T-Shirt",
        color: "Azul",
        marca: "Gym Shark",
        precioMayoreo: 450.00,
        mayoreo: false,
        posicionCarrusel: 0,
        coleccion: "",
        coleccionCatalogo: ""
    },
    {
        id: 166,
        nombre: "ARRIVAL T-SHIRT",
        categoria: "Hombre",
        precio: 550.00,
        stock: 1,
        imagen1: "hombre/166.webp",
        imagen2: "hombre/166.1.webp",
        talla: "S",
        tallaBase: "S",
        tipo: "T-Shirt",
        color: "Rosa",
        marca: "Gym Shark",
        precioMayoreo: 450.00,
        mayoreo: false,
        posicionCarrusel: 0,
        coleccion: "",
        coleccionCatalogo: ""
    },
    {
        id: 167,
        nombre: "ARRIVAL T-SHIRT",
        categoria: "Hombre",
        precio: 550.00,
        stock: 1,
        imagen1: "hombre/167.webp",
        imagen2: "hombre/167.1.webp",
        talla: "S",
        tallaBase: "S",
        tipo: "T-Shirt",
        color: "Azul",
        marca: "Gym Shark",
        precioMayoreo: 450.00,
        mayoreo: false,
        posicionCarrusel: 0,
        coleccion: "",
        coleccionCatalogo: ""
    },
    {
        id: 168,
        nombre: "GLOBAL LIFTING OVERSIZED ESSENTIAL JOGGERS",
        categoria: "Hombre",
        precio: 750.00,
        stock: 1,
        imagen1: "hombre/168.webp",
        imagen2: "hombre/168.1.webp",
        talla: "L",
        tallaBase: "L",
        tipo: "Joggers",
        color: "Negro",
        marca: "Gym Shark",
        precioMayoreo: 600.00,
        mayoreo: true,
        posicionCarrusel: 0,
        coleccion: "",
        coleccionCatalogo: ""
    },
    {
        id: 171,
        nombre: "CRITICAL TANK",
        categoria: "Hombre",
        precio: 500.00,
        stock: 1,
        imagen1: "hombre/171.webp",
        imagen2: "hombre/171.1.webp",
        talla: "M",
        tallaBase: "M",
        tipo: "Tank Top",
        color: "Blanco",
        marca: "Gym Shark",
        precioMayoreo: 420.00,
        mayoreo: false,
        posicionCarrusel: 0,
        coleccion: "",
        coleccionCatalogo: ""
    },
    {
        id: 172,
        nombre: "CRITICAL 2.0 DROP ARM TANK",
        categoria: "Hombre",
        precio: 500.00,
        stock: 1,
        imagen1: "hombre/172.webp",
        imagen2: "hombre/172.1.webp",
        talla: "M",
        tallaBase: "M",
        tipo: "Tank Top",
        color: "Blanco",
        marca: "Gym Shark",
        precioMayoreo: 420.00,
        mayoreo: false,
        posicionCarrusel: 0,
        coleccion: "",
        coleccionCatalogo: ""
    },
    {
        id: 175,
        nombre: "RIBBED T-SHIRT",
        categoria: "Hombre",
        precio: 550.00,
        stock: 1,
        imagen1: "hombre/175.webp",
        imagen2: "hombre/175.1.webp",
        talla: "XL",
        tallaBase: "XL",
        tipo: "T-Shirt",
        color: "Blanco",
        marca: "Gym Shark",
        precioMayoreo: 420.00,
        mayoreo: false,
        posicionCarrusel: 0,
        coleccion: "",
        coleccionCatalogo: ""
    },
    {
        id: 176,
        nombre: "RIBBED T-SHIRT",
        categoria: "Hombre",
        precio: 550.00,
        stock: 1,
        imagen1: "hombre/176.webp",
        imagen2: "hombre/176.1.webp",
        talla: "L",
        tallaBase: "L",
        tipo: "T-Shirt",
        color: "Blanco",
        marca: "Gym Shark",
        precioMayoreo: 420.00,
        mayoreo: false,
        posicionCarrusel: 0,
        coleccion: "",
        coleccionCatalogo: ""
    },
    {
        id: 177,
        nombre: "BUILT FOR MORE T-SHIRT",
        categoria: "Hombre",
        precio: 550.00,
        stock: 1,
        imagen1: "hombre/177.webp",
        imagen2: "hombre/177.1.webp",
        talla: "S",
        tallaBase: "S",
        tipo: "T-Shirt",
        color: "Negro",
        marca: "Gym Shark",
        precioMayoreo: 420.00,
        mayoreo: false,
        posicionCarrusel: 0,
        coleccion: "",
        coleccionCatalogo: ""
    },
    {
        id: 178,
        nombre: "BUILT FOR MORE T-SHIRT",
        categoria: "Hombre",
        precio: 550.00,
        stock: 1,
        imagen1: "hombre/178.webp",
        imagen2: "hombre/178.1.webp",
        talla: "L",
        tallaBase: "L",
        tipo: "T-Shirt",
        color: "Negro",
        marca: "Gym Shark",
        precioMayoreo: 420.00,
        mayoreo: false,
        posicionCarrusel: 0,
        coleccion: "",
        coleccionCatalogo: ""
    },
    {
        id: 180,
        nombre: "CREST OVERSIZED T-SHIRT",
        categoria: "Hombre",
        precio: 550.00,
        stock: 1,
        imagen1: "hombre/180.webp",
        imagen2: "hombre/180.1.webp",
        talla: "L",
        tallaBase: "L",
        tipo: "T-Shirt",
        color: "Azul",
        marca: "Gym Shark",
        precioMayoreo: 440.00,
        mayoreo: true,
        posicionCarrusel: 0,
        coleccion: "",
        coleccionCatalogo: ""
    },
    {
        id: 187,
        nombre: "RIBBED TANK 1PK",
        categoria: "Hombre",
        precio: 500.00,
        stock: 1,
        imagen1: "hombre/187.webp",
        imagen2: "hombre/187.1.webp",
        talla: "S",
        tallaBase: "S",
        tipo: "Tank Top",
        color: "Negro",
        marca: "Gym Shark",
        precioMayoreo: 380.00,
        mayoreo: false,
        posicionCarrusel: 0,
        coleccion: "",
        coleccionCatalogo: ""
    },
    {
        id: 189,
        nombre: "CREST OVERSIZED T-SHIRT",
        categoria: "Hombre",
        precio: 550.00,
        stock: 1,
        imagen1: "hombre/189.webp",
        imagen2: "hombre/189.1.webp",
        talla: "M",
        tallaBase: "M",
        tipo: "T-Shirt",
        color: "Azul",
        marca: "Gym Shark",
        precioMayoreo: 440.00,
        mayoreo: true,
        posicionCarrusel: 0,
        coleccion: "",
        coleccionCatalogo: ""
    },
    {
        id: 190,
        nombre: "HYBRID 6\" SHORTS",
        categoria: "Hombre",
        precio: 550.00,
        stock: 1,
        imagen1: "hombre/190.webp",
        imagen2: "hombre/190.1.webp",
        talla: "M",
        tallaBase: "M",
        tipo: "Short",
        color: "Morado",
        marca: "Gym Shark",
        precioMayoreo: 440.00,
        mayoreo: true,
        posicionCarrusel: 0,
        coleccion: "",
        coleccionCatalogo: ""
    },
    {
        id: 191,
        nombre: "14OZ SHAKER BOTTLE",
        categoria: "Hombre",
        precio: 400.00,
        stock: 1,
        imagen1: "hombre/191.webp",
        imagen2: "hombre/191.1.webp",
        talla: "ONE SIZE",
        tallaBase: "ONE SIZE",
        tipo: "Accesorios",
        color: "Negro",
        marca: "Gym Shark",
        precioMayoreo: 320.00,
        mayoreo: true,
        posicionCarrusel: 0,
        coleccion: "",
        coleccionCatalogo: ""
    },
    {
        id: 192,
        nombre: "BASELAYER LEGGING",
        categoria: "Hombre",
        precio: 750.00,
        stock: 1,
        imagen1: "hombre/192.webp",
        imagen2: "hombre/192.1.webp",
        talla: "M",
        tallaBase: "M",
        tipo: "Leggings",
        color: "Negro",
        marca: "Gym Shark",
        precioMayoreo: 580.00,
        mayoreo: false,
        posicionCarrusel: 0,
        coleccion: "",
        coleccionCatalogo: ""
    },
    {
        id: 193,
        nombre: "CARLOS BELCAST TRACK JACKET",
        categoria: "Hombre",
        precio: 1200.00,
        stock: 1,
        imagen1: "hombre/193.webp",
        imagen2: "hombre/193.1.webp",
        talla: "L",
        tallaBase: "L",
        tipo: "Jacket",
        color: "Gris",
        marca: "Gym Shark",
        precioMayoreo: 1180.00,
        mayoreo: false,
        posicionCarrusel: 6,
        coleccion: "BELCAST",
        coleccionCatalogo: "BELCAST"
    },
    {
        id: 196,
        nombre: "CARLOS BELCAST TRACK PANT",
        categoria: "Hombre",
        precio: 1250.00,
        stock: 1,
        imagen1: "hombre/196.webp",
        imagen2: "hombre/196.1.webp",
        talla: "L",
        tallaBase: "L",
        tipo: "Pants",
        color: "Gris",
        marca: "Gym Shark",
        precioMayoreo: 1250.00,
        mayoreo: false,
        posicionCarrusel: 0,
        coleccion: "BELCAST",
        coleccionCatalogo: "BELCAST"
    },
    {
        id: 198,
        nombre: "COLLEGIATE TECH TANK",
        categoria: "Hombre",
        precio: 750.00,
        stock: 1,
        imagen1: "hombre/198.webp",
        imagen2: "hombre/198.1.webp",
        talla: "L",
        tallaBase: "L",
        tipo: "Tank Top",
        color: "Azul",
        marca: "Gym Shark",
        precioMayoreo: 730.00,
        mayoreo: false,
        posicionCarrusel: 0,
        coleccion: "",
        coleccionCatalogo: ""
    },
    {
        id: 202,
        nombre: "SHADOW SEAMLESS T SHIRT",
        categoria: "Hombre",
        precio: 750.00,
        stock: 1,
        imagen1: "hombre/202.webp",
        imagen2: "hombre/202.1.webp",
        talla: "L",
        tallaBase: "L",
        tipo: "T-Shirt",
        color: "Negro",
        marca: "Gym Shark",
        precioMayoreo: 720.00,
        mayoreo: false,
        posicionCarrusel: 0,
        coleccion: "",
        coleccionCatalogo: ""
    },
    {
        id: 203,
        nombre: "GEO SEAMLESS T-SHIRT",
        categoria: "Hombre",
        precio: 500.00,
        stock: 1,
        imagen1: "hombre/203.webp",
        imagen2: "hombre/203.1.webp",
        talla: "L",
        tallaBase: "L",
        tipo: "T-Shirt",
        color: "Verde",
        marca: "Gym Shark",
        precioMayoreo: 500.00,
        mayoreo: false,
        posicionCarrusel: 0,
        coleccion: "",
        coleccionCatalogo: ""
    },
    {
        id: 204,
        nombre: "RIBBED TANK 1PK",
        categoria: "Hombre",
        precio: 500.00,
        stock: 1,
        imagen1: "hombre/204.webp",
        imagen2: "hombre/204.1.webp",
        talla: "XL",
        tallaBase: "XL",
        tipo: "Tank Top",
        color: "Negro",
        marca: "Gym Shark",
        precioMayoreo: 380.00,
        mayoreo: false,
        posicionCarrusel: 0,
        coleccion: "",
        coleccionCatalogo: ""
    },
    {
        id: 206,
        nombre: "SHADOW SEAMLESS LONG SLEEVE T-SHIRT",
        categoria: "Hombre",
        precio: 800.00,
        stock: 1,
        imagen1: "hombre/206.webp",
        imagen2: "hombre/206.1.webp",
        talla: "XL",
        tallaBase: "XL",
        tipo: "Long Sleeve",
        color: "Negro",
        marca: "Gym Shark",
        precioMayoreo: 780.00,
        mayoreo: false,
        posicionCarrusel: 0,
        coleccion: "",
        coleccionCatalogo: ""
    },
    {
        id: 214,
        nombre: "ARRIVAL CONTRAST PANTS",
        categoria: "Hombre",
        precio: 750.00,
        stock: 1,
        imagen1: "hombre/214.webp",
        imagen2: "hombre/214.1.webp",
        talla: "M",
        tallaBase: "M",
        tipo: "Pants",
        color: "Negro",
        marca: "Gym Shark",
        precioMayoreo: 720.00,
        mayoreo: false,
        posicionCarrusel: 0,
        coleccion: "",
        coleccionCatalogo: ""
    },
    {
        id: 215,
        nombre: "ARRIVAL CONTRAST PANTS",
        categoria: "Hombre",
        precio: 750.00,
        stock: 1,
        imagen1: "hombre/215.webp",
        imagen2: "hombre/215.1.webp",
        talla: "M",
        tallaBase: "M",
        tipo: "Pants",
        color: "Gris",
        marca: "Gym Shark",
        precioMayoreo: 600.00,
        mayoreo: false,
        posicionCarrusel: 0,
        coleccion: "",
        coleccionCatalogo: ""
    },
    {
        id: 218,
        nombre: "CREST TALL JOGGERS",
        categoria: "Hombre",
        precio: 750.00,
        stock: 1,
        imagen1: "hombre/218.webp",
        imagen2: "hombre/218.1.webp",
        talla: "M",
        tallaBase: "M",
        tipo: "Pants",
        color: "Negro",
        marca: "Gym Shark",
        precioMayoreo: 600.00,
        mayoreo: true,
        posicionCarrusel: 0,
        coleccion: "",
        coleccionCatalogo: ""
    },
    {
        id: 222,
        nombre: "ARRIVAL CONTRAST T-SHIRT",
        categoria: "Hombre",
        precio: 550.00,
        stock: 1,
        imagen1: "hombre/222.webp",
        imagen2: "hombre/222.1.webp",
        talla: "M",
        tallaBase: "M",
        tipo: "T-Shirt",
        color: "Negro",
        marca: "Gym Shark",
        precioMayoreo: 480.00,
        mayoreo: false,
        posicionCarrusel: 0,
        coleccion: "",
        coleccionCatalogo: ""
    },
    {
        id: 224,
        nombre: "ARRIVAL CONTRAST T-SHIRT",
        categoria: "Hombre",
        precio: 550.00,
        stock: 1,
        imagen1: "hombre/224.webp",
        imagen2: "hombre/224.1.webp",
        talla: "L",
        tallaBase: "L",
        tipo: "T-Shirt",
        color: "Gris",
        marca: "Gym Shark",
        precioMayoreo: 420.00,
        mayoreo: false,
        posicionCarrusel: 0,
        coleccion: "",
        coleccionCatalogo: ""
    },
    {
        id: 225,
        nombre: "ARRIVAL CONTRAST T-SHIRT",
        categoria: "Hombre",
        precio: 550.00,
        stock: 1,
        imagen1: "hombre/225.webp",
        imagen2: "hombre/225.1.webp",
        talla: "S",
        tallaBase: "S",
        tipo: "T-Shirt",
        color: "Gris",
        marca: "Gym Shark",
        precioMayoreo: 420.00,
        mayoreo: false,
        posicionCarrusel: 0,
        coleccion: "",
        coleccionCatalogo: ""
    },
    {
        id: 226,
        nombre: "CREST JOGGERS",
        categoria: "Hombre",
        precio: 750.00,
        stock: 1,
        imagen1: "hombre/226.webp",
        imagen2: "hombre/226.1.webp",
        talla: "M",
        tallaBase: "M",
        tipo: "Joggers",
        color: "Azul",
        marca: "Gym Shark",
        precioMayoreo: 600.00,
        mayoreo: true,
        posicionCarrusel: 0,
        coleccion: "",
        coleccionCatalogo: ""
    },
    {
        id: 227,
        nombre: "CREST TALL JOGGERS",
        categoria: "Hombre",
        precio: 750.00,
        stock: 1,
        imagen1: "hombre/227.webp",
        imagen2: "hombre/227.1.webp",
        talla: "M",
        tallaBase: "M",
        tipo: "Joggers",
        color: "Gris",
        marca: "Gym Shark",
        precioMayoreo: 630.00,
        mayoreo: false,
        posicionCarrusel: 0,
        coleccion: "",
        coleccionCatalogo: ""
    },
    {
        id: 228,
        nombre: "2012 STRENGTH JOGGERS",
        categoria: "Hombre",
        precio: 750.00,
        stock: 1,
        imagen1: "hombre/228.webp",
        imagen2: "hombre/228.1.webp",
        talla: "M",
        tallaBase: "M",
        tipo: "Joggers",
        color: "Gris",
        marca: "Gym Shark",
        precioMayoreo: 680.00,
        mayoreo: false,
        posicionCarrusel: 0,
        coleccion: "",
        coleccionCatalogo: ""
    },
    {
        id: 229,
        nombre: "COLLEGIATE MINI TOTE BAG",
        categoria: "Hombre",
        precio: 400.00,
        stock: 1,
        imagen1: "hombre/229.webp",
        imagen2: "hombre/229.1.webp",
        talla: "ONE SIZE",
        tallaBase: "ONE SIZE",
        tipo: "Accesorios",
        color: "Azul",
        marca: "Gym Shark",
        precioMayoreo: 320.00,
        mayoreo: true,
        posicionCarrusel: 0,
        coleccion: "",
        coleccionCatalogo: ""
    },
    {
        id: 231,
        nombre: "REST DAY ESSENTIALS CARGO JOGGERS",
        categoria: "Hombre",
        precio: 750.00,
        stock: 1,
        imagen1: "hombre/231.webp",
        imagen2: "hombre/231.1.webp",
        talla: "S",
        tallaBase: "S",
        tipo: "Joggers",
        color: "Gris",
        marca: "Gym Shark",
        precioMayoreo: 600.00,
        mayoreo: true,
        posicionCarrusel: 0,
        coleccion: "",
        coleccionCatalogo: ""
    },
    {
        id: 232,
        nombre: "LEGACY SHADOW TEES 4285",
        categoria: "Hombre",
        precio: 1100.00,
        stock: 1,
        imagen1: "hombre/232.webp",
        imagen2: "",
        talla: "S",
        tallaBase: "S",
        tipo: "T-Shirt",
        color: "Azul",
        marca: "YoungLA",
        precioMayoreo: 0.00,
        mayoreo: false,
        posicionCarrusel: 0,
        coleccion: "GOLDS GYM",
        coleccionCatalogo: "GOLDS GYM"
    },
    {
        id: 233,
        nombre: "LEGACY SHADOW CUT OFFS 5097",
        categoria: "Hombre",
        precio: 1200.00,
        stock: 1,
        imagen1: "hombre/233.webp",
        imagen2: "hombre/233.1.webp",
        talla: "M",
        tallaBase: "M",
        tipo: "Tank Top",
        color: "Marrón",
        marca: "YoungLA",
        precioMayoreo: 0.00,
        mayoreo: false,
        posicionCarrusel: 0,
        coleccion: "GOLDS GYM",
        coleccionCatalogo: "GOLDS GYM"
    },
    {
        id: 234,
        nombre: "LEGACY COMPRESSION TEES 4286",
        categoria: "Hombre",
        precio: 1200.00,
        stock: 1,
        imagen1: "hombre/234.webp",
        imagen2: "",
        talla: "L",
        tallaBase: "L",
        tipo: "Compression Shirt",
        color: "Negro",
        marca: "YoungLA",
        precioMayoreo: 0.00,
        mayoreo: false,
        posicionCarrusel: 0,
        coleccion: "GOLDS GYM",
        coleccionCatalogo: "GOLDS GYM"
    },
    {
        id: 235,
        nombre: "THROWBACK BAGGY JOGGERS 2154",
        categoria: "Hombre",
        precio: 1600.00,
        stock: 1,
        imagen1: "hombre/235.webp",
        imagen2: "",
        talla: "M",
        tallaBase: "M",
        tipo: "Joggers",
        color: "Azul",
        marca: "YoungLA",
        precioMayoreo: 0.00,
        mayoreo: false,
        posicionCarrusel: 0,
        coleccion: "",
        coleccionCatalogo: ""
    },
    {
        id: 236,
        nombre: "DEVANT SEAMLESS TANK",
        categoria: "Hombre",
        precio: 999.00,
        stock: 2,
        imagen1: "hombre/236.webp",
        imagen2: "hombre/236.1.webp",
        talla: "M",
        tallaBase: "M",
        tipo: "Tank Top",
        color: "Verde",
        marca: "Gym Shark",
        precioMayoreo: 0.00,
        mayoreo: false,
        posicionCarrusel: 4,
        coleccion: "DEVANT",
        coleccionCatalogo: "DEVANT"
    },
    {
        id: 237,
        nombre: "DEVANT SEMALESS TANK",
        categoria: "Hombre",
        precio: 999.00,
        stock: 1,
        imagen1: "hombre/237.webp",
        imagen2: "hombre/237.1.jpg",
        talla: "L",
        tallaBase: "L",
        tipo: "Tank Top",
        color: "Verde",
        marca: "Gym Shark",
        precioMayoreo: 0.00,
        mayoreo: false,
        posicionCarrusel: 0,
        coleccion: "DEVANT",
        coleccionCatalogo: "DEVANT"
    },
    {
        id: 239,
        nombre: "DEVANT SEAMLESS LONG SLEEVE T-SHIRT",
        categoria: "Hombre",
        precio: 1299.00,
        stock: 2,
        imagen1: "hombre/239.jpg",
        imagen2: "hombre/239.1.jpg",
        talla: "L",
        tallaBase: "L",
        tipo: "Long Sleeve",
        color: "Azul",
        marca: "Gym Shark",
        precioMayoreo: 0.00,
        mayoreo: false,
        posicionCarrusel: 2,
        coleccion: "DEVANT",
        coleccionCatalogo: "DEVANT"
    },
    {
        id: 241,
        nombre: "DEVANT SEAMLESS T-SHIRT",
        categoria: "Hombre",
        precio: 1199.00,
        stock: 1,
        imagen1: "hombre/241.webp",
        imagen2: "hombre/241.1.webp",
        talla: "XL",
        tallaBase: "XL",
        tipo: "T-Shirt",
        color: "Azul",
        marca: "Gym Shark",
        precioMayoreo: 0.00,
        mayoreo: false,
        posicionCarrusel: 0,
        coleccion: "DEVANT",
        coleccionCatalogo: "DEVANT"
    },
    {
        id: 243,
        nombre: "DEVANT SEAMLESS T-SHIRT",
        categoria: "Hombre",
        precio: 1199.00,
        stock: 1,
        imagen1: "hombre/243.jpg",
        imagen2: "hombre/243.1.jpg",
        talla: "L",
        tallaBase: "L",
        tipo: "T-Shirt",
        color: "Negro",
        marca: "Gym Shark",
        precioMayoreo: 0.00,
        mayoreo: false,
        posicionCarrusel: 0,
        coleccion: "DEVANT",
        coleccionCatalogo: "DEVANT"
    },
    {
        id: 245,
        nombre: "DEVANT SEAMLESS T-SHIRT",
        categoria: "Hombre",
        precio: 1199.00,
        stock: 1,
        imagen1: "hombre/245.webp",
        imagen2: "hombre/245.1.webp",
        talla: "L",
        tallaBase: "L",
        tipo: "T-Shirt",
        color: "Morado",
        marca: "Gym Shark",
        precioMayoreo: 0.00,
        mayoreo: false,
        posicionCarrusel: 1,
        coleccion: "DEVANT",
        coleccionCatalogo: "DEVANT"
    },
    {
        id: 262,
        nombre: "DEVANT SEMALESS TANK",
        categoria: "Hombre",
        precio: 999.00,
        stock: 1,
        imagen1: "hombre/262.webp",
        imagen2: "hombre/262.1.webp",
        talla: "M",
        tallaBase: "M",
        tipo: "Tank Top",
        color: "Negro",
        marca: "Gym Shark",
        precioMayoreo: 0.00,
        mayoreo: false,
        posicionCarrusel: 0,
        coleccion: "DEVANT",
        coleccionCatalogo: "DEVANT"
    },
    {
        id: 263,
        nombre: "DEVANT SEMALESS TANK",
        categoria: "Hombre",
        precio: 999.00,
        stock: 1,
        imagen1: "hombre/263.webp",
        imagen2: "hombre/263.1.webp",
        talla: "M",
        tallaBase: "M",
        tipo: "Tank Top",
        color: "Azul",
        marca: "Gym Shark",
        precioMayoreo: 0.00,
        mayoreo: false,
        posicionCarrusel: 0,
        coleccion: "DEVANT",
        coleccionCatalogo: "DEVANT"
    },
    {
        id: 264,
        nombre: "DEVANT SEMALESS TANK",
        categoria: "Hombre",
        precio: 999.00,
        stock: 1,
        imagen1: "hombre/264.webp",
        imagen2: "hombre/264.1.jpg",
        talla: "L",
        tallaBase: "L",
        tipo: "Tank Top",
        color: "Azul",
        marca: "Gym Shark",
        precioMayoreo: 0.00,
        mayoreo: false,
        posicionCarrusel: 0,
        coleccion: "DEVANT",
        coleccionCatalogo: "DEVANT"
    },
    {
        id: 265,
        nombre: "DEVANT SEMALESS TANK",
        categoria: "Hombre",
        precio: 999.00,
        stock: 1,
        imagen1: "hombre/265.webp",
        imagen2: "hombre/265.1.jpg",
        talla: "L",
        tallaBase: "L",
        tipo: "Tank Top",
        color: "Negro",
        marca: "Gym Shark",
        precioMayoreo: 0.00,
        mayoreo: false,
        posicionCarrusel: 0,
        coleccion: "DEVANT",
        coleccionCatalogo: "DEVANT"
    },
    {
        id: 266,
        nombre: "DEVANT SEAMLESS LONG SLEEVE T-SHIRT",
        categoria: "Hombre",
        precio: 1299.00,
        stock: 1,
        imagen1: "hombre/266.webp",
        imagen2: "hombre/266.1.jpg",
        talla: "L",
        tallaBase: "L",
        tipo: "Long Sleeve",
        color: "Negro",
        marca: "Gym Shark",
        precioMayoreo: 0.00,
        mayoreo: false,
        posicionCarrusel: 0,
        coleccion: "DEVANT",
        coleccionCatalogo: "DEVANT"
    },
    {
        id: 275,
        nombre: "Devant Seamless T-Shirt",
        categoria: "Hombre",
        precio: 1199.00,
        stock: 2,
        imagen1: "hombre/275.jpg",
        imagen2: "hombre/275.1.jpg",
        talla: "S",
        tallaBase: "S",
        tipo: "T-Shirt",
        color: "Negro",
        marca: "Gym Shark",
        precioMayoreo: 0.00,
        mayoreo: false,
        posicionCarrusel: 0,
        coleccion: "DEVANT",
        coleccionCatalogo: "DEVANT"
    }
];
