// =============================================================================
// STOCK HOMBRE — Única fuente del catálogo masculino en la web.
// Edita SOLO este archivo y sube cambios a GitHub; productos.js y script.js leen
// el array global productosHombre (expuesto como `productos` desde script.js).
// =============================================================================
const productosHombre = [
    {
        id: 1,
        nombre: "Retro Polo Shirt",
        categoria: "Hombre",
        precio: 650.00,
        stock: 1,
        imagen1: "hombre/1.png",
        imagen2: "hombre/1.1.png",
        talla: "M - Oversized Fit",
        tallaBase: "M",
        tipo: "Polo",
        color: "Blanco",
        marca: "Gym Shark"
    },
    {
        id: 2,
        nombre: "Varsity Hoodie",
        categoria: "Hombre",
        precio: 900.00,
        stock: 1,
        imagen1: "hombre/2.png",
        imagen2: "",
        talla: "L - Oversized Fit",
        tallaBase: "L",
        tipo: "Hoodie",
        color: "Negro",
        marca: "Gym Shark"
    },
    {
        id: 3,
        nombre: "Strenght Pants",
        categoria: "Hombre",
        precio: 850.00,
        stock: 1,
        imagen1: "hombre/3.png",
        imagen2: "hombre/3.1.png",
        talla: "L - Oversized",
        tallaBase: "L",
        tipo: "Pants",
        color: "Beige",
        marca: "Gym Shark"
    },
    {
        id: 4,
        nombre: "Strenght Hoodie",
        categoria: "Hombre",
        precio: 900.00,
        stock: 1,
        imagen1: "hombre/4.png",
        imagen2: "hombre/4.1.png",
        talla: "M - Regular Fit",
        tallaBase: "M",
        tipo: "Hoodie",
        color: "Beige",
        marca: "Gym Shark"
    },
    {
        id: 5,
        nombre: "Prayer Hands Hoodie",
        categoria: "Hombre",
        precio: 900.00,
        stock: 1,
        imagen1: "hombre/5.png",
        imagen2: "",
        talla: "L - Extreme Oversized",
        tallaBase: "L",
        tipo: "Hoodie",
        color: "Gris",
        marca: "Gym Shark"
    },
    {
        id: 6,
        nombre: "Collegiate - Short",
        categoria: "Hombre",
        precio: 600.00,
        stock: 1,
        imagen1: "hombre/6.png",
        imagen2: "hombre/6.1.png",
        talla: "S - Regular Fit",
        tallaBase: "S",
        tipo: "Short",
        color: "Verde",
        marca: "YoungLA"
    },
    {
        id: 7,
        nombre: "Rest Day",
        categoria: "Hombre",
        precio: 600.00,
        stock: 1,
        imagen1: "hombre/7.png",
        imagen2: "",
        talla: "S - Regular Fit",
        tallaBase: "S",
        tipo: "Short",
        color: "Gris",
        marca: "YoungLA"
    },
    {
        id: 8,
        nombre: "Collegiate - Short",
        categoria: "Hombre",
        precio: 600.00,
        stock: 1,
        imagen1: "hombre/8.png",
        imagen2: "hombre/8.1.png",
        talla: "M - Regular Fit",
        tallaBase: "M",
        tipo: "Short",
        color: "Verde",
        marca: "YoungLA"
    },
    {
        id: 9,
        nombre: "Collegiate - Short",
        categoria: "Hombre",
        precio: 600.00,
        stock: 1,
        imagen1: "hombre/9.png",
        imagen2: "hombre/9.1.png",
        talla: "S - Regular Fit",
        tallaBase: "S",
        tipo: "Short",
        color: "Gris",
        marca: "YoungLA"
    },
    {
        id: 10,
        nombre: "Sport - Panel",
        categoria: "Hombre",
        precio: 500.00,
        stock: 1,
        imagen1: "hombre/10.png",
        imagen2: "hombre/10.1.png",
        talla: "S - Slim Fit",
        tallaBase: "S",
        tipo: "Short",
        color: "Cafe",
        marca: "YoungLA"
    },
    {
        id: 11,
        nombre: "Collegiate - Short",
        categoria: "Hombre",
        precio: 600.00,
        stock: 1,
        imagen1: "hombre/11.png",
        imagen2: "hombre/11.1.png",
        talla: "M - Slim Fit",
        tallaBase: "M",
        tipo: "Short",
        color: "Gris",
        marca: "Uniqlo"
    },
    {
        id: 12,
        nombre: "Collegiate - Short",
        categoria: "Hombre",
        precio: 600.00,
        stock: 1,
        imagen1: "hombre/12.png",
        imagen2: "hombre/12.1.png",
        talla: "M - Slim Fit",
        tallaBase: "M",
        tipo: "Short",
        color: "Negro",
        marca: "Uniqlo"
    },
    {
        id: 13,
        nombre: "Varsity - Mesh",
        categoria: "Hombre",
        precio: 500.00,
        stock: 3,
        imagen1: "hombre/13.png",
        imagen2: "hombre/13.1.png",
        talla: "S - Slim Fit",
        tallaBase: "S",
        tipo: "Short",
        color: "Rojo",
        marca: "Uniqlo"
    },
    {
        id: 14,
        nombre: "Collegiate - Short",
        categoria: "Hombre",
        precio: 600.00,
        stock: 1,
        imagen1: "hombre/14.png",
        imagen2: "hombre/14.1.png",
        talla: "S - Slim Fit",
        tallaBase: "S",
        tipo: "Short",
        color: "Negro",
        marca: "Uniqlo"
    },
    {
        id: 15,
        nombre: "Rest Day",
        categoria: "Hombre",
        precio: 600.00,
        stock: 1,
        imagen1: "hombre/15.png",
        imagen2: "hombre/15.1.png",
        talla: "S - Regular Fit",
        tallaBase: "S",
        tipo: "Short",
        color: "Negro",
        marca: "Uniqlo"
    },  
];





