// =============================================================================
// STOCK HOMBRE — Generado automáticamente con scripts/importar-stock.py
// Fuente: Google Sheets (hoja HOMBRE)
// Edita el sheet y vuelve a ejecutar el script para actualizar.
// =============================================================================
const productosHombre = [
    {
        id: 1,
        nombre: "ARRIVAL REGULAR FIT",
        categoria: "Hombre",
        precio: 750.00,
        stock: 1,
        imagen1: "hombre/1.webp",
        imagen2: "hombre/1.1.webp",
        talla: "S",
        tallaBase: "S",
        tipo: "T-Shirt",
        color: "Verde azulado",
        marca: "Gym Shark"
    },
    {
        id: 2,
        nombre: "ARRIVAL REGULAR FIT",
        categoria: "Hombre",
        precio: 550.00,
        stock: 1,
        imagen1: "hombre/2.webp",
        imagen2: "hombre/2.1.webp",
        talla: "S",
        tallaBase: "S",
        tipo: "T-Shirt",
        color: "Verde",
        marca: "Gym Shark"
    },
    {
        id: 3,
        nombre: "COLLEGIATE 9 SHORT",
        categoria: "Hombre",
        precio: 600.00,
        stock: 3,
        imagen1: "hombre/3.webp",
        imagen2: "hombre/3.1.webp",
        talla: "M",
        tallaBase: "M",
        tipo: "Short",
        color: "Verde",
        marca: "Gym Shark"
    },
    {
        id: 4,
        nombre: "COLLEGIATE 9 SHORT",
        categoria: "Hombre",
        precio: 600.00,
        stock: 1,
        imagen1: "hombre/4.webp",
        imagen2: "hombre/4.1.webp",
        talla: "S",
        tallaBase: "S",
        tipo: "Short",
        color: "Gris",
        marca: "Gym Shark"
    },
    {
        id: 5,
        nombre: "COLLEGIATE 9 SHORT",
        categoria: "Hombre",
        precio: 600.00,
        stock: 1,
        imagen1: "hombre/5.webp",
        imagen2: "hombre/5.1.webp",
        talla: "L",
        tallaBase: "L",
        tipo: "Short",
        color: "Gris",
        marca: "Gym Shark"
    },
    {
        id: 6,
        nombre: "COLLEGIATE 9 SHORT",
        categoria: "Hombre",
        precio: 600.00,
        stock: 2,
        imagen1: "hombre/6.webp",
        imagen2: "hombre/6.1.webp",
        talla: "S",
        tallaBase: "S",
        tipo: "Short",
        color: "Verde",
        marca: "Gym Shark"
    },
    {
        id: 7,
        nombre: "COLLEGIATE 9 SHORT",
        categoria: "Hombre",
        precio: 600.00,
        stock: 2,
        imagen1: "hombre/7.webp",
        imagen2: "hombre/7.1.webp",
        talla: "M",
        tallaBase: "M",
        tipo: "Short",
        color: "Negro",
        marca: "Gym Shark"
    },
    {
        id: 8,
        nombre: "COLLEGIATE 9 SHORT",
        categoria: "Hombre",
        precio: 600.00,
        stock: 1,
        imagen1: "hombre/8.webp",
        imagen2: "hombre/8.1.webp",
        talla: "S",
        tallaBase: "S",
        tipo: "Short",
        color: "Negro",
        marca: "Gym Shark"
    },
    {
        id: 9,
        nombre: "ELEMENT BASELAYER",
        categoria: "Hombre",
        precio: 1000.00,
        stock: 1,
        imagen1: "hombre/9.webp",
        imagen2: "hombre/9.1.webp",
        talla: "S",
        tallaBase: "S",
        tipo: "T-Shirt",
        color: "Blanco",
        marca: "Gym Shark"
    },
    {
        id: 10,
        nombre: "ELEMENT BASELAYER",
        categoria: "Hombre",
        precio: 1000.00,
        stock: 1,
        imagen1: "hombre/10.webp",
        imagen2: "hombre/10.1.webp",
        talla: "M",
        tallaBase: "M",
        tipo: "T-Shirt",
        color: "Blanco",
        marca: "Gym Shark"
    },
    {
        id: 11,
        nombre: "ELEMENT BASELAYER TANK",
        categoria: "Hombre",
        precio: 850.00,
        stock: 1,
        imagen1: "hombre/11.webp",
        imagen2: "hombre/11.1.webp",
        talla: "S",
        tallaBase: "S",
        tipo: "T-Shirt",
        color: "Rojo",
        marca: "Gym Shark"
    },
    {
        id: 12,
        nombre: "FIT ELITE 5",
        categoria: "Hombre",
        precio: 600.00,
        stock: 1,
        imagen1: "hombre/12.webp",
        imagen2: "hombre/12.1.webp",
        talla: "S",
        tallaBase: "S",
        tipo: "Short",
        color: "Verde",
        marca: "Gym Shark"
    },
    {
        id: 13,
        nombre: "LEGACY SHORT",
        categoria: "Hombre",
        precio: 600.00,
        stock: 1,
        imagen1: "hombre/13.webp",
        imagen2: "hombre/13.1.webp",
        talla: "M",
        tallaBase: "M",
        tipo: "Short",
        color: "Negro",
        marca: "Gym Shark"
    },
    {
        id: 14,
        nombre: "LIFTING MESH 5",
        categoria: "Hombre",
        precio: 550.00,
        stock: 1,
        imagen1: "hombre/14.webp",
        imagen2: "hombre/14.1.webp",
        talla: "S",
        tallaBase: "S",
        tipo: "Short",
        color: "Gris",
        marca: "Gym Shark"
    },
    {
        id: 15,
        nombre: "LIFTING MESH 5",
        categoria: "Hombre",
        precio: 550.00,
        stock: 1,
        imagen1: "hombre/15.webp",
        imagen2: "hombre/15.1.webp",
        talla: "S",
        tallaBase: "S",
        tipo: "Short",
        color: "Negro",
        marca: "Gym Shark"
    },
    {
        id: 16,
        nombre: "LIFTING MESH 5",
        categoria: "Hombre",
        precio: 500.00,
        stock: 3,
        imagen1: "hombre/16.webp",
        imagen2: "hombre/16.1.webp",
        talla: "S",
        tallaBase: "S",
        tipo: "Short",
        color: "Negro",
        marca: "Gym Shark"
    },
    {
        id: 17,
        nombre: "LIFTING MESH 5",
        categoria: "Hombre",
        precio: 500.00,
        stock: 2,
        imagen1: "hombre/17.webp",
        imagen2: "hombre/17.1.webp",
        talla: "M",
        tallaBase: "M",
        tipo: "Short",
        color: "Negro",
        marca: "Gym Shark"
    },
    {
        id: 18,
        nombre: "LIFTING MESH 5",
        categoria: "Hombre",
        precio: 550.00,
        stock: 3,
        imagen1: "hombre/18.webp",
        imagen2: "hombre/18.1.webp",
        talla: "S",
        tallaBase: "S",
        tipo: "Short",
        color: "Verde",
        marca: "Gym Shark"
    },
    {
        id: 19,
        nombre: "SPORT PANEL 7",
        categoria: "Hombre",
        precio: 500.00,
        stock: 1,
        imagen1: "hombre/19.webp",
        imagen2: "hombre/19.1.webp",
        talla: "S",
        tallaBase: "S",
        tipo: "Short",
        color: "Marrón",
        marca: "Gym Shark"
    },
    {
        id: 20,
        nombre: "SPORT PANEL 7",
        categoria: "Hombre",
        precio: 500.00,
        stock: 2,
        imagen1: "hombre/20.webp",
        imagen2: "hombre/20.1.webp",
        talla: "S",
        tallaBase: "S",
        tipo: "Short",
        color: "Azul",
        marca: "Gym Shark"
    },
    {
        id: 21,
        nombre: "VARSITY MESH",
        categoria: "Hombre",
        precio: 500.00,
        stock: 2,
        imagen1: "hombre/21.webp",
        imagen2: "hombre/21.1.webp",
        talla: "S",
        tallaBase: "S",
        tipo: "Short",
        color: "Rojo",
        marca: "Gym Shark"
    },
    {
        id: 22,
        nombre: "WAFFLE SHORT",
        categoria: "Hombre",
        precio: 700.00,
        stock: 2,
        imagen1: "hombre/22.webp",
        imagen2: "hombre/22.1.jpg",
        talla: "M",
        tallaBase: "M",
        tipo: "Short",
        color: "Negro",
        marca: "Gym Shark"
    },
    {
        id: 23,
        nombre: "WAFFLE SHORT",
        categoria: "Hombre",
        precio: 700.00,
        stock: 1,
        imagen1: "hombre/23.webp",
        imagen2: "hombre/23.1.webp",
        talla: "M",
        tallaBase: "M",
        tipo: "Short",
        color: "Gris",
        marca: "Gym Shark"
    },
    {
        id: 24,
        nombre: "INTERLOCK TECH JOGGERS",
        categoria: "Hombre",
        precio: 900.00,
        stock: 1,
        imagen1: "hombre/24.webp",
        imagen2: "hombre/24.1.webp",
        talla: "S",
        tallaBase: "S",
        tipo: "Joggers",
        color: "Negro",
        marca: "Gym Shark"
    },
    {
        id: 25,
        nombre: "STRENGHT OF TOMORROW ZIP UP HOODIE",
        categoria: "Hombre",
        precio: 990.00,
        stock: 2,
        imagen1: "hombre/25.webp",
        imagen2: "hombre/25.1.webp",
        talla: "L",
        tallaBase: "L",
        tipo: "Hoodie",
        color: "Negro",
        marca: "Gym Shark"
    },
    {
        id: 26,
        nombre: "CREST T-SHIRT",
        categoria: "Hombre",
        precio: 550.00,
        stock: 2,
        imagen1: "hombre/26.webp",
        imagen2: "hombre/26.1.webp",
        talla: "S",
        tallaBase: "S",
        tipo: "T-Shirt",
        color: "Azul",
        marca: "Gym Shark"
    },
    {
        id: 27,
        nombre: "CREST T-SHIRT",
        categoria: "Hombre",
        precio: 550.00,
        stock: 2,
        imagen1: "hombre/27.webp",
        imagen2: "hombre/27.1.jpg",
        talla: "M",
        tallaBase: "M",
        tipo: "T-Shirt",
        color: "Azul",
        marca: "Gym Shark"
    },
    {
        id: 28,
        nombre: "CREST T-SHIRT",
        categoria: "Hombre",
        precio: 550.00,
        stock: 2,
        imagen1: "hombre/28.webp",
        imagen2: "hombre/28.1.webp",
        talla: "L",
        tallaBase: "L",
        tipo: "T-Shirt",
        color: "Azul",
        marca: "Gym Shark"
    },
    {
        id: 29,
        nombre: "CREST T-SHIRT",
        categoria: "Hombre",
        precio: 550.00,
        stock: 1,
        imagen1: "hombre/29.webp",
        imagen2: "hombre/29.1.webp",
        talla: "S",
        tallaBase: "S",
        tipo: "T-Shirt",
        color: "Marrón",
        marca: "Gym Shark"
    },
    {
        id: 30,
        nombre: "CREST T-SHIRT",
        categoria: "Hombre",
        precio: 550.00,
        stock: 2,
        imagen1: "hombre/30.webp",
        imagen2: "hombre/30.1.jpg",
        talla: "M",
        tallaBase: "M",
        tipo: "T-Shirt",
        color: "Marrón",
        marca: "Gym Shark"
    },
    {
        id: 31,
        nombre: "CREST T-SHIRT",
        categoria: "Hombre",
        precio: 550.00,
        stock: 2,
        imagen1: "hombre/31.webp",
        imagen2: "hombre/31.1.webp",
        talla: "L",
        tallaBase: "L",
        tipo: "T-Shirt",
        color: "Marrón",
        marca: "Gym Shark"
    },
    {
        id: 32,
        nombre: "RIBBED TANK 1PK",
        categoria: "Hombre",
        precio: 500.00,
        stock: 1,
        imagen1: "hombre/32.webp",
        imagen2: "hombre/32.1.webp",
        talla: "L",
        tallaBase: "L",
        tipo: "Tank Top",
        color: "Blanco",
        marca: "Gym Shark"
    },
    {
        id: 33,
        nombre: "RUNNING LONG SLEEVE T-SHIRT",
        categoria: "Hombre",
        precio: 600.00,
        stock: 2,
        imagen1: "hombre/33.webp",
        imagen2: "hombre/33.1.webp",
        talla: "S",
        tallaBase: "S",
        tipo: "Long Sleeve",
        color: "Verde",
        marca: "Gym Shark"
    },
    {
        id: 34,
        nombre: "RUNNING LONG SLEEVE T-SHIRT",
        categoria: "Hombre",
        precio: 600.00,
        stock: 2,
        imagen1: "hombre/34.webp",
        imagen2: "hombre/34.1.webp",
        talla: "M",
        tallaBase: "M",
        tipo: "Long Sleeve",
        color: "Verde",
        marca: "Gym Shark"
    },
    {
        id: 35,
        nombre: "COLLEGIATE CONTRAST 5",
        categoria: "Hombre",
        precio: 550.00,
        stock: 3,
        imagen1: "hombre/35.webp",
        imagen2: "hombre/35.1.webp",
        talla: "S",
        tallaBase: "S",
        tipo: "Short",
        color: "Azul",
        marca: "Gym Shark"
    },
    {
        id: 36,
        nombre: "FIND YOUR SPEED JACKET",
        categoria: "Hombre",
        precio: 990.00,
        stock: 2,
        imagen1: "hombre/36.webp",
        imagen2: "hombre/36.1.webp",
        talla: "S",
        tallaBase: "S",
        tipo: "Hoodie",
        color: "Gris",
        marca: "Gym Shark"
    },
    {
        id: 37,
        nombre: "KNITTED SCARF/BEANIE GIFT SET",
        categoria: "Hombre",
        precio: 380.00,
        stock: 1,
        imagen1: "hombre/37.webp",
        imagen2: "hombre/37.1.webp",
        talla: "ONE SIZE",
        tallaBase: "ONE SIZE",
        tipo: "Scarf",
        color: "Blanco",
        marca: "Gym Shark"
    },
    {
        id: 38,
        nombre: "ESSENTIAL OVERSIZED JOGGERS",
        categoria: "Hombre",
        precio: 650.00,
        stock: 3,
        imagen1: "hombre/38.webp",
        imagen2: "hombre/38.1.webp",
        talla: "S",
        tallaBase: "S",
        tipo: "Joggers",
        color: "Azul marino",
        marca: "Gym Shark"
    },
    {
        id: 39,
        nombre: "ESSENTIAL OVERSIZED JOGGERS",
        categoria: "Hombre",
        precio: 650.00,
        stock: 3,
        imagen1: "hombre/39.webp",
        imagen2: "hombre/39.1.webp",
        talla: "S",
        tallaBase: "S",
        tipo: "Joggers",
        color: "Gris",
        marca: "Gym Shark"
    },
    {
        id: 40,
        nombre: "VARSITY HOODIE",
        categoria: "Hombre",
        precio: 900.00,
        stock: 1,
        imagen1: "hombre/40.webp",
        imagen2: "hombre/40.1.webp",
        talla: "L",
        tallaBase: "L",
        tipo: "Hoodie",
        color: "Negro",
        marca: "Gym Shark"
    },
    {
        id: 41,
        nombre: "2012 STRENGTH JOGGERS",
        categoria: "Hombre",
        precio: 850.00,
        stock: 1,
        imagen1: "hombre/41.webp",
        imagen2: "hombre/41.1.webp",
        talla: "L",
        tallaBase: "L",
        tipo: "Joggers",
        color: "Gris",
        marca: "Gym Shark"
    },
    {
        id: 42,
        nombre: "CREST SWEATSHIRT",
        categoria: "Hombre",
        precio: 720.00,
        stock: 3,
        imagen1: "hombre/42.webp",
        imagen2: "hombre/42.1.webp",
        talla: "S",
        tallaBase: "S",
        tipo: "Hoodie",
        color: "Negro",
        marca: "Gym Shark"
    },
    {
        id: 43,
        nombre: "RETAKE ANORAK",
        categoria: "Hombre",
        precio: 1000.00,
        stock: 2,
        imagen1: "hombre/43.webp",
        imagen2: "hombre/43.1.webp",
        talla: "L",
        tallaBase: "L",
        tipo: "Jacket",
        color: "Negro",
        marca: "Gym Shark"
    },
    {
        id: 44,
        nombre: "FIT REPEAT 6",
        categoria: "Hombre",
        precio: 550.00,
        stock: 1,
        imagen1: "hombre/44.webp",
        imagen2: "hombre/44.1.webp",
        talla: "S",
        tallaBase: "S",
        tipo: "Short",
        color: "Azul",
        marca: "Gym Shark"
    },
    {
        id: 45,
        nombre: "TACTICAL 6 SHORT",
        categoria: "Hombre",
        precio: 550.00,
        stock: 2,
        imagen1: "hombre/45.webp",
        imagen2: "hombre/45.1.webp",
        talla: "S",
        tallaBase: "S",
        tipo: "Short",
        color: "Verde",
        marca: "Gym Shark"
    },
    {
        id: 46,
        nombre: "TACTICAL 6 SHORT",
        categoria: "Hombre",
        precio: 720.00,
        stock: 1,
        imagen1: "hombre/46.webp",
        imagen2: "hombre/46.1.webp",
        talla: "S",
        tallaBase: "S",
        tipo: "Short",
        color: "Negro",
        marca: "Gym Shark"
    },
    {
        id: 47,
        nombre: "ARRIVAL SHORT",
        categoria: "Hombre",
        precio: 550.00,
        stock: 1,
        imagen1: "hombre/47.webp",
        imagen2: "hombre/47.1.webp",
        talla: "L",
        tallaBase: "L",
        tipo: "Short",
        color: "Blanco",
        marca: "Gym Shark"
    },
    {
        id: 48,
        nombre: "ARRIVAL SHORT",
        categoria: "Hombre",
        precio: 550.00,
        stock: 1,
        imagen1: "hombre/48.webp",
        imagen2: "hombre/48.1.webp",
        talla: "M",
        tallaBase: "M",
        tipo: "Short",
        color: "Blanco",
        marca: "Gym Shark"
    },
    {
        id: 49,
        nombre: "2012 STRENGHT JOGGERS",
        categoria: "Hombre",
        precio: 700.00,
        stock: 1,
        imagen1: "hombre/49.webp",
        imagen2: "hombre/49.1.webp",
        talla: "M",
        tallaBase: "M",
        tipo: "Joggers",
        color: "Gris",
        marca: "Gym Shark"
    },
    {
        id: 50,
        nombre: "2012 STRENGHT JOGGERS",
        categoria: "Hombre",
        precio: 700.00,
        stock: 1,
        imagen1: "hombre/50.webp",
        imagen2: "hombre/50.1.webp",
        talla: "S",
        tallaBase: "S",
        tipo: "Joggers",
        color: "Gris",
        marca: "Gym Shark"
    },
    {
        id: 51,
        nombre: "CREST JOGGERS",
        categoria: "Hombre",
        precio: 750.00,
        stock: 1,
        imagen1: "hombre/51.webp",
        imagen2: "hombre/51.1.webp",
        talla: "M",
        tallaBase: "M",
        tipo: "Joggers",
        color: "Negro",
        marca: "Gym Shark"
    },
    {
        id: 52,
        nombre: "CREST JOGGERS",
        categoria: "Hombre",
        precio: 750.00,
        stock: 1,
        imagen1: "hombre/52.webp",
        imagen2: "hombre/52.1.webp",
        talla: "M",
        tallaBase: "M",
        tipo: "Joggers",
        color: "Gris",
        marca: "Gym Shark"
    },
    {
        id: 53,
        nombre: "CREST JOGGERS",
        categoria: "Hombre",
        precio: 750.00,
        stock: 1,
        imagen1: "hombre/53.webp",
        imagen2: "hombre/53.1.webp",
        talla: "L",
        tallaBase: "L",
        tipo: "Joggers",
        color: "Gris",
        marca: "Gym Shark"
    },
    {
        id: 54,
        nombre: "HERITAGE 5 SHORTS",
        categoria: "Hombre",
        precio: 550.00,
        stock: 1,
        imagen1: "hombre/54.webp",
        imagen2: "hombre/54.1.webp",
        talla: "S",
        tallaBase: "S",
        tipo: "Short",
        color: "Onyx Grey",
        marca: "Gym Shark"
    },
    {
        id: 55,
        nombre: "HERITAGE 5 SHORTS",
        categoria: "Hombre",
        precio: 550.00,
        stock: 1,
        imagen1: "hombre/55.webp",
        imagen2: "hombre/55.1.webp",
        talla: "S",
        tallaBase: "S",
        tipo: "Short",
        color: "Gris",
        marca: "Gym Shark"
    },
    {
        id: 56,
        nombre: "AOT X YLA BAGGY JOGGERS 2128",
        categoria: "Hombre",
        precio: 1500.00,
        stock: 1,
        imagen1: "hombre/56.webp",
        imagen2: "hombre/56.1.webp",
        talla: "M",
        tallaBase: "M",
        tipo: "Joggers",
        color: "Negro",
        marca: "YoungLA"
    },
    {
        id: 57,
        nombre: "DARK MAGICIAN TEE 4152",
        categoria: "Hombre",
        precio: 1200.00,
        stock: 2,
        imagen1: "hombre/57.webp",
        imagen2: "",
        talla: "M",
        tallaBase: "M",
        tipo: "T-Shirt",
        color: "Negro",
        marca: "YoungLA"
    },
    {
        id: 58,
        nombre: "VENOM JERSEYS",
        categoria: "Hombre",
        precio: 750.00,
        stock: 1,
        imagen1: "hombre/58.webp",
        imagen2: "",
        talla: "S",
        tallaBase: "S",
        tipo: "Jersey",
        color: "Black Tree Camo",
        marca: "YoungLA"
    },
    {
        id: 59,
        nombre: "OLY LIFTING STRAPS",
        categoria: "Hombre",
        precio: 350.00,
        stock: 5,
        imagen1: "hombre/59.webp",
        imagen2: "hombre/59.1.webp",
        talla: "ONE SIZE",
        tallaBase: "ONE SIZE",
        tipo: "Straps",
        color: "Azul",
        marca: "Gym Shark"
    },
    {
        id: 60,
        nombre: "CREW SOCKS 3PK",
        categoria: "Hombre",
        precio: 450.00,
        stock: 1,
        imagen1: "hombre/60.webp",
        imagen2: "hombre/60.1.webp",
        talla: "S",
        tallaBase: "S",
        tipo: "Socks",
        color: "Blanco",
        marca: "Gym Shark"
    },
    {
        id: 61,
        nombre: "COLLEGIATE CREW SOCKS 3PK",
        categoria: "Hombre",
        precio: 520.00,
        stock: 1,
        imagen1: "hombre/61.webp",
        imagen2: "hombre/61.1.webp",
        talla: "M",
        tallaBase: "M",
        tipo: "Socks",
        color: "Rosa",
        marca: "Gym Shark"
    },
    {
        id: 62,
        nombre: "COLLEGIATE CREW SOCKS 3PK",
        categoria: "Hombre",
        precio: 520.00,
        stock: 2,
        imagen1: "hombre/62.webp",
        imagen2: "hombre/62.1.webp",
        talla: "M",
        tallaBase: "M",
        tipo: "Socks",
        color: "Azul",
        marca: "Gym Shark"
    },
    {
        id: 63,
        nombre: "CREW SOCKS 5 PK",
        categoria: "Hombre",
        precio: 450.00,
        stock: 5,
        imagen1: "hombre/63.webp",
        imagen2: "hombre/63.1.webp",
        talla: "S",
        tallaBase: "S",
        tipo: "Socks",
        color: "Negro",
        marca: "Gym Shark"
    },
    {
        id: 64,
        nombre: "COLLEGIATE CAP",
        categoria: "Hombre",
        precio: 500.00,
        stock: 2,
        imagen1: "hombre/64.webp",
        imagen2: "hombre/64.1.webp",
        talla: "ONE SIZE",
        tallaBase: "ONE SIZE",
        tipo: "Caps",
        color: "Azul",
        marca: "Gym Shark"
    },
    {
        id: 65,
        nombre: "DEEP KNIT BEANIE",
        categoria: "Hombre",
        precio: 350.00,
        stock: 3,
        imagen1: "hombre/65.webp",
        imagen2: "hombre/65.1.webp",
        talla: "ONE SIZE",
        tallaBase: "ONE SIZE",
        tipo: "Beanie",
        color: "Rosa",
        marca: "Gym Shark"
    },
    {
        id: 66,
        nombre: "FOUNDATION TRACK PANTS 2113",
        categoria: "Hombre",
        precio: 1200.00,
        stock: 1,
        imagen1: "hombre/66.webp",
        imagen2: "hombre/66.1.webp",
        talla: "L",
        tallaBase: "L",
        tipo: "Pants",
        color: "Negro",
        marca: "YoungLA"
    },
    {
        id: 67,
        nombre: "2.2L WATER BOTTLE",
        categoria: "Hombre",
        precio: 510.00,
        stock: 2,
        imagen1: "hombre/67.webp",
        imagen2: "hombre/67.1.webp",
        talla: "ONE SIZE",
        tallaBase: "ONE SIZE",
        tipo: "Bottle",
        color: "Negro",
        marca: "Gym Shark"
    },
    {
        id: 68,
        nombre: "500ML BOTTLE",
        categoria: "Hombre",
        precio: 750.00,
        stock: 2,
        imagen1: "hombre/68.webp",
        imagen2: "hombre/68.1.webp",
        talla: "ONE SIZE",
        tallaBase: "ONE SIZE",
        tipo: "Bottle",
        color: "Gris",
        marca: "Gym Shark"
    },
    {
        id: 69,
        nombre: "SUPERMAN COMPRESSION 4117",
        categoria: "Hombre",
        precio: 1300.00,
        stock: 1,
        imagen1: "hombre/69.webp",
        imagen2: "",
        talla: "M",
        tallaBase: "M",
        tipo: "Compression Shirt",
        color: "Negro",
        marca: "Gym Shark"
    },
    {
        id: 70,
        nombre: "ARRIVAL CONTRAST T-SHIRT",
        categoria: "Hombre",
        precio: 550.00,
        stock: 1,
        imagen1: "hombre/70.webp",
        imagen2: "hombre/70.1.webp",
        talla: "L",
        tallaBase: "L",
        tipo: "T-Shirt",
        color: "Gris",
        marca: "Gym Shark"
    },
    {
        id: 71,
        nombre: "ARRIVAL CONTRAST T-SHIRT",
        categoria: "Hombre",
        precio: 550.00,
        stock: 1,
        imagen1: "hombre/71.webp",
        imagen2: "hombre/71.1.webp",
        talla: "L",
        tallaBase: "L",
        tipo: "T-Shirt",
        color: "Azul",
        marca: "Gym Shark"
    },
    {
        id: 72,
        nombre: "ARRIVAL CONTRAST T-SHIRT",
        categoria: "Hombre",
        precio: 550.00,
        stock: 1,
        imagen1: "hombre/72.webp",
        imagen2: "hombre/72.1.webp",
        talla: "L",
        tallaBase: "L",
        tipo: "T-Shirt",
        color: "Verde",
        marca: "Gym Shark"
    },
    {
        id: 73,
        nombre: "ARRIVAL CONTRAST T-SHIRT",
        categoria: "Hombre",
        precio: 550.00,
        stock: 1,
        imagen1: "hombre/73.webp",
        imagen2: "hombre/73.1.webp",
        talla: "L",
        tallaBase: "L",
        tipo: "T-Shirt",
        color: "Gris",
        marca: "Gym Shark"
    },
    {
        id: 74,
        nombre: "ARRIVAL CONTRAST T-SHIRT",
        categoria: "Hombre",
        precio: 550.00,
        stock: 1,
        imagen1: "hombre/74.webp",
        imagen2: "hombre/74.1.webp",
        talla: "S",
        tallaBase: "S",
        tipo: "T-Shirt",
        color: "Azul",
        marca: "Gym Shark"
    },
    {
        id: 75,
        nombre: "ARRIVAL CONTRAST T-SHIRT",
        categoria: "Hombre",
        precio: 550.00,
        stock: 1,
        imagen1: "hombre/75.webp",
        imagen2: "hombre/75.1.webp",
        talla: "S",
        tallaBase: "S",
        tipo: "T-Shirt",
        color: "Verde",
        marca: "Gym Shark"
    },
    {
        id: 76,
        nombre: "ARRIVAL CONTRAST T-SHIRT",
        categoria: "Hombre",
        precio: 550.00,
        stock: 1,
        imagen1: "hombre/76.webp",
        imagen2: "hombre/76.1.jpg",
        talla: "L",
        tallaBase: "L",
        tipo: "T-Shirt",
        color: "Negro",
        marca: "Gym Shark"
    },
    {
        id: 77,
        nombre: "ARRIVAL CONTRAST T-SHIRT",
        categoria: "Hombre",
        precio: 550.00,
        stock: 1,
        imagen1: "hombre/77.webp",
        imagen2: "hombre/77.1.webp",
        talla: "M",
        tallaBase: "M",
        tipo: "T-Shirt",
        color: "Azul",
        marca: "Gym Shark"
    },
    {
        id: 78,
        nombre: "ARRIVAL CONTRAST T-SHIRT",
        categoria: "Hombre",
        precio: 550.00,
        stock: 1,
        imagen1: "hombre/78.webp",
        imagen2: "hombre/78.1.jpg",
        talla: "S",
        tallaBase: "S",
        tipo: "T-Shirt",
        color: "Gris",
        marca: "Gym Shark"
    },
    {
        id: 79,
        nombre: "ARRIVAL OVERSIZED TANK",
        categoria: "Hombre",
        precio: 500.00,
        stock: 1,
        imagen1: "hombre/79.webp",
        imagen2: "hombre/79.1.webp",
        talla: "M",
        tallaBase: "M",
        tipo: "Tank Top",
        color: "Rosa",
        marca: "Gym Shark"
    },
    {
        id: 80,
        nombre: "ARRIVAL TANK",
        categoria: "Hombre",
        precio: 500.00,
        stock: 1,
        imagen1: "hombre/80.webp",
        imagen2: "hombre/80.1.webp",
        talla: "L",
        tallaBase: "L",
        tipo: "Tank Top",
        color: "Verde",
        marca: "Gym Shark"
    },
    {
        id: 81,
        nombre: "BIG PATCH SWEATS",
        categoria: "Hombre",
        precio: 1500.00,
        stock: 1,
        imagen1: "hombre/81.webp",
        imagen2: "hombre/81.1.webp",
        talla: "M",
        tallaBase: "M",
        tipo: "Pants",
        color: "Negro",
        marca: "YoungLA"
    },
    {
        id: 82,
        nombre: "BUILT FOR MORE T-SHIRT",
        categoria: "Hombre",
        precio: 550.00,
        stock: 1,
        imagen1: "hombre/82.webp",
        imagen2: "hombre/82.1.webp",
        talla: "L",
        tallaBase: "L",
        tipo: "T-Shirt",
        color: "Negro",
        marca: "Gym Shark"
    },
    {
        id: 83,
        nombre: "BUILT FOR MORE T-SHIRT",
        categoria: "Hombre",
        precio: 550.00,
        stock: 1,
        imagen1: "hombre/83.webp",
        imagen2: "hombre/83.1.webp",
        talla: "S",
        tallaBase: "S",
        tipo: "T-Shirt",
        color: "Blanco",
        marca: "Gym Shark"
    },
    {
        id: 84,
        nombre: "BUILT FOR MORE T-SHIRT",
        categoria: "Hombre",
        precio: 550.00,
        stock: 1,
        imagen1: "hombre/84.webp",
        imagen2: "hombre/84.1.webp",
        talla: "L",
        tallaBase: "L",
        tipo: "T-Shirt",
        color: "Blanco",
        marca: "Gym Shark"
    },
    {
        id: 85,
        nombre: "BUILT FOR MORE T-SHIRT",
        categoria: "Hombre",
        precio: 550.00,
        stock: 1,
        imagen1: "hombre/85.webp",
        imagen2: "hombre/85.1.webp",
        talla: "L",
        tallaBase: "L",
        tipo: "T-Shirt",
        color: "Gris",
        marca: "Gym Shark"
    },
    {
        id: 86,
        nombre: "BUILT FOR MORE T-SHIRT",
        categoria: "Hombre",
        precio: 550.00,
        stock: 1,
        imagen1: "hombre/86.webp",
        imagen2: "hombre/86.1.webp",
        talla: "M",
        tallaBase: "M",
        tipo: "T-Shirt",
        color: "Marrón",
        marca: "Gym Shark"
    },
    {
        id: 87,
        nombre: "BUILT FOR MORE T-SHIRT",
        categoria: "Hombre",
        precio: 550.00,
        stock: 1,
        imagen1: "hombre/87.webp",
        imagen2: "hombre/87.1.jpg",
        talla: "L",
        tallaBase: "L",
        tipo: "T-Shirt",
        color: "Marrón",
        marca: "Gym Shark"
    },
    {
        id: 88,
        nombre: "BUILT FOR MORE T-SHIRT",
        categoria: "Hombre",
        precio: 550.00,
        stock: 1,
        imagen1: "hombre/88.webp",
        imagen2: "hombre/88.1.webp",
        talla: "M",
        tallaBase: "M",
        tipo: "T-Shirt",
        color: "Blanco",
        marca: "Gym Shark"
    },
    {
        id: 89,
        nombre: "BUILT FOR MORE T-SHIRT",
        categoria: "Hombre",
        precio: 550.00,
        stock: 1,
        imagen1: "hombre/89.webp",
        imagen2: "hombre/89.1.webp",
        talla: "M",
        tallaBase: "M",
        tipo: "T-Shirt",
        color: "Gris",
        marca: "Gym Shark"
    },
    {
        id: 90,
        nombre: "BUILT FOR MORE T-SHIRT",
        categoria: "Hombre",
        precio: 550.00,
        stock: 1,
        imagen1: "hombre/90.webp",
        imagen2: "hombre/90.1.webp",
        talla: "S",
        tallaBase: "S",
        tipo: "T-Shirt",
        color: "Negro",
        marca: "Gym Shark"
    },
    {
        id: 91,
        nombre: "BUILT FOR MORE T-SHIRT",
        categoria: "Hombre",
        precio: 550.00,
        stock: 1,
        imagen1: "hombre/91.webp",
        imagen2: "hombre/91.1.webp",
        talla: "S",
        tallaBase: "S",
        tipo: "T-Shirt",
        color: "Marrón",
        marca: "Gym Shark"
    },
    {
        id: 92,
        nombre: "BUILT FOR MORE T-SHIRT",
        categoria: "Hombre",
        precio: 550.00,
        stock: 1,
        imagen1: "hombre/92.webp",
        imagen2: "hombre/92.1.webp",
        talla: "S",
        tallaBase: "S",
        tipo: "T-Shirt",
        color: "Gris",
        marca: "Gym Shark"
    },
    {
        id: 93,
        nombre: "CHAOS TEES",
        categoria: "Hombre",
        precio: 1050.00,
        stock: 1,
        imagen1: "hombre/93.webp",
        imagen2: "hombre/93.1.webp",
        talla: "L",
        tallaBase: "L",
        tipo: "T-Shirt",
        color: "Negro",
        marca: "YoungLA"
    },
    {
        id: 94,
        nombre: "CHAOS TEES",
        categoria: "Hombre",
        precio: 1050.00,
        stock: 1,
        imagen1: "hombre/94.webp",
        imagen2: "hombre/94.1.webp",
        talla: "M",
        tallaBase: "M",
        tipo: "T-Shirt",
        color: "Negro",
        marca: "YoungLA"
    },
    {
        id: 95,
        nombre: "CREST OVERSIZED JOGGERS",
        categoria: "Hombre",
        precio: 750.00,
        stock: 1,
        imagen1: "hombre/95.webp",
        imagen2: "hombre/95.1.webp",
        talla: "M",
        tallaBase: "M",
        tipo: "Pants",
        color: "Marrón",
        marca: "Gym Shark"
    },
    {
        id: 96,
        nombre: "CREST OVERSIZED T-SHIRT",
        categoria: "Hombre",
        precio: 550.00,
        stock: 1,
        imagen1: "hombre/96.webp",
        imagen2: "hombre/96.1.webp",
        talla: "M",
        tallaBase: "M",
        tipo: "T-Shirt",
        color: "Azul",
        marca: "Gym Shark"
    },
    {
        id: 97,
        nombre: "CREST OVERSIZED T-SHIRT",
        categoria: "Hombre",
        precio: 550.00,
        stock: 1,
        imagen1: "hombre/97.webp",
        imagen2: "hombre/97.1.webp",
        talla: "S",
        tallaBase: "S",
        tipo: "T-Shirt",
        color: "Azul",
        marca: "Gym Shark"
    },
    {
        id: 98,
        nombre: "CREST OVERSIZED T-SHIRT",
        categoria: "Hombre",
        precio: 550.00,
        stock: 1,
        imagen1: "hombre/98.webp",
        imagen2: "hombre/98.1.webp",
        talla: "S",
        tallaBase: "S",
        tipo: "T-Shirt",
        color: "Azul",
        marca: "Gym Shark"
    },
    {
        id: 99,
        nombre: "CREST OVERSIZED T-SHIRT",
        categoria: "Hombre",
        precio: 550.00,
        stock: 1,
        imagen1: "hombre/99.webp",
        imagen2: "hombre/99.1.webp",
        talla: "L",
        tallaBase: "L",
        tipo: "T-Shirt",
        color: "Azul",
        marca: "Gym Shark"
    },
    {
        id: 100,
        nombre: "CREST OVERSIZED TRACK JACKET",
        categoria: "Hombre",
        precio: 800.00,
        stock: 1,
        imagen1: "hombre/100.webp",
        imagen2: "hombre/100.1.webp",
        talla: "M",
        tallaBase: "M",
        tipo: "Jacket",
        color: "Negro",
        marca: "Gym Shark"
    },
    {
        id: 101,
        nombre: "CREST OVERSIZED TRACK JACKET",
        categoria: "Hombre",
        precio: 800.00,
        stock: 1,
        imagen1: "hombre/101.webp",
        imagen2: "hombre/101.1.webp",
        talla: "M",
        tallaBase: "M",
        tipo: "Jacket",
        color: "Negro",
        marca: "Gym Shark"
    },
    {
        id: 102,
        nombre: "CREW SOCKS",
        categoria: "Hombre",
        precio: 500.00,
        stock: 1,
        imagen1: "hombre/102.webp",
        imagen2: "hombre/102.1.webp",
        talla: "S",
        tallaBase: "S",
        tipo: "Socks",
        color: "Negro",
        marca: "Gym Shark"
    },
    {
        id: 103,
        nombre: "CRITICAL CUT OFF TANK",
        categoria: "Hombre",
        precio: 500.00,
        stock: 1,
        imagen1: "hombre/103.webp",
        imagen2: "hombre/103.1.webp",
        talla: "M",
        tallaBase: "M",
        tipo: "Tank Top",
        color: "Blanco",
        marca: "Gym Shark"
    },
    {
        id: 104,
        nombre: "CRITICAL CUT OFF TANK",
        categoria: "Hombre",
        precio: 500.00,
        stock: 1,
        imagen1: "hombre/104.webp",
        imagen2: "hombre/104.1.webp",
        talla: "M",
        tallaBase: "M",
        tipo: "Tank Top",
        color: "Negro",
        marca: "Gym Shark"
    },
    {
        id: 105,
        nombre: "DARK WAVE JOGGERS",
        categoria: "Hombre",
        precio: 1500.00,
        stock: 1,
        imagen1: "hombre/105.webp",
        imagen2: "hombre/105.1.webp",
        talla: "L",
        tallaBase: "L",
        tipo: "Pants",
        color: "Negro",
        marca: "YoungLA"
    },
    {
        id: 106,
        nombre: "DARK WAVE WIFE LOVERS",
        categoria: "Hombre",
        precio: 750.00,
        stock: 1,
        imagen1: "hombre/106.webp",
        imagen2: "hombre/106.1.webp",
        talla: "L",
        tallaBase: "L",
        tipo: "Tank Top",
        color: "Negro",
        marca: "YoungLA"
    },
    {
        id: 107,
        nombre: "DISTRESSED SCRIPT TEES",
        categoria: "Hombre",
        precio: 1050.00,
        stock: 1,
        imagen1: "hombre/107.webp",
        imagen2: "hombre/107.1.webp",
        talla: "L",
        tallaBase: "L",
        tipo: "T-Shirt",
        color: "Negro",
        marca: "YoungLA"
    },
    {
        id: 108,
        nombre: "DISTRESSED SCRIPT TEES",
        categoria: "Hombre",
        precio: 1050.00,
        stock: 1,
        imagen1: "hombre/108.webp",
        imagen2: "hombre/108.1.webp",
        talla: "L",
        tallaBase: "L",
        tipo: "T-Shirt",
        color: "Blanco",
        marca: "YoungLA"
    },
    {
        id: 109,
        nombre: "DIVINE SWEATS",
        categoria: "Hombre",
        precio: 1600.00,
        stock: 1,
        imagen1: "hombre/109.webp",
        imagen2: "hombre/109.1.webp",
        talla: "L",
        tallaBase: "L",
        tipo: "Pants",
        color: "Negro",
        marca: "YoungLA"
    },
    {
        id: 110,
        nombre: "DYNASTY SWEATS",
        categoria: "Hombre",
        precio: 1500.00,
        stock: 1,
        imagen1: "hombre/110.webp",
        imagen2: "hombre/110.1.jpg",
        talla: "L",
        tallaBase: "L",
        tipo: "Pants",
        color: "Negro",
        marca: "YoungLA"
    },
    {
        id: 111,
        nombre: "ELEMENT BASELAYER T-SHIRT",
        categoria: "Hombre",
        precio: 800.00,
        stock: 1,
        imagen1: "hombre/111.webp",
        imagen2: "hombre/111.1.webp",
        talla: "M",
        tallaBase: "M",
        tipo: "T-Shirt",
        color: "Rojo",
        marca: "Gym Shark"
    },
    {
        id: 112,
        nombre: "FAITH SWEATS",
        categoria: "Hombre",
        precio: 1500.00,
        stock: 1,
        imagen1: "hombre/112.webp",
        imagen2: "hombre/112.1.webp",
        talla: "L",
        tallaBase: "L",
        tipo: "Pants",
        color: "Negro",
        marca: "YoungLA"
    },
    {
        id: 113,
        nombre: "FIT REPEAT 6 SHORTS",
        categoria: "Hombre",
        precio: 500.00,
        stock: 1,
        imagen1: "hombre/113.webp",
        imagen2: "hombre/113.1.webp",
        talla: "M",
        tallaBase: "M",
        tipo: "Short",
        color: "Verde",
        marca: "Gym Shark"
    },
    {
        id: 114,
        nombre: "FLAGSHIP TRACK PANTS",
        categoria: "Hombre",
        precio: 1350.00,
        stock: 1,
        imagen1: "hombre/114.webp",
        imagen2: "hombre/114.1.webp",
        talla: "M",
        tallaBase: "M",
        tipo: "Pants",
        color: "Verde",
        marca: "YoungLA"
    },
    {
        id: 115,
        nombre: "GLOBAL LIFTING GRAPHIC PANTS",
        categoria: "Hombre",
        precio: 800.00,
        stock: 1,
        imagen1: "hombre/115.webp",
        imagen2: "hombre/115.1.webp",
        talla: "M",
        tallaBase: "M",
        tipo: "Pants",
        color: "Gris",
        marca: "Gym Shark"
    },
    {
        id: 116,
        nombre: "GYMSHARK X CBUM CAP",
        categoria: "Hombre",
        precio: 900.00,
        stock: 1,
        imagen1: "hombre/116.webp",
        imagen2: "hombre/116.1.webp",
        talla: "ONE SIZE",
        tallaBase: "ONE SIZE",
        tipo: "Cap",
        color: "Negro",
        marca: "Gym Shark"
    },
    {
        id: 117,
        nombre: "GYMSHARK X CBUM HOCKEY JERSEY",
        categoria: "Hombre",
        precio: 1500.00,
        stock: 1,
        imagen1: "hombre/117.webp",
        imagen2: "hombre/117.1.webp",
        talla: "L",
        tallaBase: "L",
        tipo: "Jersey",
        color: "Rojo",
        marca: "Gym Shark"
    },
    {
        id: 118,
        nombre: "GYMSHARK X CBUM HOCKEY JERSEY",
        categoria: "Hombre",
        precio: 1500.00,
        stock: 1,
        imagen1: "hombre/118.webp",
        imagen2: "hombre/118.1.webp",
        talla: "M",
        tallaBase: "M",
        tipo: "Jersey",
        color: "Negro",
        marca: "Gym Shark"
    },
    {
        id: 119,
        nombre: "GYMSHARK X CBUM HOCKEY JERSEY",
        categoria: "Hombre",
        precio: 1500.00,
        stock: 1,
        imagen1: "hombre/119.webp",
        imagen2: "hombre/119.1.webp",
        talla: "M",
        tallaBase: "M",
        tipo: "Jersey",
        color: "Rojo",
        marca: "Gym Shark"
    },
    {
        id: 120,
        nombre: "GYMSHARK X CBUM HOCKEY JERSEY",
        categoria: "Hombre",
        precio: 1500.00,
        stock: 1,
        imagen1: "hombre/120.webp",
        imagen2: "hombre/120.1.webp",
        talla: "S",
        tallaBase: "S",
        tipo: "Jersey",
        color: "Rojo",
        marca: "Gym Shark"
    },
    {
        id: 121,
        nombre: "GYMSHARK X CBUM T-SHIRT",
        categoria: "Hombre",
        precio: 1200.00,
        stock: 1,
        imagen1: "hombre/121.webp",
        imagen2: "hombre/121.1.webp",
        talla: "L",
        tallaBase: "L",
        tipo: "T-Shirt",
        color: "Blanco",
        marca: "Gym Shark"
    },
    {
        id: 122,
        nombre: "GYMSHARK X CBUM T-SHIRT",
        categoria: "Hombre",
        precio: 1200.00,
        stock: 1,
        imagen1: "hombre/122.webp",
        imagen2: "hombre/122.1.webp",
        talla: "M",
        tallaBase: "M",
        tipo: "T-Shirt",
        color: "Negro",
        marca: "Gym Shark"
    },
    {
        id: 123,
        nombre: "GYMSHARK X CBUM T-SHIRT",
        categoria: "Hombre",
        precio: 1200.00,
        stock: 1,
        imagen1: "hombre/123.webp",
        imagen2: "hombre/123.1.webp",
        talla: "M",
        tallaBase: "M",
        tipo: "T-Shirt",
        color: "Blanco",
        marca: "Gym Shark"
    },
    {
        id: 124,
        nombre: "GYMSHARK X CBUM T-SHIRT",
        categoria: "Hombre",
        precio: 1200.00,
        stock: 1,
        imagen1: "hombre/124.webp",
        imagen2: "hombre/124.1.webp",
        talla: "S",
        tallaBase: "S",
        tipo: "T-Shirt",
        color: "Negro",
        marca: "Gym Shark"
    },
    {
        id: 125,
        nombre: "GYMSHARK X CBUM WASHED HOODIE",
        categoria: "Hombre",
        precio: 2000.00,
        stock: 1,
        imagen1: "hombre/125.webp",
        imagen2: "hombre/125.1.webp",
        talla: "L",
        tallaBase: "L",
        tipo: "Hoodie",
        color: "Negro",
        marca: "Gym Shark"
    },
    {
        id: 126,
        nombre: "GYMSHARK X CBUM WASHED HOODIE",
        categoria: "Hombre",
        precio: 2000.00,
        stock: 1,
        imagen1: "hombre/126.webp",
        imagen2: "hombre/126.1.webp",
        talla: "M",
        tallaBase: "M",
        tipo: "Hoodie",
        color: "Gris",
        marca: "Gym Shark"
    },
    {
        id: 127,
        nombre: "GYMSHARK X CBUM WASHED HOODIE",
        categoria: "Hombre",
        precio: 2000.00,
        stock: 1,
        imagen1: "hombre/127.webp",
        imagen2: "hombre/127.1.webp",
        talla: "M",
        tallaBase: "M",
        tipo: "Hoodie",
        color: "Morado",
        marca: "Gym Shark"
    },
    {
        id: 128,
        nombre: "LEGACY DROP ARM TANK",
        categoria: "Hombre",
        precio: 500.00,
        stock: 1,
        imagen1: "hombre/128.webp",
        imagen2: "hombre/128.1.webp",
        talla: "M",
        tallaBase: "M",
        tipo: "Tank Top",
        color: "Blanco",
        marca: "Gym Shark"
    },
    {
        id: 129,
        nombre: "NUMERALS HOODIE",
        categoria: "Hombre",
        precio: 900.00,
        stock: 1,
        imagen1: "hombre/129.webp",
        imagen2: "hombre/129.1.webp",
        talla: "L",
        tallaBase: "L",
        tipo: "Hoodie",
        color: "Negro",
        marca: "Gym Shark"
    },
    {
        id: 130,
        nombre: "NUMERALS HOODIE",
        categoria: "Hombre",
        precio: 900.00,
        stock: 2,
        imagen1: "hombre/130.webp",
        imagen2: "hombre/130.1.webp",
        talla: "M",
        tallaBase: "M",
        tipo: "Hoodie",
        color: "Negro",
        marca: "Gym Shark"
    },
    {
        id: 131,
        nombre: "NUMERLAS HOODIE",
        categoria: "Hombre",
        precio: 800.00,
        stock: 1,
        imagen1: "hombre/131.webp",
        imagen2: "hombre/131.1.jpg",
        talla: "S",
        tallaBase: "S",
        tipo: "Hoodie",
        color: "Negro",
        marca: "Gym Shark"
    },
    {
        id: 132,
        nombre: "PANTS ELITE TALL",
        categoria: "Hombre",
        precio: 800.00,
        stock: 1,
        imagen1: "hombre/132.webp",
        imagen2: "hombre/132.1.webp",
        talla: "30",
        tallaBase: "30",
        tipo: "Pants",
        color: "Azul",
        marca: "Gym Shark"
    },
    {
        id: 133,
        nombre: "PANTS ELITE TALL",
        categoria: "Hombre",
        precio: 800.00,
        stock: 1,
        imagen1: "hombre/133.webp",
        imagen2: "hombre/133.1.webp",
        talla: "30",
        tallaBase: "30",
        tipo: "Pants",
        color: "Negro",
        marca: "Gym Shark"
    },
    {
        id: 134,
        nombre: "PANTS ELITE TALL",
        categoria: "Hombre",
        precio: 800.00,
        stock: 1,
        imagen1: "hombre/134.webp",
        imagen2: "hombre/134.1.webp",
        talla: "32",
        tallaBase: "32",
        tipo: "Pants",
        color: "Azul",
        marca: "Gym Shark"
    },
    {
        id: 135,
        nombre: "PANTS ELITE TALL",
        categoria: "Hombre",
        precio: 800.00,
        stock: 1,
        imagen1: "hombre/135.webp",
        imagen2: "hombre/135.1.webp",
        talla: "32",
        tallaBase: "32",
        tipo: "Pants",
        color: "Negro",
        marca: "Gym Shark"
    },
    {
        id: 136,
        nombre: "REVENGE CROP CUT-OFFS",
        categoria: "Hombre",
        precio: 900.00,
        stock: 1,
        imagen1: "hombre/136.webp",
        imagen2: "hombre/136.1.webp",
        talla: "L",
        tallaBase: "L",
        tipo: "Tank Top",
        color: "Gris",
        marca: "YoungLA"
    },
    {
        id: 137,
        nombre: "REVENGE TEES SPRING",
        categoria: "Hombre",
        precio: 1050.00,
        stock: 1,
        imagen1: "hombre/137.webp",
        imagen2: "",
        talla: "M",
        tallaBase: "M",
        tipo: "T-Shirt",
        color: "Gris",
        marca: "YoungLA"
    },
    {
        id: 138,
        nombre: "RUNNING 4 2 IN 1 SHORTS",
        categoria: "Hombre",
        precio: 600.00,
        stock: 1,
        imagen1: "hombre/138.webp",
        imagen2: "hombre/138.1.webp",
        talla: "S",
        tallaBase: "S",
        tipo: "Short",
        color: "Marrón",
        marca: "Gym Shark"
    },
    {
        id: 139,
        nombre: "RUNNING 4 2 IN 1 SHORTS",
        categoria: "Hombre",
        precio: 700.00,
        stock: 1,
        imagen1: "hombre/139.webp",
        imagen2: "hombre/139.1.webp",
        talla: "M",
        tallaBase: "M",
        tipo: "Short",
        color: "Verde",
        marca: "Gym Shark"
    },
    {
        id: 140,
        nombre: "SPORT 7 2 IN 1 SHORTS",
        categoria: "Hombre",
        precio: 600.00,
        stock: 1,
        imagen1: "hombre/140.webp",
        imagen2: "hombre/140.1.webp",
        talla: "M",
        tallaBase: "M",
        tipo: "Short",
        color: "Gris",
        marca: "Gym Shark"
    },
    {
        id: 141,
        nombre: "SPORT 7 2 IN 1 SHORTS",
        categoria: "Hombre",
        precio: 600.00,
        stock: 1,
        imagen1: "hombre/141.webp",
        imagen2: "hombre/141.1.webp",
        talla: "S",
        tallaBase: "S",
        tipo: "Short",
        color: "Gris",
        marca: "Gym Shark"
    },
    {
        id: 142,
        nombre: "SPORT 7 2 IN 1 SHORTS",
        categoria: "Hombre",
        precio: 600.00,
        stock: 1,
        imagen1: "hombre/142.webp",
        imagen2: "hombre/142.1.webp",
        talla: "S",
        tallaBase: "S",
        tipo: "Short",
        color: "Azul",
        marca: "Gym Shark"
    },
    {
        id: 143,
        nombre: "STRAIGHT LEG PUMPER PANTS",
        categoria: "Hombre",
        precio: 1850.00,
        stock: 1,
        imagen1: "hombre/143.webp",
        imagen2: "hombre/143.1.webp",
        talla: "L",
        tallaBase: "L",
        tipo: "Pants",
        color: "Gris",
        marca: "Gym Shark"
    },
    {
        id: 144,
        nombre: "YUGIOH JERSEY",
        categoria: "Hombre",
        precio: 1100.00,
        stock: 1,
        imagen1: "hombre/144.webp",
        imagen2: "hombre/144.1.webp",
        talla: "L",
        tallaBase: "L",
        tipo: "Jersey",
        color: "Negro",
        marca: "YoungLA"
    }
];
