// =============================================================================
// STOCK MUJER - Archivo separado para subir/cambiar el catálogo de mujer aparte.
// Añade aquí los productos con categoria: "Mujer". Usa imágenes en carpeta mujer/
// (ej: mujer/1.jpeg). Misma estructura que en script.js (id, nombre, categoria,
// precio, stock, imagen1, imagen2, talla, tallaBase, tipo, color).
// =============================================================================
const productosMujer = [
    {
        id: 1001,
        nombre: "Flex - Short",
        categoria: "Mujer",
        precio: 550.00,
        stock: 1,
        imagen1: "mujer/1.jpeg",
        imagen2: "mujer/1.1.jpeg",
        talla: "XS - Body Fit",
        tallaBase: "XS",
        tipo: "Short",
        color: "Gris"
    },
    {
        id: 1002,
        nombre: "Simmons - Short",
        categoria: "Mujer",
        precio: 550.00,
        stock: 1,
        imagen1: "mujer/2.jpeg",
        imagen2: "mujer/2.1.jpeg",
        talla: "XS - Body Fit",
        tallaBase: "XS",
        tipo: "Short",
        color: "Azul"
    },
    {
        id: 1003,
        nombre: "Power Tight - Short",
        categoria: "Mujer",
        precio: 550.00,
        stock: 1,
        imagen1: "mujer/3.jpeg",
        imagen2: "mujer/3.1.jpeg",
        talla: "S - Body Fit",
        tallaBase: "S",
        tipo: "Short",
        color: "Negro"
    },
    {
        id: 1004,
        nombre: "Soft Sculpt - Short",
        categoria: "Mujer",
        precio: 550.00,
        stock: 1,
        imagen1: "mujer/4.jpeg",
        imagen2: "mujer/4.1.jpeg",
        talla: "XS - Body Fit",
        tallaBase: "XS",
        tipo: "Short",
        color: "Rosa"
    },
    {
        id: 1005,
        nombre: "Flex Short - Short",
        categoria: "Mujer",
        precio: 550.00,
        stock: 1,
        imagen1: "mujer/5.jpeg",
        imagen2: "mujer/5.1.jpeg",
        talla: "XS - Body Fit",
        tallaBase: "XS",
        tipo: "Short",
        color: "Negro"
    },
    {
        id: 1006,
        nombre: "Vital Seamless - Short",
        categoria: "Mujer",
        precio: 550.00,
        stock: 1,
        imagen1: "mujer/6.jpeg",
        imagen2: "mujer/6.1.jpeg",
        talla: "XS - Body Fit",
        tallaBase: "XS",
        tipo: "Short",
        color: "Negro"
    },
    {
        id: 1007,
        nombre: "Waffle - Short",
        categoria: "Mujer",
        precio: 550.00,
        stock: 1,
        imagen1: "mujer/7.jpeg",
        imagen2: "mujer/7.1.jpeg",
        talla: "S - Regular Fit",
        tallaBase: "S",
        tipo: "Short",
        color: "Gris"
    },
    {
        id: 1008,
        nombre: "Training - Leggings",
        categoria: "Mujer",
        precio: 700.00,
        stock: 1,
        imagen1: "mujer/8.jpeg",
        imagen2: "mujer/8.1.jpeg",
        talla: "XS - Body Fit",
        tallaBase: "XS",
        tipo: "Leggings",
        color: "Negro"
    },
    {
        id: 1009,
        nombre: "Gains Seamless - Leggings",
        categoria: "Mujer",
        precio: 700.00,
        stock: 1,
        imagen1: "mujer/9.jpeg",
        imagen2: "mujer/9.1.jpeg",
        talla: "XS - Body Fit",
        tallaBase: "XS",
        tipo: "Leggings",
        color: "Negro"
    },
    {
        id: 1010,
        nombre: "Elevate - Leggings",
        categoria: "Mujer",
        precio: 700.00,
        stock: 1,
        imagen1: "mujer/10.jpeg",
        imagen2: "mujer/10.1.jpeg",
        talla: "XS - Body Fit",
        tallaBase: "XS",
        tipo: "Leggings",
        color: "Negro"
    },,
    {
        id: 1011,
        nombre: "Elevate - Leggings",
        categoria: "Mujer",
        precio: 700.00,
        stock: 1,
        imagen1: "mujer/10.jpeg",
        imagen2: "mujer/10.1.jpeg",
        talla: "S - Body Fit",
        tallaBase: "S",
        tipo: "Leggings",
        color: "Negro"
    },
    {
        id: 1012,
        nombre: "Cargo Pants - Pants",
        categoria: "Mujer",
        precio: 750.00,
        stock: 1,
        imagen1: "mujer/11.jpeg",
        imagen2: "mujer/11.1.jpeg",
        talla: "S - Regular Fit",
        tallaBase: "S",
        tipo: "Pants",
        color: "Verde"
    },
    {
        id: 1013,
        nombre: "Adapt Fleck - Sport Bra",
        categoria: "Mujer",
        precio: 550.00,
        stock: 1,
        imagen1: "mujer/12.jpeg",
        imagen2: "mujer/12.1.jpeg",
        talla: "XS - Medium Support",
        tallaBase: "XS",
        tipo: "Sport Bra",
        color: "Negro"
    },
    {
        id: 1014,
        nombre: "Adapt Fleck - Sport Bra",
        categoria: "Mujer",
        precio: 550.00,
        stock: 1,
        imagen1: "mujer/12.jpeg",
        imagen2: "mujer/12.1.jpeg",
        talla: "S - Medium Support",
        tallaBase: "S",
        tipo: "Sport Bra",
        color: "Negro"
    },
    {
        id: 1015,
        nombre: "Sport Seamless - Sport Bra",
        categoria: "Mujer",
        precio: 550.00,
        stock: 1,
        imagen1: "mujer/13.jpeg",
        imagen2: "mujer/13.1.jpeg",
        talla: "XS - Light Support",
        tallaBase: "XS",
        tipo: "Sport Bra",
        color: "Gris"
    },
    {
        id: 1016,
        nombre: "Sport Seamless - Sport Bra",
        categoria: "Mujer",
        precio: 550.00,
        stock: 1,
        imagen1: "mujer/13.jpeg",
        imagen2: "mujer/13.1.jpeg",
        talla: "S - Light Support",
        tallaBase: "S",
        tipo: "Sport Bra",
        color: "Negro"
    },
    {
        id: 1017,
        nombre: "Adapt Fleck - Sport Bra",
        categoria: "Mujer",
        precio: 550.00,
        stock: 1,
        imagen1: "mujer/14.jpeg",
        imagen2: "mujer/14.1.jpeg",
        talla: "XS - Medium Support",
        tallaBase: "XS",
        tipo: "Sport Bra",
        color: "Morado"
    },
    {
        id: 1018,
        nombre: "T Back - Sport Bra",
        categoria: "Mujer",
        precio: 550.00,
        stock: 1,
        imagen1: "mujer/15.jpeg",
        imagen2: "mujer/15.1.jpeg",
        talla: "XS - Light Support",
        tallaBase: "XS",
        tipo: "Sport Bra",
        color: "Azul"
    },
    {
        id: 1019,
        nombre: "Sport Bra - Sport Bra",
        categoria: "Mujer",
        precio: 550.00,
        stock: 1,
        imagen1: "mujer/16.jpeg",
        imagen2: "mujer/16.1.jpeg",
        talla: "XS - Light Support",
        tallaBase: "XS",
        tipo: "Sport Bra",
        color: "Azul"
    },
    {
        id: 1020,
        nombre: "Double Up - Sport Bra",
        categoria: "Mujer",
        precio: 550.00,
        stock: 1,
        imagen1: "mujer/17.jpeg",
        imagen2: "mujer/17.1.jpeg",
        talla: "XS - Medium Support",
        tallaBase: "XS",
        tipo: "Sport Bra",
        color: "Negro"
    },
    {
        id: 1021,
        nombre: "Vital Seamless - Body Suit",
        categoria: "Mujer",
        precio: 1000.00,
        stock: 1,
        imagen1: "mujer/18.jpeg",
        imagen2: "mujer/18.1.jpeg",
        talla: "XS - Body Fit",
        tallaBase: "XS",
        tipo: "Body Suit",
        color: "Negro"
    },
    {
        id: 1022,
        nombre: "Vital Seamless - Body Suit",
        categoria: "Mujer",
        precio: 1000.00,
        stock: 1,
        imagen1: "mujer/18.jpeg",
        imagen2: "mujer/18.1.jpeg",
        talla: "S - Body Fit",
        tallaBase: "S",
        tipo: "Body Suit",
        color: "Negro"
    },
    {
        id: 1023,
        nombre: "Corset Seamless - Crop Top",
        categoria: "Mujer",
        precio: 650.00,
        stock: 1,
        imagen1: "mujer/19.jpeg",
        imagen2: "mujer/19.1.jpeg",
        talla: "XS - Body Fit",
        tallaBase: "XS",
        tipo: "Crop Top",
        color: "Azul"
    },
    {
        id: 1024,
        nombre: "Long Sleeve - Crop top",
        categoria: "Mujer",
        precio: 650.00,
        stock: 1,
        imagen1: "mujer/20.jpeg",
        imagen2: "mujer/20.1.jpeg",
        talla: "XS - Body Fit",
        tallaBase: "XS",
        tipo: "Crop Top",
        color: "Morado"
    },
    {
        id: 1025,
        nombre: "Long Sleeve - Crop top",
        categoria: "Mujer",
        precio: 650.00,
        stock: 1,
        imagen1: "mujer/21.jpeg",
        imagen2: "mujer/21.1.jpeg",
        talla: "XS - Body Fit",
        tallaBase: "XS",
        tipo: "Crop Top",
        color: "Naranja"
    },
    {
        id: 1026,
        nombre: "Long Sleeve - Crop top",
        categoria: "Mujer",
        precio: 650.00,
        stock: 1,
        imagen1: "mujer/22.jpeg",
        imagen2: "mujer/22.1.jpeg",
        talla: "XS - Body Fit",
        tallaBase: "XS",
        tipo: "Crop Top",
        color: "Verde"
    },
    {
        id: 1027,
        nombre: "Boat Neck - Crop top",
        categoria: "Mujer",
        precio: 650.00,
        stock: 1,
        imagen1: "mujer/23.jpeg",
        imagen2: "mujer/23.1.jpeg",
        talla: "S - Body Fit",
        tallaBase: "S",
        tipo: "Crop Top",
        color: "Rosa"
    },
    {
        id: 1028,
        nombre: "Boat Neck - Crop top",
        categoria: "Mujer",
        precio: 650.00,
        stock: 1,
        imagen1: "mujer/23.jpeg",
        imagen2: "mujer/23.1.jpeg",
        talla: "L - Body Fit",
        tallaBase: "L",
        tipo: "Crop Top",
        color: "Rosa"
    },
    {
        id: 1029,
        nombre: "Adapt Animal - Crop top",
        categoria: "Mujer",
        precio: 650.00,
        stock: 1,
        imagen1: "mujer/24.jpeg",
        imagen2: "mujer/24.1.jpeg",
        talla: "S - Body Fit",
        tallaBase: "S",
        tipo: "Crop Top",
        color: "Cafe"
    },
    {
        id: 1030,
        nombre: "Adapt Animal - Crop top",
        categoria: "Mujer",
        precio: 650.00,
        stock: 1,
        imagen1: "mujer/24.jpeg",
        imagen2: "mujer/24.1.jpeg",
        talla: "M - Body Fit",
        tallaBase: "M",
        tipo: "Crop Top",
        color: "Cafe"
    },
    {
        id: 1031,
        nombre: "Contrast - Mid Tee",
        categoria: "Mujer",
        precio: 650.00,
        stock: 1,
        imagen1: "mujer/25.jpeg",
        imagen2: "",
        talla: "XS - Body Fit",
        tallaBase: "XS",
        tipo: "Mid Tee",
        color: "Negro"
    }
];
