// =============================================================================
// STOCK MUJER — Generado automáticamente con scripts/importar-stock.py
// Fuente: Google Sheets (hoja INVENTARIO, columna T = HOMBRE/MUJER)
// Edita el sheet y vuelve a ejecutar el script para actualizar.
// =============================================================================
const productosMujer = [
    {
        id: 1,
        nombre: "ADAPT ANIMAL SEMALESS CROP TOP",
        categoria: "Mujer",
        precio: 650.00,
        stock: 2,
        imagen1: "mujer/1.webp",
        imagen2: "mujer/1.1.webp",
        talla: "M",
        tallaBase: "M",
        tipo: "Crop Top",
        color: "Marrón",
        marca: "Gym Shark",
        precioMayoreo: 0.00,
        mayoreo: false,
        posicionCarrusel: 1
    },
    {
        id: 2,
        nombre: "ADAPT ANIMAL SEMALESS CROP TOP",
        categoria: "Mujer",
        precio: 650.00,
        stock: 2,
        imagen1: "mujer/2.webp",
        imagen2: "mujer/2.1.webp",
        talla: "S",
        tallaBase: "S",
        tipo: "Crop Top",
        color: "Marrón",
        marca: "Gym Shark",
        precioMayoreo: 0.00,
        mayoreo: false,
        posicionCarrusel: 0
    },
    {
        id: 3,
        nombre: "ADAPT FLECK LEGGINGS",
        categoria: "Mujer",
        precio: 900.00,
        stock: 1,
        imagen1: "mujer/3.webp",
        imagen2: "mujer/3.1.webp",
        talla: "S",
        tallaBase: "S",
        tipo: "Leggings",
        color: "Verde",
        marca: "Gym Shark",
        precioMayoreo: 0.00,
        mayoreo: false,
        posicionCarrusel: 0
    },
    {
        id: 4,
        nombre: "ADAPT FLECK SPORTS BRA",
        categoria: "Mujer",
        precio: 550.00,
        stock: 1,
        imagen1: "mujer/4.webp",
        imagen2: "mujer/4.1.webp",
        talla: "XS",
        tallaBase: "XS",
        tipo: "Sport Bra",
        color: "Negro",
        marca: "Gym Shark",
        precioMayoreo: 0.00,
        mayoreo: false,
        posicionCarrusel: 0
    },
    {
        id: 5,
        nombre: "ADAPT FLECK SPORTS BRA",
        categoria: "Mujer",
        precio: 550.00,
        stock: 1,
        imagen1: "mujer/5.webp",
        imagen2: "mujer/5.1.webp",
        talla: "S",
        tallaBase: "S",
        tipo: "Sport Bra",
        color: "Negro",
        marca: "Gym Shark",
        precioMayoreo: 0.00,
        mayoreo: false,
        posicionCarrusel: 0
    },
    {
        id: 6,
        nombre: "ADAPT FLECK SPORTS BRA",
        categoria: "Mujer",
        precio: 550.00,
        stock: 1,
        imagen1: "mujer/6.webp",
        imagen2: "mujer/6.1.webp",
        talla: "XS",
        tallaBase: "XS",
        tipo: "Sport Bra",
        color: "Morado",
        marca: "Gym Shark",
        precioMayoreo: 0.00,
        mayoreo: false,
        posicionCarrusel: 0
    },
    {
        id: 7,
        nombre: "ADAPT FLECK T-BACK BRA",
        categoria: "Mujer",
        precio: 550.00,
        stock: 1,
        imagen1: "mujer/7.png",
        imagen2: "mujer/7.1.png",
        talla: "XS",
        tallaBase: "XS",
        tipo: "Sport Bra",
        color: "Verde",
        marca: "Gym Shark",
        precioMayoreo: 0.00,
        mayoreo: false,
        posicionCarrusel: 0
    },
    {
        id: 8,
        nombre: "CAMPUS CLASSIC",
        categoria: "Mujer",
        precio: 700.00,
        stock: 1,
        imagen1: "mujer/8.webp",
        imagen2: "mujer/8.1.webp",
        talla: "S",
        tallaBase: "S",
        tipo: "Short",
        color: "Verde",
        marca: "Gym Shark",
        precioMayoreo: 0.00,
        mayoreo: false,
        posicionCarrusel: 0
    },
    {
        id: 9,
        nombre: "CAMPUS CLASSIC",
        categoria: "Mujer",
        precio: 700.00,
        stock: 1,
        imagen1: "mujer/9.webp",
        imagen2: "mujer/9.1.webp",
        talla: "M",
        tallaBase: "M",
        tipo: "Short",
        color: "Verde",
        marca: "Gym Shark",
        precioMayoreo: 0.00,
        mayoreo: false,
        posicionCarrusel: 0
    },
    {
        id: 10,
        nombre: "CONTRAT SEAMLESS MIDI TEE",
        categoria: "Mujer",
        precio: 650.00,
        stock: 2,
        imagen1: "mujer/10.webp",
        imagen2: "mujer/10.1.webp",
        talla: "XS",
        tallaBase: "XS",
        tipo: "T-Shirt",
        color: "Negro",
        marca: "Gym Shark",
        precioMayoreo: 0.00,
        mayoreo: false,
        posicionCarrusel: 0
    },
    {
        id: 11,
        nombre: "CORSET SEAMLESS CROP TOP",
        categoria: "Mujer",
        precio: 650.00,
        stock: 2,
        imagen1: "mujer/11.webp",
        imagen2: "mujer/11.1.webp",
        talla: "XS",
        tallaBase: "XS",
        tipo: "Crop Top",
        color: "Azul",
        marca: "Gym Shark",
        precioMayoreo: 0.00,
        mayoreo: false,
        posicionCarrusel: 0
    },
    {
        id: 12,
        nombre: "ELEVATE LEGGINGS 2.0",
        categoria: "Mujer",
        precio: 700.00,
        stock: 2,
        imagen1: "mujer/12.webp",
        imagen2: "mujer/12.1.webp",
        talla: "XS",
        tallaBase: "XS",
        tipo: "Leggings",
        color: "Negro",
        marca: "Gym Shark",
        precioMayoreo: 0.00,
        mayoreo: false,
        posicionCarrusel: 0
    },
    {
        id: 13,
        nombre: "ELEVATE LEGGINGS 2.0",
        categoria: "Mujer",
        precio: 700.00,
        stock: 1,
        imagen1: "mujer/13.webp",
        imagen2: "mujer/13.1.webp",
        talla: "S",
        tallaBase: "S",
        tipo: "Leggings",
        color: "Negro",
        marca: "Gym Shark",
        precioMayoreo: 0.00,
        mayoreo: false,
        posicionCarrusel: 0
    },
    {
        id: 14,
        nombre: "EVERYWEAR WARP KNIT FLARE",
        categoria: "Mujer",
        precio: 1500.00,
        stock: 1,
        imagen1: "mujer/14.webp",
        imagen2: "mujer/14.1.webp",
        talla: "M",
        tallaBase: "M",
        tipo: "Leggings",
        color: "Azul",
        marca: "Gym Shark",
        precioMayoreo: 0.00,
        mayoreo: false,
        posicionCarrusel: 0
    },
    {
        id: 15,
        nombre: "EVERYWEAR WARP KNIT FLARE",
        categoria: "Mujer",
        precio: 1500.00,
        stock: 1,
        imagen1: "mujer/15.webp",
        imagen2: "mujer/15.1.webp",
        talla: "M",
        tallaBase: "M",
        tipo: "Leggings",
        color: "Negro",
        marca: "Gym Shark",
        precioMayoreo: 0.00,
        mayoreo: false,
        posicionCarrusel: 0
    },
    {
        id: 16,
        nombre: "FLEX SHORTS",
        categoria: "Mujer",
        precio: 550.00,
        stock: 1,
        imagen1: "mujer/16.webp",
        imagen2: "mujer/16.1.webp",
        talla: "XS",
        tallaBase: "XS",
        tipo: "Short",
        color: "Negro",
        marca: "Gym Shark",
        precioMayoreo: 0.00,
        mayoreo: false,
        posicionCarrusel: 0
    },
    {
        id: 17,
        nombre: "FLEX SHORTS",
        categoria: "Mujer",
        precio: 550.00,
        stock: 2,
        imagen1: "mujer/17.webp",
        imagen2: "mujer/17.1.webp",
        talla: "XS",
        tallaBase: "XS",
        tipo: "Short",
        color: "Gris",
        marca: "Gym Shark",
        precioMayoreo: 0.00,
        mayoreo: false,
        posicionCarrusel: 0
    },
    {
        id: 18,
        nombre: "FLEX SHORTS",
        categoria: "Mujer",
        precio: 550.00,
        stock: 1,
        imagen1: "mujer/18.webp",
        imagen2: "mujer/18.1.webp",
        talla: "S",
        tallaBase: "S",
        tipo: "Short",
        color: "Gris",
        marca: "Gym Shark",
        precioMayoreo: 0.00,
        mayoreo: false,
        posicionCarrusel: 0
    },
    {
        id: 19,
        nombre: "GYMSHARK X WHITNEY SIMMONS",
        categoria: "Mujer",
        precio: 550.00,
        stock: 2,
        imagen1: "mujer/19.webp",
        imagen2: "mujer/19.1.webp",
        talla: "XS",
        tallaBase: "XS",
        tipo: "Short",
        color: "Azul",
        marca: "Gym Shark",
        precioMayoreo: 0.00,
        mayoreo: false,
        posicionCarrusel: 0
    },
    {
        id: 20,
        nombre: "LIFT VARSITY LEGGINGS",
        categoria: "Mujer",
        precio: 950.00,
        stock: 1,
        imagen1: "mujer/20.webp",
        imagen2: "mujer/20.1.webp",
        talla: "L",
        tallaBase: "L",
        tipo: "Leggings",
        color: "Rojo",
        marca: "Gym Shark",
        precioMayoreo: 0.00,
        mayoreo: false,
        posicionCarrusel: 0
    },
    {
        id: 21,
        nombre: "LIFT VARSITY SHORT",
        categoria: "Mujer",
        precio: 850.00,
        stock: 1,
        imagen1: "mujer/21.webp",
        imagen2: "mujer/21.1.webp",
        talla: "S",
        tallaBase: "S",
        tipo: "Short",
        color: "Negro",
        marca: "Gym Shark",
        precioMayoreo: 0.00,
        mayoreo: false,
        posicionCarrusel: 0
    },
    {
        id: 22,
        nombre: "LIFT VARSITY SHORT",
        categoria: "Mujer",
        precio: 850.00,
        stock: 1,
        imagen1: "mujer/22.webp",
        imagen2: "mujer/22.1.webp",
        talla: "S",
        tallaBase: "S",
        tipo: "Short",
        color: "Rojo",
        marca: "Gym Shark",
        precioMayoreo: 0.00,
        mayoreo: false,
        posicionCarrusel: 0
    },
    {
        id: 23,
        nombre: "POWER TIGHT SHORTS",
        categoria: "Mujer",
        precio: 750.00,
        stock: 1,
        imagen1: "mujer/23.webp",
        imagen2: "mujer/23.1.webp",
        talla: "S",
        tallaBase: "S",
        tipo: "Short",
        color: "Negro",
        marca: "Gym Shark",
        precioMayoreo: 0.00,
        mayoreo: false,
        posicionCarrusel: 0
    },
    {
        id: 24,
        nombre: "REST DAY JOGGER",
        categoria: "Mujer",
        precio: 900.00,
        stock: 1,
        imagen1: "mujer/24.webp",
        imagen2: "mujer/24.1.webp",
        talla: "M",
        tallaBase: "M",
        tipo: "Joggers",
        color: "Verde",
        marca: "Gym Shark",
        precioMayoreo: 0.00,
        mayoreo: false,
        posicionCarrusel: 0
    },
    {
        id: 25,
        nombre: "REST DAY JOGGER",
        categoria: "Mujer",
        precio: 900.00,
        stock: 1,
        imagen1: "mujer/25.webp",
        imagen2: "mujer/25.1.webp",
        talla: "S",
        tallaBase: "S",
        tipo: "Joggers",
        color: "Verde",
        marca: "Gym Shark",
        precioMayoreo: 0.00,
        mayoreo: false,
        posicionCarrusel: 0
    },
    {
        id: 26,
        nombre: "REST DAY SEAMLESS MODAL BOAT NECK CROP TOP",
        categoria: "Mujer",
        precio: 650.00,
        stock: 1,
        imagen1: "mujer/26.webp",
        imagen2: "mujer/26.1.webp",
        talla: "L",
        tallaBase: "L",
        tipo: "Crop Top",
        color: "Rosa",
        marca: "Gym Shark",
        precioMayoreo: 0.00,
        mayoreo: false,
        posicionCarrusel: 0
    },
    {
        id: 27,
        nombre: "REST DAY SEAMLESS MODAL BOAT NECK CROP TOP",
        categoria: "Mujer",
        precio: 650.00,
        stock: 2,
        imagen1: "mujer/27.webp",
        imagen2: "mujer/27.1.webp",
        talla: "S",
        tallaBase: "S",
        tipo: "Crop Top",
        color: "Rosa",
        marca: "Gym Shark",
        precioMayoreo: 0.00,
        mayoreo: false,
        posicionCarrusel: 0
    },
    {
        id: 28,
        nombre: "SPORT SEAMLESS SPORTS BRA",
        categoria: "Mujer",
        precio: 550.00,
        stock: 2,
        imagen1: "mujer/28.webp",
        imagen2: "mujer/28.1.webp",
        talla: "S",
        tallaBase: "S",
        tipo: "Sport Bra",
        color: "Gris",
        marca: "Gym Shark",
        precioMayoreo: 0.00,
        mayoreo: false,
        posicionCarrusel: 2
    },
    {
        id: 29,
        nombre: "SPORT SEAMLESS SPORTS BRA",
        categoria: "Mujer",
        precio: 550.00,
        stock: 2,
        imagen1: "mujer/29.webp",
        imagen2: "mujer/29.1.webp",
        talla: "XS",
        tallaBase: "XS",
        tipo: "Sport Bra",
        color: "Gris",
        marca: "Gym Shark",
        precioMayoreo: 0.00,
        mayoreo: false,
        posicionCarrusel: 0
    },
    {
        id: 30,
        nombre: "TRAINING LEGGINGS",
        categoria: "Mujer",
        precio: 700.00,
        stock: 2,
        imagen1: "mujer/30.webp",
        imagen2: "mujer/30.1.webp",
        talla: "XS",
        tallaBase: "XS",
        tipo: "Leggings",
        color: "Negro",
        marca: "Gym Shark",
        precioMayoreo: 0.00,
        mayoreo: false,
        posicionCarrusel: 0
    },
    {
        id: 31,
        nombre: "VITAL SEAMLESS 7 INCH",
        categoria: "Mujer",
        precio: 550.00,
        stock: 1,
        imagen1: "mujer/31.webp",
        imagen2: "mujer/31.1.webp",
        talla: "XS",
        tallaBase: "XS",
        tipo: "Short",
        color: "Negro",
        marca: "Gym Shark",
        precioMayoreo: 0.00,
        mayoreo: false,
        posicionCarrusel: 0
    },
    {
        id: 32,
        nombre: "VITAL SCULPT SEAMLESS SHORT",
        categoria: "Mujer",
        precio: 550.00,
        stock: 1,
        imagen1: "mujer/32.webp",
        imagen2: "mujer/32.1.webp",
        talla: "M",
        tallaBase: "M",
        tipo: "Short",
        color: "Negro",
        marca: "Gym Shark",
        precioMayoreo: 0.00,
        mayoreo: false,
        posicionCarrusel: 0
    },
    {
        id: 33,
        nombre: "VITAL SEAMLESS SLEEVE CUT OUT TOP",
        categoria: "Mujer",
        precio: 650.00,
        stock: 2,
        imagen1: "mujer/33.webp",
        imagen2: "mujer/33.1.webp",
        talla: "XS",
        tallaBase: "XS",
        tipo: "Long Sleeve",
        color: "Rojo",
        marca: "Gym Shark",
        precioMayoreo: 0.00,
        mayoreo: false,
        posicionCarrusel: 0
    },
    {
        id: 35,
        nombre: "WOMEN CARGO PANTS",
        categoria: "Mujer",
        precio: 750.00,
        stock: 2,
        imagen1: "mujer/35.webp",
        imagen2: "mujer/35.1.webp",
        talla: "S",
        tallaBase: "S",
        tipo: "Pants",
        color: "Verde",
        marca: "Gym Shark",
        precioMayoreo: 0.00,
        mayoreo: false,
        posicionCarrusel: 0
    },
    {
        id: 36,
        nombre: "PEEK A BOO SPORTS BRA",
        categoria: "Mujer",
        precio: 500.00,
        stock: 1,
        imagen1: "mujer/36.webp",
        imagen2: "mujer/36.1.webp",
        talla: "S",
        tallaBase: "S",
        tipo: "Sport Bra",
        color: "Blanco",
        marca: "Gym Shark",
        precioMayoreo: 0.00,
        mayoreo: false,
        posicionCarrusel: 0
    },
    {
        id: 37,
        nombre: "STRAIGHT HEADBAND",
        categoria: "Mujer",
        precio: 250.00,
        stock: 2,
        imagen1: "mujer/37.webp",
        imagen2: "mujer/37.1.webp",
        talla: "ONE SIZE",
        tallaBase: "ONE SIZE",
        tipo: "Band",
        color: "Blanco",
        marca: "Gym Shark",
        precioMayoreo: 0.00,
        mayoreo: false,
        posicionCarrusel: 0
    },
    {
        id: 38,
        nombre: "TWIST HEADBAND",
        categoria: "Mujer",
        precio: 250.00,
        stock: 2,
        imagen1: "mujer/38.webp",
        imagen2: "mujer/38.1.webp",
        talla: "ONE SIZE",
        tallaBase: "ONE SIZE",
        tipo: "Band",
        color: "Negro",
        marca: "Gym Shark",
        precioMayoreo: 0.00,
        mayoreo: false,
        posicionCarrusel: 0
    },
    {
        id: 39,
        nombre: "TWIST HEADBAND",
        categoria: "Mujer",
        precio: 250.00,
        stock: 2,
        imagen1: "mujer/39.webp",
        imagen2: "mujer/39.1.webp",
        talla: "ONE SIZE",
        tallaBase: "ONE SIZE",
        tipo: "Band",
        color: "Blanco",
        marca: "Gym Shark",
        precioMayoreo: 0.00,
        mayoreo: false,
        posicionCarrusel: 0
    },
    {
        id: 41,
        nombre: "PEEK A BOO SPORTS BRA",
        categoria: "Mujer",
        precio: 500.00,
        stock: 2,
        imagen1: "mujer/41.webp",
        imagen2: "mujer/41.1.webp",
        talla: "S",
        tallaBase: "S",
        tipo: "Sport Bra",
        color: "Negro",
        marca: "Gym Shark",
        precioMayoreo: 0.00,
        mayoreo: false,
        posicionCarrusel: 0
    },
    {
        id: 42,
        nombre: "VITAL SOFT SHORT",
        categoria: "Mujer",
        precio: 550.00,
        stock: 1,
        imagen1: "mujer/42.webp",
        imagen2: "mujer/42.1.webp",
        talla: "M",
        tallaBase: "M",
        tipo: "Short",
        color: "Negro",
        marca: "Gym Shark",
        precioMayoreo: 0.00,
        mayoreo: false,
        posicionCarrusel: 0
    },
    {
        id: 43,
        nombre: "BACK GAINS SPORTS BRA",
        categoria: "Mujer",
        precio: 500.00,
        stock: 2,
        imagen1: "mujer/43.webp",
        imagen2: "mujer/43.1.webp",
        talla: "M",
        tallaBase: "M",
        tipo: "Sport Bra",
        color: "Rojo",
        marca: "Gym Shark",
        precioMayoreo: 0.00,
        mayoreo: false,
        posicionCarrusel: 0
    },
    {
        id: 44,
        nombre: "COLLEGIATE GRAPHIC JOGGERS",
        categoria: "Mujer",
        precio: 750.00,
        stock: 1,
        imagen1: "mujer/44.webp",
        imagen2: "mujer/44.1.webp",
        talla: "M",
        tallaBase: "M",
        tipo: "Joggers",
        color: "Azul",
        marca: "Gym Shark",
        precioMayoreo: 0.00,
        mayoreo: false,
        posicionCarrusel: 0
    },
    {
        id: 45,
        nombre: "COLLEGIATE GRAPHIC JOGGERS",
        categoria: "Mujer",
        precio: 750.00,
        stock: 1,
        imagen1: "mujer/45.webp",
        imagen2: "mujer/45.1.jpg",
        talla: "L",
        tallaBase: "L",
        tipo: "Joggers",
        color: "Azul",
        marca: "Gym Shark",
        precioMayoreo: 0.00,
        mayoreo: false,
        posicionCarrusel: 0
    },
    {
        id: 46,
        nombre: "JUICY PEACH LONG SLEEVE T-SHIRT",
        categoria: "Mujer",
        precio: 600.00,
        stock: 1,
        imagen1: "mujer/46.webp",
        imagen2: "mujer/46.1.webp",
        talla: "L",
        tallaBase: "L",
        tipo: "Long Sleeve",
        color: "Rosa",
        marca: "Gym Shark",
        precioMayoreo: 0.00,
        mayoreo: false,
        posicionCarrusel: 0
    },
    {
        id: 47,
        nombre: "JUICY PEACH LONG SLEEVE T-SHIRT",
        categoria: "Mujer",
        precio: 600.00,
        stock: 1,
        imagen1: "mujer/47.webp",
        imagen2: "mujer/47.1.webp",
        talla: "M",
        tallaBase: "M",
        tipo: "Long Sleeve",
        color: "Blanco",
        marca: "Gym Shark",
        precioMayoreo: 0.00,
        mayoreo: false,
        posicionCarrusel: 0
    },
    {
        id: 49,
        nombre: "JUICY PEACH LONG SLEEVE T-SHIRT",
        categoria: "Mujer",
        precio: 600.00,
        stock: 1,
        imagen1: "mujer/49.webp",
        imagen2: "mujer/49.1.webp",
        talla: "L",
        tallaBase: "L",
        tipo: "Long Sleeve",
        color: "Blanco",
        marca: "Gym Shark",
        precioMayoreo: 0.00,
        mayoreo: false,
        posicionCarrusel: 0
    },
    {
        id: 50,
        nombre: "JUICY PEACH LONG SLEEVE T-SHIRT",
        categoria: "Mujer",
        precio: 600.00,
        stock: 1,
        imagen1: "mujer/50.webp",
        imagen2: "mujer/50.1.webp",
        talla: "M",
        tallaBase: "M",
        tipo: "Long Sleeve",
        color: "Rosa",
        marca: "Gym Shark",
        precioMayoreo: 0.00,
        mayoreo: false,
        posicionCarrusel: 0
    },
    {
        id: 51,
        nombre: "JUICY PEACH LONG SLEEVE T-SHIRT",
        categoria: "Mujer",
        precio: 600.00,
        stock: 1,
        imagen1: "mujer/51.webp",
        imagen2: "mujer/51.1.webp",
        talla: "S",
        tallaBase: "S",
        tipo: "Long Sleeve",
        color: "Blanco",
        marca: "Gym Shark",
        precioMayoreo: 0.00,
        mayoreo: false,
        posicionCarrusel: 0
    },
    {
        id: 52,
        nombre: "JUICY PEACH SHORT SLEEVE T-SHIRT",
        categoria: "Mujer",
        precio: 550.00,
        stock: 1,
        imagen1: "mujer/52.webp",
        imagen2: "mujer/52.1.webp",
        talla: "M",
        tallaBase: "M",
        tipo: "T-Shirt",
        color: "Blanco",
        marca: "Gym Shark",
        precioMayoreo: 0.00,
        mayoreo: false,
        posicionCarrusel: 0
    },
    {
        id: 54,
        nombre: "JUICY PEACH SHORT SLEEVE T-SHIRT",
        categoria: "Mujer",
        precio: 550.00,
        stock: 1,
        imagen1: "mujer/54.webp",
        imagen2: "mujer/54.1.webp",
        talla: "S",
        tallaBase: "S",
        tipo: "T-Shirt",
        color: "Blanco",
        marca: "Gym Shark",
        precioMayoreo: 0.00,
        mayoreo: false,
        posicionCarrusel: 0
    },
    {
        id: 54,
        nombre: "JUICY PEACH SHORT SLEEVE T-SHIRT",
        categoria: "Mujer",
        precio: 550.00,
        stock: 1,
        imagen1: "mujer/54.webp",
        imagen2: "mujer/54.1.webp",
        talla: "S",
        tallaBase: "S",
        tipo: "T-Shirt",
        color: "Blanco",
        marca: "Gym Shark",
        precioMayoreo: 0.00,
        mayoreo: false,
        posicionCarrusel: 0
    },
    {
        id: 55,
        nombre: "JUICY PEACH SHORT SLEEVE T-SHIRT",
        categoria: "Mujer",
        precio: 550.00,
        stock: 1,
        imagen1: "mujer/55.webp",
        imagen2: "mujer/55.1.webp",
        talla: "L",
        tallaBase: "L",
        tipo: "T-Shirt",
        color: "Negro",
        marca: "Gym Shark",
        precioMayoreo: 0.00,
        mayoreo: false,
        posicionCarrusel: 0
    },
    {
        id: 58,
        nombre: "RETRO STRIPE SNAP PANTS",
        categoria: "Mujer",
        precio: 750.00,
        stock: 1,
        imagen1: "mujer/58.webp",
        imagen2: "mujer/58.1.webp",
        talla: "L",
        tallaBase: "L",
        tipo: "Pants",
        color: "Azul",
        marca: "Gym Shark",
        precioMayoreo: 0.00,
        mayoreo: false,
        posicionCarrusel: 0
    },
    {
        id: 59,
        nombre: "RETRO STRIPE SNAP PANTS",
        categoria: "Mujer",
        precio: 750.00,
        stock: 1,
        imagen1: "mujer/59.webp",
        imagen2: "mujer/59.1.webp",
        talla: "M",
        tallaBase: "M",
        tipo: "Joggers",
        color: "Azul",
        marca: "Gym Shark",
        precioMayoreo: 0.00,
        mayoreo: false,
        posicionCarrusel: 0
    },
    {
        id: 60,
        nombre: "STRENGTH GRAPHIC JOGGERS",
        categoria: "Mujer",
        precio: 750.00,
        stock: 1,
        imagen1: "mujer/60.webp",
        imagen2: "mujer/60.1.webp",
        talla: "L",
        tallaBase: "L",
        tipo: "Joggers",
        color: "Morado",
        marca: "Gym Shark",
        precioMayoreo: 0.00,
        mayoreo: false,
        posicionCarrusel: 0
    },
    {
        id: 62,
        nombre: "SUPERSOFT STRAIGHT LEG PANT",
        categoria: "Mujer",
        precio: 750.00,
        stock: 1,
        imagen1: "mujer/62.webp",
        imagen2: "mujer/62.1.webp",
        talla: "M",
        tallaBase: "M",
        tipo: "Pants",
        color: "Rosa",
        marca: "Gym Shark",
        precioMayoreo: 0.00,
        mayoreo: false,
        posicionCarrusel: 0
    },
    {
        id: 63,
        nombre: "SUPERSOFT STRAIGHT LEG PANT",
        categoria: "Mujer",
        precio: 750.00,
        stock: 1,
        imagen1: "mujer/63.webp",
        imagen2: "mujer/63.1.webp",
        talla: "L",
        tallaBase: "L",
        tipo: "Joggers",
        color: "Rosa",
        marca: "Gym Shark",
        precioMayoreo: 0.00,
        mayoreo: false,
        posicionCarrusel: 0
    },
    {
        id: 64,
        nombre: "SUPERSOFT STRAIGHT LEG PANT",
        categoria: "Mujer",
        precio: 750.00,
        stock: 1,
        imagen1: "mujer/64.webp",
        imagen2: "mujer/64.1.webp",
        talla: "S",
        tallaBase: "S",
        tipo: "Pants",
        color: "Rosa",
        marca: "Gym Shark",
        precioMayoreo: 0.00,
        mayoreo: false,
        posicionCarrusel: 0
    },
    {
        id: 65,
        nombre: "VELOCITY SHORTS",
        categoria: "Mujer",
        precio: 900.00,
        stock: 1,
        imagen1: "mujer/65.webp",
        imagen2: "",
        talla: "L",
        tallaBase: "L",
        tipo: "Short",
        color: "Negro",
        marca: "YoungLA",
        precioMayoreo: 0.00,
        mayoreo: false,
        posicionCarrusel: 0
    },
    {
        id: 66,
        nombre: "VELOCY SPORTS BRA",
        categoria: "Mujer",
        precio: 850.00,
        stock: 1,
        imagen1: "mujer/66.webp",
        imagen2: "mujer/66.1.webp",
        talla: "L",
        tallaBase: "L",
        tipo: "Sport Bra",
        color: "Negro",
        marca: "YoungLA",
        precioMayoreo: 0.00,
        mayoreo: false,
        posicionCarrusel: 0
    },
    {
        id: 67,
        nombre: "COSY LUXE ZIP THROUGH HOODIE",
        categoria: "Mujer",
        precio: 750.00,
        stock: 1,
        imagen1: "mujer/67.webp",
        imagen2: "mujer/67.1.webp",
        talla: "XS",
        tallaBase: "XS",
        tipo: "Hoodie",
        color: "Azul",
        marca: "Gym Shark",
        precioMayoreo: 660.00,
        mayoreo: false,
        posicionCarrusel: 0
    },
    {
        id: 68,
        nombre: "CHAINSTITCH GRAPHIC HOODIE",
        categoria: "Mujer",
        precio: 750.00,
        stock: 1,
        imagen1: "mujer/68.webp",
        imagen2: "mujer/68.1.webp",
        talla: "XS",
        tallaBase: "XS",
        tipo: "Hoodie",
        color: "Rosa",
        marca: "Gym Shark",
        precioMayoreo: 660.00,
        mayoreo: false,
        posicionCarrusel: 0
    },
    {
        id: 69,
        nombre: "COSY LUXE ZIP THROUGH HOODIE",
        categoria: "Mujer",
        precio: 750.00,
        stock: 1,
        imagen1: "mujer/69.webp",
        imagen2: "mujer/69.1.webp",
        talla: "M",
        tallaBase: "M",
        tipo: "Hoodie",
        color: "Azul",
        marca: "Gym Shark",
        precioMayoreo: 660.00,
        mayoreo: false,
        posicionCarrusel: 3
    },
    {
        id: 70,
        nombre: "COSY LUXE ZIP THROUGH HOODIE",
        categoria: "Mujer",
        precio: 750.00,
        stock: 1,
        imagen1: "mujer/70.webp",
        imagen2: "mujer/70.1.webp",
        talla: "S",
        tallaBase: "S",
        tipo: "Hoodie",
        color: "Azul",
        marca: "Gym Shark",
        precioMayoreo: 600.00,
        mayoreo: false,
        posicionCarrusel: 0
    },
    {
        id: 71,
        nombre: "TRAINING OVERSIZED FLEECE HOODIE",
        categoria: "Mujer",
        precio: 750.00,
        stock: 1,
        imagen1: "mujer/71.webp",
        imagen2: "mujer/71.1.webp",
        talla: "S",
        tallaBase: "S",
        tipo: "Hoodie",
        color: "Morado",
        marca: "Gym Shark",
        precioMayoreo: 600.00,
        mayoreo: false,
        posicionCarrusel: 0
    },
    {
        id: 72,
        nombre: "CHAINSTITCH GRAPHIC HOODIE",
        categoria: "Mujer",
        precio: 750.00,
        stock: 1,
        imagen1: "mujer/72.webp",
        imagen2: "mujer/72.1.webp",
        talla: "L",
        tallaBase: "L",
        tipo: "Hoodie",
        color: "Rosa",
        marca: "Gym Shark",
        precioMayoreo: 630.00,
        mayoreo: false,
        posicionCarrusel: 0
    },
    {
        id: 74,
        nombre: "CHAINSTITCH GRAPHIC HOODIE",
        categoria: "Mujer",
        precio: 750.00,
        stock: 1,
        imagen1: "mujer/74.webp",
        imagen2: "mujer/74.1.webp",
        talla: "S",
        tallaBase: "S",
        tipo: "Hoodie",
        color: "Rosa",
        marca: "Gym Shark",
        precioMayoreo: 600.00,
        mayoreo: false,
        posicionCarrusel: 0
    },
    {
        id: 75,
        nombre: "EVERYDAY SEAMLESS LEGGINGS",
        categoria: "Mujer",
        precio: 750.00,
        stock: 1,
        imagen1: "mujer/75.webp",
        imagen2: "mujer/75.1.webp",
        talla: "XS",
        tallaBase: "XS",
        tipo: "Leggings",
        color: "Azul",
        marca: "Gym Shark",
        precioMayoreo: 600.00,
        mayoreo: true,
        posicionCarrusel: 0
    },
    {
        id: 76,
        nombre: "LIGHT HOLD LEGGINGS",
        categoria: "Mujer",
        precio: 750.00,
        stock: 1,
        imagen1: "mujer/76.webp",
        imagen2: "mujer/76.1.webp",
        talla: "L",
        tallaBase: "L",
        tipo: "Leggings",
        color: "Negro",
        marca: "Gym Shark",
        precioMayoreo: 600.00,
        mayoreo: true,
        posicionCarrusel: 0
    },
    {
        id: 77,
        nombre: "LIGHT HOLD LEGGINGS",
        categoria: "Mujer",
        precio: 750.00,
        stock: 1,
        imagen1: "mujer/77.webp",
        imagen2: "mujer/77.1.webp",
        talla: "M",
        tallaBase: "M",
        tipo: "Leggings",
        color: "Negro",
        marca: "Gym Shark",
        precioMayoreo: 600.00,
        mayoreo: true,
        posicionCarrusel: 0
    },
    {
        id: 78,
        nombre: "LIGHT HOLD LEGGINGS",
        categoria: "Mujer",
        precio: 750.00,
        stock: 1,
        imagen1: "mujer/78.jpg",
        imagen2: "mujer/78.1.webp",
        talla: "S",
        tallaBase: "S",
        tipo: "Leggings",
        color: "Negro",
        marca: "Gym Shark",
        precioMayoreo: 600.00,
        mayoreo: true,
        posicionCarrusel: 0
    },
    {
        id: 79,
        nombre: "EVERYDAY SEAMLESS TIGHT FIT CREW NECK TEE",
        categoria: "Mujer",
        precio: 550.00,
        stock: 1,
        imagen1: "mujer/79.webp",
        imagen2: "mujer/79.1.webp",
        talla: "L",
        tallaBase: "L",
        tipo: "T-Shirt",
        color: "Blanco",
        marca: "Gym Shark",
        precioMayoreo: 440.00,
        mayoreo: true,
        posicionCarrusel: 0
    },
    {
        id: 80,
        nombre: "EVERYDAY SEAMLESS TIGHT FIT CREW NECK TEE",
        categoria: "Mujer",
        precio: 550.00,
        stock: 1,
        imagen1: "mujer/80.webp",
        imagen2: "mujer/80.1.webp",
        talla: "M",
        tallaBase: "M",
        tipo: "T-Shirt",
        color: "Blanco",
        marca: "Gym Shark",
        precioMayoreo: 440.00,
        mayoreo: true,
        posicionCarrusel: 0
    },
    {
        id: 81,
        nombre: "EVERYDAY SEAMLESS TIGHT FIT CREW NECK TEE",
        categoria: "Mujer",
        precio: 550.00,
        stock: 1,
        imagen1: "mujer/81.webp",
        imagen2: "mujer/81.1.webp",
        talla: "S",
        tallaBase: "S",
        tipo: "T-Shirt",
        color: "Blanco",
        marca: "Gym Shark",
        precioMayoreo: 440.00,
        mayoreo: true,
        posicionCarrusel: 0
    },
    {
        id: 82,
        nombre: "RUCHED STRAPPY SPORTS BRA",
        categoria: "Mujer",
        precio: 500.00,
        stock: 1,
        imagen1: "mujer/82.webp",
        imagen2: "mujer/82.1.webp",
        talla: "XS",
        tallaBase: "XS",
        tipo: "Sport Bra",
        color: "Azul",
        marca: "Gym Shark",
        precioMayoreo: 400.00,
        mayoreo: true,
        posicionCarrusel: 0
    },
    {
        id: 83,
        nombre: "RUCHED STRAPPY SPORTS BRA",
        categoria: "Mujer",
        precio: 500.00,
        stock: 1,
        imagen1: "mujer/83.webp",
        imagen2: "mujer/83.1.webp",
        talla: "S",
        tallaBase: "S",
        tipo: "Sport Bra",
        color: "Azul",
        marca: "Gym Shark",
        precioMayoreo: 400.00,
        mayoreo: true,
        posicionCarrusel: 0
    },
    {
        id: 84,
        nombre: "VITAL CROP TOP",
        categoria: "Mujer",
        precio: 600.00,
        stock: 1,
        imagen1: "mujer/84.webp",
        imagen2: "mujer/84.1.webp",
        talla: "XS",
        tallaBase: "XS",
        tipo: "Crop Top",
        color: "Negro",
        marca: "Gym Shark",
        precioMayoreo: 480.00,
        mayoreo: true,
        posicionCarrusel: 0
    },
    {
        id: 87,
        nombre: "TRAINING BABY TEE",
        categoria: "Mujer",
        precio: 550.00,
        stock: 1,
        imagen1: "mujer/87.webp",
        imagen2: "mujer/87.1.webp",
        talla: "M",
        tallaBase: "M",
        tipo: "T-Shirt",
        color: "Blanco",
        marca: "Gym Shark",
        precioMayoreo: 440.00,
        mayoreo: true,
        posicionCarrusel: 0
    },
    {
        id: 88,
        nombre: "TRAINING BABY TEE",
        categoria: "Mujer",
        precio: 550.00,
        stock: 1,
        imagen1: "mujer/88.webp",
        imagen2: "mujer/88.1.webp",
        talla: "S",
        tallaBase: "S",
        tipo: "T-Shirt",
        color: "Blanco",
        marca: "Gym Shark",
        precioMayoreo: 440.00,
        mayoreo: true,
        posicionCarrusel: 0
    },
    {
        id: 90,
        nombre: "LIGHT HOLD SHORTS",
        categoria: "Mujer",
        precio: 550.00,
        stock: 1,
        imagen1: "mujer/90.webp",
        imagen2: "mujer/90.1.jpg",
        talla: "L",
        tallaBase: "L",
        tipo: "Short",
        color: "Rosa",
        marca: "Gym Shark",
        precioMayoreo: 440.00,
        mayoreo: true,
        posicionCarrusel: 0
    },
    {
        id: 91,
        nombre: "LIGHT HOLD SHORTS",
        categoria: "Mujer",
        precio: 550.00,
        stock: 1,
        imagen1: "mujer/91.webp",
        imagen2: "mujer/91.1.jpg",
        talla: "M",
        tallaBase: "M",
        tipo: "Short",
        color: "Rosa",
        marca: "Gym Shark",
        precioMayoreo: 440.00,
        mayoreo: true,
        posicionCarrusel: 0
    },
    {
        id: 92,
        nombre: "EVERYDAY MINI TOTE BAG",
        categoria: "Mujer",
        precio: 500.00,
        stock: 1,
        imagen1: "mujer/92.webp",
        imagen2: "mujer/92.1.webp",
        talla: "ONE SIZE",
        tallaBase: "ONE SIZE",
        tipo: "Bag",
        color: "Negro",
        marca: "Gym Shark",
        precioMayoreo: 400.00,
        mayoreo: true,
        posicionCarrusel: 0
    },
    {
        id: 94,
        nombre: "PIPING SPORTS BRA",
        categoria: "Mujer",
        precio: 500.00,
        stock: 1,
        imagen1: "mujer/94.webp",
        imagen2: "mujer/94.1.webp",
        talla: "XS",
        tallaBase: "XS",
        tipo: "Sport Bra",
        color: "Rojo",
        marca: "Gym Shark",
        precioMayoreo: 400.00,
        mayoreo: true,
        posicionCarrusel: 0
    },
    {
        id: 95,
        nombre: "PIPING SPORTS BRA",
        categoria: "Mujer",
        precio: 500.00,
        stock: 1,
        imagen1: "mujer/95.webp",
        imagen2: "mujer/95.1.webp",
        talla: "M",
        tallaBase: "M",
        tipo: "Sport Bra",
        color: "Rojo",
        marca: "Gym Shark",
        precioMayoreo: 400.00,
        mayoreo: true,
        posicionCarrusel: 6
    },
    {
        id: 96,
        nombre: "LOVE LIFTING GRAPHIC TOTE BAG",
        categoria: "Mujer",
        precio: 600.00,
        stock: 2,
        imagen1: "mujer/96.webp",
        imagen2: "mujer/96.1.webp",
        talla: "ONE SIZE",
        tallaBase: "ONE SIZE",
        tipo: "Bag",
        color: "Rojo",
        marca: "Gym Shark",
        precioMayoreo: 480.00,
        mayoreo: true,
        posicionCarrusel: 5
    },
    {
        id: 98,
        nombre: "EVERYDAY SEAMLESS CROP TANK",
        categoria: "Mujer",
        precio: 500.00,
        stock: 1,
        imagen1: "mujer/98.webp",
        imagen2: "mujer/98.1.webp",
        talla: "M",
        tallaBase: "M",
        tipo: "Crop Tank",
        color: "Azul",
        marca: "Gym Shark",
        precioMayoreo: 400.00,
        mayoreo: true,
        posicionCarrusel: 7
    },
    {
        id: 99,
        nombre: "PEEK A BOO SPORTS BRA",
        categoria: "Mujer",
        precio: 500.00,
        stock: 1,
        imagen1: "mujer/99.webp",
        imagen2: "mujer/99.1.webp",
        talla: "S",
        tallaBase: "S",
        tipo: "Sport Bra",
        color: "Blanco",
        marca: "Gym Shark",
        precioMayoreo: 400.00,
        mayoreo: true,
        posicionCarrusel: 8
    },
    {
        id: 100,
        nombre: "PEEK A BOO SPORTS BRA",
        categoria: "Mujer",
        precio: 500.00,
        stock: 1,
        imagen1: "mujer/100.webp",
        imagen2: "mujer/100.1.webp",
        talla: "XS",
        tallaBase: "XS",
        tipo: "Sport Bra",
        color: "Negro",
        marca: "Gym Shark",
        precioMayoreo: 400.00,
        mayoreo: true,
        posicionCarrusel: 0
    },
    {
        id: 101,
        nombre: "BACK GAINS SPORTS BRA",
        categoria: "Mujer",
        precio: 500.00,
        stock: 1,
        imagen1: "mujer/101.webp",
        imagen2: "mujer/101.1.webp",
        talla: "XS",
        tallaBase: "XS",
        tipo: "Sport Bra",
        color: "Azul",
        marca: "Gym Shark",
        precioMayoreo: 400.00,
        mayoreo: true,
        posicionCarrusel: 0
    },
    {
        id: 105,
        nombre: "PIPING MIDI CREW NECK",
        categoria: "Mujer",
        precio: 650.00,
        stock: 1,
        imagen1: "mujer/105.webp",
        imagen2: "mujer/105.1.webp",
        talla: "L",
        tallaBase: "L",
        tipo: "Sweater",
        color: "Azul",
        marca: "Gym Shark",
        precioMayoreo: 520.00,
        mayoreo: true,
        posicionCarrusel: 0
    },
    {
        id: 106,
        nombre: "PIPING MIDI CREW NECK",
        categoria: "Mujer",
        precio: 650.00,
        stock: 1,
        imagen1: "mujer/106.webp",
        imagen2: "mujer/106.1.webp",
        talla: "M",
        tallaBase: "M",
        tipo: "Sweater",
        color: "Azul",
        marca: "Gym Shark",
        precioMayoreo: 520.00,
        mayoreo: true,
        posicionCarrusel: 0
    },
    {
        id: 108,
        nombre: "PIPING LONG SLEEVE CROP TOP",
        categoria: "Mujer",
        precio: 600.00,
        stock: 1,
        imagen1: "mujer/108.webp",
        imagen2: "mujer/108.1.webp",
        talla: "S",
        tallaBase: "S",
        tipo: "Crop Top",
        color: "Rojo",
        marca: "Gym Shark",
        precioMayoreo: 460.00,
        mayoreo: false,
        posicionCarrusel: 0
    },
    {
        id: 109,
        nombre: "PIPING BANDEAU WITH SHELF",
        categoria: "Mujer",
        precio: 550.00,
        stock: 1,
        imagen1: "mujer/109.webp",
        imagen2: "mujer/109.1.webp",
        talla: "S",
        tallaBase: "S",
        tipo: "Top",
        color: "Rojo",
        marca: "Gym Shark",
        precioMayoreo: 460.00,
        mayoreo: false,
        posicionCarrusel: 0
    },
    {
        id: 110,
        nombre: "PIPING BANDEAU WITH SHELF",
        categoria: "Mujer",
        precio: 550.00,
        stock: 1,
        imagen1: "mujer/110.webp",
        imagen2: "mujer/110.1.webp",
        talla: "L",
        tallaBase: "L",
        tipo: "Top",
        color: "Rojo",
        marca: "Gym Shark",
        precioMayoreo: 460.00,
        mayoreo: false,
        posicionCarrusel: 0
    },
    {
        id: 111,
        nombre: "PIPING LONG SLEEVE CROP TOP",
        categoria: "Mujer",
        precio: 600.00,
        stock: 1,
        imagen1: "mujer/111.webp",
        imagen2: "mujer/111.1.jpg",
        talla: "M",
        tallaBase: "M",
        tipo: "Crop Top",
        color: "Rojo",
        marca: "Gym Shark",
        precioMayoreo: 460.00,
        mayoreo: false,
        posicionCarrusel: 0
    },
    {
        id: 112,
        nombre: "PIPING BANDEAU WITH SHELF",
        categoria: "Mujer",
        precio: 550.00,
        stock: 1,
        imagen1: "mujer/112.webp",
        imagen2: "mujer/112.1.webp",
        talla: "M",
        tallaBase: "M",
        tipo: "Top",
        color: "Rojo",
        marca: "Gym Shark",
        precioMayoreo: 460.00,
        mayoreo: false,
        posicionCarrusel: 0
    },
    {
        id: 113,
        nombre: "PIPING LONG SLEEVE CROP TOP",
        categoria: "Mujer",
        precio: 600.00,
        stock: 1,
        imagen1: "mujer/113.webp",
        imagen2: "mujer/113.1.webp",
        talla: "M",
        tallaBase: "M",
        tipo: "Crop Top",
        color: "Azul",
        marca: "Gym Shark",
        precioMayoreo: 460.00,
        mayoreo: false,
        posicionCarrusel: 0
    },
    {
        id: 114,
        nombre: "PIPING BANDEAU WITH SHELF",
        categoria: "Mujer",
        precio: 550.00,
        stock: 1,
        imagen1: "mujer/114.webp",
        imagen2: "mujer/114.1.webp",
        talla: "S",
        tallaBase: "S",
        tipo: "Top",
        color: "Azul",
        marca: "Gym Shark",
        precioMayoreo: 460.00,
        mayoreo: false,
        posicionCarrusel: 0
    },
    {
        id: 115,
        nombre: "PIPING BANDEAU WITH SHELF",
        categoria: "Mujer",
        precio: 550.00,
        stock: 1,
        imagen1: "mujer/115.webp",
        imagen2: "mujer/115.1.webp",
        talla: "L",
        tallaBase: "L",
        tipo: "Top",
        color: "Azul",
        marca: "Gym Shark",
        precioMayoreo: 460.00,
        mayoreo: false,
        posicionCarrusel: 0
    },
    {
        id: 117,
        nombre: "PIPING BANDEAU WITH SHELF",
        categoria: "Mujer",
        precio: 550.00,
        stock: 1,
        imagen1: "mujer/117.webp",
        imagen2: "mujer/117.1.webp",
        talla: "M",
        tallaBase: "M",
        tipo: "Top",
        color: "Azul",
        marca: "Gym Shark",
        precioMayoreo: 460.00,
        mayoreo: false,
        posicionCarrusel: 0
    },
    {
        id: 118,
        nombre: "VITAL SEAMLESS 2.0 CROP TOP",
        categoria: "Mujer",
        precio: 600.00,
        stock: 1,
        imagen1: "mujer/118.webp",
        imagen2: "mujer/118.1.webp",
        talla: "M",
        tallaBase: "M",
        tipo: "Crop Top",
        color: "Negro",
        marca: "Gym Shark",
        precioMayoreo: 480.00,
        mayoreo: true,
        posicionCarrusel: 0
    },
    {
        id: 119,
        nombre: "EVERYDAY FOLDOVER LEGGINGS",
        categoria: "Mujer",
        precio: 750.00,
        stock: 1,
        imagen1: "mujer/119.webp",
        imagen2: "mujer/119.1.webp",
        talla: "XS",
        tallaBase: "XS",
        tipo: "Leggings",
        color: "Negro",
        marca: "Gym Shark",
        precioMayoreo: 600.00,
        mayoreo: true,
        posicionCarrusel: 0
    },
    {
        id: 120,
        nombre: "CONTRAST SEAMLESS CROP TOP",
        categoria: "Mujer",
        precio: 650.00,
        stock: 1,
        imagen1: "mujer/120.webp",
        imagen2: "mujer/120.1.webp",
        talla: "M",
        tallaBase: "M",
        tipo: "Crop Top",
        color: "Marrón",
        marca: "Gym Shark",
        precioMayoreo: 630.00,
        mayoreo: false,
        posicionCarrusel: 0
    },
    {
        id: 121,
        nombre: "CONTRAST SEAMLESS CROP TOP",
        categoria: "Mujer",
        precio: 650.00,
        stock: 1,
        imagen1: "mujer/121.webp",
        imagen2: "mujer/121.1.webp",
        talla: "S",
        tallaBase: "S",
        tipo: "Crop Top",
        color: "Marrón",
        marca: "Gym Shark",
        precioMayoreo: 630.00,
        mayoreo: false,
        posicionCarrusel: 0
    },
    {
        id: 122,
        nombre: "PEEK A BOO SPORTS BRA",
        categoria: "Mujer",
        precio: 500.00,
        stock: 1,
        imagen1: "mujer/122.webp",
        imagen2: "mujer/122.1.webp",
        talla: "XS",
        tallaBase: "XS",
        tipo: "Sport Bra",
        color: "Negro",
        marca: "Gym Shark",
        precioMayoreo: 400.00,
        mayoreo: true,
        posicionCarrusel: 0
    },
    {
        id: 123,
        nombre: "RUCHED STRAPPY SPORTS BRA",
        categoria: "Mujer",
        precio: 500.00,
        stock: 1,
        imagen1: "mujer/123.webp",
        imagen2: "mujer/123.1.webp",
        talla: "XS",
        tallaBase: "XS",
        tipo: "Sport Bra",
        color: "Morado",
        marca: "Gym Shark",
        precioMayoreo: 400.00,
        mayoreo: true,
        posicionCarrusel: 0
    },
    {
        id: 125,
        nombre: "EVERYDAY MINI TOTE BAG",
        categoria: "Mujer",
        precio: 500.00,
        stock: 1,
        imagen1: "mujer/125.webp",
        imagen2: "mujer/125.1.webp",
        talla: "ONE SIZE",
        tallaBase: "ONE SIZE",
        tipo: "Bag",
        color: "Rojo",
        marca: "Gym Shark",
        precioMayoreo: 400.00,
        mayoreo: true,
        posicionCarrusel: 0
    },
    {
        id: 126,
        nombre: "LEGACY REGULAR LEGGINGS",
        categoria: "Mujer",
        precio: 750.00,
        stock: 1,
        imagen1: "mujer/126.webp",
        imagen2: "mujer/126.1.webp",
        talla: "XS",
        tallaBase: "XS",
        tipo: "Leggings",
        color: "Negro",
        marca: "Gym Shark",
        precioMayoreo: 600.00,
        mayoreo: true,
        posicionCarrusel: 0
    },
    {
        id: 127,
        nombre: "ADAPT ANIMAL SEAMLESS LEGGINGS",
        categoria: "Mujer",
        precio: 750.00,
        stock: 1,
        imagen1: "mujer/127.webp",
        imagen2: "mujer/127.1.webp",
        talla: "S",
        tallaBase: "S",
        tipo: "Leggings",
        color: "Negro",
        marca: "Gym Shark",
        precioMayoreo: 600.00,
        mayoreo: true,
        posicionCarrusel: 0
    },
    {
        id: 128,
        nombre: "LEGACY REGULAR LEGGINGS",
        categoria: "Mujer",
        precio: 750.00,
        stock: 1,
        imagen1: "mujer/128.webp",
        imagen2: "mujer/128.1.webp",
        talla: "S",
        tallaBase: "S",
        tipo: "Leggings",
        color: "Negro",
        marca: "Gym Shark",
        precioMayoreo: 600.00,
        mayoreo: true,
        posicionCarrusel: 0
    },
    {
        id: 129,
        nombre: "SUPERSOFT STRAIGHT LEG PANT",
        categoria: "Mujer",
        precio: 750.00,
        stock: 1,
        imagen1: "mujer/129.webp",
        imagen2: "mujer/129.1.webp",
        talla: "XS",
        tallaBase: "XS",
        tipo: "Pants",
        color: "Gris",
        marca: "Gym Shark",
        precioMayoreo: 600.00,
        mayoreo: true,
        posicionCarrusel: 0
    },
    {
        id: 130,
        nombre: "FLEX SHORTS",
        categoria: "Mujer",
        precio: 550.00,
        stock: 1,
        imagen1: "mujer/130.webp",
        imagen2: "mujer/130.1.webp",
        talla: "XS",
        tallaBase: "XS",
        tipo: "Short",
        color: "Gris",
        marca: "Gym Shark",
        precioMayoreo: 420.00,
        mayoreo: false,
        posicionCarrusel: 0
    },
    {
        id: 131,
        nombre: "PIPING MIDI CREW NECK",
        categoria: "Mujer",
        precio: 650.00,
        stock: 1,
        imagen1: "mujer/131.webp",
        imagen2: "mujer/131.1.webp",
        talla: "L",
        tallaBase: "L",
        tipo: "Sweater",
        color: "Rojo",
        marca: "Gym Shark",
        precioMayoreo: 520.00,
        mayoreo: true,
        posicionCarrusel: 0
    },
    {
        id: 132,
        nombre: "PIPING MIDI CREW NECK",
        categoria: "Mujer",
        precio: 650.00,
        stock: 1,
        imagen1: "mujer/132.webp",
        imagen2: "mujer/132.1.webp",
        talla: "M",
        tallaBase: "M",
        tipo: "Sweater",
        color: "Rojo",
        marca: "Gym Shark",
        precioMayoreo: 520.00,
        mayoreo: true,
        posicionCarrusel: 0
    },
    {
        id: 133,
        nombre: "PIPING MIDI CREW NECK",
        categoria: "Mujer",
        precio: 650.00,
        stock: 1,
        imagen1: "mujer/133.webp",
        imagen2: "mujer/133.1.webp",
        talla: "S",
        tallaBase: "S",
        tipo: "Sweater",
        color: "Rojo",
        marca: "Gym Shark",
        precioMayoreo: 520.00,
        mayoreo: true,
        posicionCarrusel: 0
    },
    {
        id: 134,
        nombre: "VITAL SOFT SHORT",
        categoria: "Mujer",
        precio: 550.00,
        stock: 1,
        imagen1: "mujer/134.webp",
        imagen2: "mujer/134.1.webp",
        talla: "S",
        tallaBase: "S",
        tipo: "Short",
        color: "Negro",
        marca: "Gym Shark",
        precioMayoreo: 440.00,
        mayoreo: true,
        posicionCarrusel: 0
    },
    {
        id: 136,
        nombre: "AFTER DARK HOODIE W532",
        categoria: "Mujer",
        precio: 1500.00,
        stock: 1,
        imagen1: "mujer/136.webp",
        imagen2: "mujer/136.1.webp",
        talla: "M",
        tallaBase: "M",
        tipo: "Hoodie",
        color: "Rojo",
        marca: "YoungLA",
        precioMayoreo: 0.00,
        mayoreo: false,
        posicionCarrusel: 0
    },
    {
        id: 137,
        nombre: "AFTER DARK HOODIE W532",
        categoria: "Mujer",
        precio: 1500.00,
        stock: 1,
        imagen1: "mujer/137.webp",
        imagen2: "mujer/137.1.webp",
        talla: "L",
        tallaBase: "L",
        tipo: "Hoodie",
        color: "Gris",
        marca: "YoungLA",
        precioMayoreo: 0.00,
        mayoreo: false,
        posicionCarrusel: 0
    },
    {
        id: 138,
        nombre: "AFTER DARK JOGGERS W234",
        categoria: "Mujer",
        precio: 1400.00,
        stock: 1,
        imagen1: "mujer/138.webp",
        imagen2: "mujer/138.1.webp",
        talla: "M",
        tallaBase: "M",
        tipo: "Joggers",
        color: "Rojo",
        marca: "YoungLA",
        precioMayoreo: 0.00,
        mayoreo: false,
        posicionCarrusel: 0
    }
];
